TestFx.sln
scripts/Build.ps1
scripts/SetBuildNumber.ps1
scripts/build/TestFx.targets

Fixes to ensure that the file version changes in official builds. This was a constant earlier(14.0.0.0).

Ensure that that the file version changes

---

src/Adapter/MSTest.CoreAdapter/Discovery/UnitTestDiscoverer.cs
src/Adapter/MSTest.CoreAdapter/Helpers/RunSettingsUtilities.cs
src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj
src/Adapter/MSTest.CoreAdapter/MSTestDiscoverer.cs
src/Adapter/MSTest.CoreAdapter/RunConfigurationSettings.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/UnitTestDiscovererTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/RunSettingsUtilitiesTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/RunConfigurationSettingsTests.cs

Adapter should honour DesignMode flag

---

src/Adapter/MSTest.CoreAdapter/MSTestExecutor.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestExecutorTests.cs

Populated RunConfiguration Settings for RunAll.

Populated RunConfiguration Settings for RunAll.

---

src/Adapter/MSTest.CoreAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs
src/Adapter/MSTest.CoreAdapter/Extensions/ExceptionExtensions.cs
src/Adapter/MSTest.CoreAdapter/Extensions/TestResultExtensions.cs
src/Adapter/MSTest.CoreAdapter/Extensions/UnitTestOutcomeExtensions.cs
src/Adapter/MSTest.CoreAdapter/Helpers/UnitTestOutcomeHelper.cs
src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj
src/Adapter/MSTest.CoreAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.CoreAdapter/Resources/Resource.resx
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/TypeEnumeratorTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/ExceptionExtensionsTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/TestResultExtensionsTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/UnitTestOutcomeExtensionsTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/UnitTestOutcomeHelperTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestExecutorTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs

Fix for TestMethod failures masked by TestCleanUp exceptions

---

WizardExtensions/MSTestv2IntelliTestExtension/MSTestv2TestFramework.cs
WizardExtensions/MSTestv2IntelliTestExtension/MSTestv2TestFrameworkPackageAttribute.cs

Multiple copies getting added while running tests using Intellitest

---

src/Adapter/MSTest.CoreAdapter/Extensions/TestResultExtensions.cs
src/Adapter/MSTest.CoreAdapter/Helpers/UnitTestOutcomeHelper.cs
src/TestFramework/MSTest.Core/UnitTestOutcome.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/UnitTestOutcomeHelperTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/ObjectModel/UnitTestResultTests.cs

Fix for https://github.com/Microsoft/testfx/issues/217

Test outcome none mapping

---

scripts/test.ps1

Error exception was already there but handling it to add custom message.

Adding try catch block in Test script to Handle exception

---

scripts/test.ps1

Fixing test script to fail on test failures.

---

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumerator.cs
src/Adapter/MSTest.CoreAdapter/TestMethodFilter.cs
src/Adapter/PlatformServices.Desktop/RecursiveDirectoryPath.cs
src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs
src/Adapter/PlatformServices.Desktop/Services/DesktopTestSource.cs
src/Adapter/PlatformServices.Desktop/Utilities/AssemblyUtility.cs
src/Adapter/PlatformServices.Desktop/Utilities/DeploymentItemUtility.cs
src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs
src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestDeployment.cs
src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestSource.cs
src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TraceLogger.cs
src/Adapter/PlatformServices.Universal/Services/UniversalTestSource.cs
src/TestFramework/MSTest.Core/Assertions/Assert.cs
src/TestFramework/MSTest.Core/MSTest.Core.csproj.DotSettings
test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs
test/UnitTests/MSTest.Core.Unit.Tests/Attributes/DynamicDataAttributeTests.cs

Improvements to reduce ReSharper warnings. These were not mindlessly accepting ReShaper recommendations. I went through stuff by hand. 
If some of these could be done with stylecop, let me know I'll figure out how and make a PR to add tests there.

Reduction of Resharper errors.

---

Templates/CSharp/Desktop/ProjectTemplates/CSharp/Test/UnitTestProject.csproj
Templates/VisualBasic/Desktop/ProjectTemplates/VisualBasic/Test/UnitTestProject.vbproj

More details: https://developercommunity.visualstudio.com/content/problem/217774/directorybuildprops-ignored-by-c-unit-test-project.html

Add Microsoft.Common.props to Desktop templates

---

Templates/CSharp/Desktop/source.extension.vsixmanifest
Templates/CSharp/UWP/source.extension.vsixmanifest
Templates/VisualBasic/Desktop/source.extension.vsixmanifest
Templates/VisualBasic/UWP/source.extension.vsixmanifest
WizardExtensions/MSTestv2IntelliTestExtensionPackage/source.extension.vsixmanifest
WizardExtensions/MSTestv2UnitTestExtensionPackage/source.extension.vsixmanifest

Related DEVDIV bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594684?src=alerts&src-action=cta

Marking extensions as System Components to hide from Extensions UI

---

src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodRunnerTests.cs

This PR fixes issue #442 
It's just cleaning up the messages/suggestions by VS.
After these changes it'll looks like this:
No Messages shown!

Cleaned up messages

---

src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/UnitTestRunnerTests.cs

https://github.com/Microsoft/testfx/issues/503

CustomTestAttribute inheriting from TestClass attribute

---

src/Adapter/MSTest.CoreAdapter/Helpers/ReflectHelper.cs

https://github.com/Microsoft/testfx/issues/467

Related to #467. Adds direct cast to properly call the overloaded member

---

test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/ReflectHelperTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/TestableImplementations/TestableReflectHelper.cs

Issue: https://github.com/Microsoft/testfx/issues/263

unused return value in TestableReflectHelper

---

src/TestFramework/Extension.Desktop/PrivateObject.cs
src/TestFramework/Extension.Desktop/PrivateType.cs

Handling inner exceptions in Private Object

---

TestFx.sln
src/Adapter/PlatformServices.NetCore/Services/NetCoreTestContextImplementation.cs
src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10ThreadOperations.cs
test/E2ETests/Smoke.E2E.Tests/TimeoutTests.cs
test/E2ETests/TestAssets/TimeoutTestProjectNetCore/SelfTerminatingTestClass.cs
test/E2ETests/TestAssets/TimeoutTestProjectNetCore/TerimnateLongRunningTasksUsingTokenTestClass.cs
test/E2ETests/TestAssets/TimeoutTestProjectNetCore/TimeoutTestProjectNetCore.csproj

Added initialization that was missing in the NetCoreTestContext and added a test to cover the net core scenario as well.

Bugfix for CancellationTokenSource

---

azure-pipelines.yml
test/E2ETests/Automation.CLI/CLITestBase.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs
test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopThreadOperationsTests.cs

Azure Pipelines Support

---

scripts/build/TestFx.targets

Changed certs as SHA1 certificates have expired.

Certificate change SHA1 to hybrid

---

src/Adapter/MSTest.CoreAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestAssemblyInfoTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs

Make AssemblyCleanup/ClassCleanup execute even if Initialize fails.

---

scripts/Build.ps1
scripts/build/TestFx.targets
src/Adapter/PlatformServices.NetCore/PlatformServices.NetCore.csproj
test/E2ETests/TestAssets/DeploymentTestProjectNetCore/DeploymentTestProjectNetCore.csproj
test/E2ETests/TestAssets/FSharpTestProject/FSharpTestProject.fsproj
test/E2ETests/TestAssets/TimeoutTestProjectNetCore/TimeoutTestProjectNetCore.csproj

* `Microsoft402400` certificate is deprecated, replaced with `Microsoft400`

Replaced deprecated certificate

---

src/TestFramework/MSTest.Core/Assertions/Assert.cs
src/TestFramework/MSTest.Core/Internal/NullableAttributes.cs
src/TestFramework/MSTest.Core/MSTest.Core.csproj

Add nullable-annotated Assert.IsNotNull

---

scripts/verify-sign.ps1

- Added new thumbprint to verify-sign.ps1

Added new thumbprint

---

scripts/write-release-notes.ps1

This PR is mainly for checking that auto-merge is working.

Removed unnecessary whitespace

---

scripts/build/TestFx.Versions.targets
src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj
src/Adapter/MSTest.CoreAdapter/Properties/AssemblyInfo.cs
src/Adapter/MSTest.CoreAdapter/Properties/TestExtensionTypesAttribute.cs
src/Adapter/PlatformServices.Desktop/packages.config
src/Adapter/PlatformServices.Interface/packages.config
src/Adapter/PlatformServices.Portable/packages.config
test/ComponentTests/PlatformServices.Desktop.Component.Tests/packages.config
test/E2ETests/Automation.CLI/CLITestBase.cs
test/E2ETests/Automation.CLI/packages.config
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/packages.config
test/UnitTests/PlatformServices.Desktop.Unit.Tests/packages.config
test/UnitTests/PlatformServices.Portable.Unit.Tests/packages.config
test/UnitTests/PlatformServices.Universal.Unit.Tests/packages.config

Applied changes in https://github.com/microsoft/vstest/pull/2676.

Refactored `TypesToLoadAttribute` into `TestExtensionTypesAttribute`

---

src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/PlatformServices.Shared/netstandard1.3/Resources/xlf/Resource.ko.xlf

Hello,
I'm your MSFT Loc PM. This PR is about some fixes to previous translations.

[Loc] Updates

---

Nuget.config
scripts/toolset/packages.config

Removing deprecated nuget feeds

Fixing nugets

---

src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs

Merge session level parameters safely with source level parameters.

Merge parameters safely

---

src/TestFramework/MSTest.Core/Assertions/StringAssert.cs

Fix infinite iteration in Matches method

---

src/Package/MSTest.TestAdapter.Enu.nuspec
src/Package/MSTest.TestAdapter.nuspec
src/Package/MSTest.TestAdapter.symbols.nuspec

Added missing library to the NuGet package.

---

scripts/build/TestFx.Settings.targets
scripts/build/TestFx.targets

MSBuild scripts fixed

---

test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs

Added some AreEqual and AreNotEqual unit tests to increase code coverage incase of future mistakes.
Let me know if you want me to optimise these.

Added more AreEqual and AreNotEqual unit tests

---

Localize/lcl/ko/src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20210412164646888 to master with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20210412164646888 to master

---

Localize/lcl/ko/src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20210413165102761 to master with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20210413165102761 to master

---

src/Adapter/PlatformServices.WinUI/PlatformServices.WinUI.csproj
src/Adapter/PlatformServices.WinUI/Services/WinUITestSourceHost.cs

Small fix that was preventing tests from running from VS TestExplorer.

Added WinUITestSourceHost

---

.github/ISSUE_TEMPLATE.md

Adding additional contribution note, cause recently we get similar issues from community.

Adding contribution note

---

src/Adapter/MSTest.CoreAdapter/Helpers/DataSerializationHelper.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/DataSerializationHelperTests.cs
test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj

Changed the DateTime formatter for the DataSerializer
Added unit tests

Fix DateTime looses significant digits in DynamicData (#875)

---

eng/Versions.props
src/TestFramework/Extension.WinUI/Extension.WinUI.csproj

Updated to WindowsAppSDK 1.0.0-preview1

---

scripts/common.lib.ps1

Give the actual reason for failure when VS is not found, rather than failing to resolve null path.

Update error when VS is not found, and update VS version

---

src/Package/MSTest.TestAdapter.nuspec
src/Package/MSTest.TestAdapter.symbols.nuspec
src/Package/MSTest.TestFramework.nuspec
src/Package/MSTest.TestFramework.symbols.nuspec

Update description of the Nuget packages

---

scripts/write-release-notes.ps1

We are now discarding PRs like below when generating change log.
- [main] Update dependencies from ...
- Update dependencies from ... build XXXXXXXX-XX
- Localized file check-in by OneLocBuild Task
- LEGO: Pull request from lego/... to ...

Discard auto PRs in write-release-notes.ps1

---

src/TestFramework/MSTest.Core/Exceptions/AssertFailedException.cs
src/TestFramework/MSTest.Core/Exceptions/AssertInconclusiveException.cs
src/TestFramework/MSTest.Core/Exceptions/InternalTestFailureException.cs
src/TestFramework/MSTest.Core/Exceptions/UnitTestAssertException.cs

Mark exceptions with SerializableAttribute for all supported TFMs where the attribute is available.
Fixes #113

Mark exceptions with SerializableAttribute

---

eng/Version.Details.xml
eng/Versions.props
eng/common/cross/arm/sources.list.focal
eng/common/cross/arm/sources.list.jammy
eng/common/cross/arm64/sources.list.focal
eng/common/cross/arm64/sources.list.jammy
eng/common/cross/build-rootfs.sh
eng/common/cross/x86/sources.list.focal
eng/common/cross/x86/sources.list.jammy
global.json
scripts/Install-WindowsSDK.ps1
scripts/PortableToFullPdb.ps1
src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
src/Adapter/PlatformServices.Interface/PlatformServices.Interface.csproj
src/Adapter/PlatformServices.NetCore/PlatformServices.NetCore.csproj
src/Adapter/PlatformServices.Portable/PlatformServices.Portable.csproj
src/Adapter/PlatformServices.Shared/netstandard1.3/Services/ns13TestDeployment.cs
src/Adapter/PlatformServices.Universal/PlatformServices.Universal.csproj
src/Package/MSTest.TestAdapter.nuspec
src/Package/MSTest.TestAdapter.symbols.nuspec
src/Package/MSTest.TestFramework.nuspec
src/Package/MSTest.TestFramework.symbols.nuspec
src/Package/MSTest.nuspec
src/TestFramework/Extension.Core/Extension.Core.csproj
src/TestFramework/Extension.UWP/Extension.UWP.csproj
src/TestFramework/MSTest.Core/MSTest.Core.csproj
test/E2ETests/Automation.CLI/Automation.CLI.csproj
test/E2ETests/Automation.CLI/CLITestBase.common.cs
test/UnitTests/MSTest.CoreAdapter.TestUtilities/MSTest.CoreAdapter.TestUtilities.csproj
test/UnitTests/PlatformServices.Universal.Unit.Tests/PlatformServices.Universal.Unit.Tests.csproj

Target netstandard2.0 as minimal netstandard

---

src/TestFramework/MSTest.Core/Assertions/Assert.cs
test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs

Fix: https://github.com/microsoft/testfx/issues/1033

Fixed the case ignoring in AreEqual() with culture parameter

---

scripts/Build.ps1
scripts/write-release-notes.ps1

Relates to https://github.com/microsoft/vstest/issues/4018

Added version parameter to build script

---

Localize/lcl/cs/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/de/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/es/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/fr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/it/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ja/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ko/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pl/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pt-BR/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ru/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/tr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hans/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hant/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20220922180806580 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20220922180806580 to main

---

Localize/lcl/cs/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/de/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/es/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/fr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/it/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ja/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ko/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pl/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pt-BR/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ru/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/tr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hans/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hant/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20220924094927958 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20220924094927958 to main

---

src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj
src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj

Revert hack changes introduced in #1311

Revert temporary hack related to .net 6.0.10

---

test/E2ETests/DiscoveryAndExecutionTests/Parameterized tests/DynamicDataTests.cs
test/E2ETests/Smoke.E2E.Tests/Parameterized tests/DynamicDataTests.cs
test/E2ETests/TestAssets/DynamicDataTestProject/DynamicDataTestProject.csproj
test/E2ETests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs

Add test case for StackOverflow issue

---

Localize/lcl/cs/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/de/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/es/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/fr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/it/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ja/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ko/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pl/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pt-BR/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ru/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/tr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hans/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hant/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221030091801488 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221030091801488 to main

---

Localize/lcl/cs/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/de/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/es/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/fr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/it/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ja/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ko/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pl/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pt-BR/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ru/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/tr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hans/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hant/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221029092611434 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221029092611434 to main

---

Localize/lcl/cs/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/de/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/es/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/fr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/it/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ja/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ko/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pl/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/pt-BR/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/ru/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/tr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hans/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hant/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221101094922489 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221101094922489 to main

---

scripts/write-release-notes.ps1

Parity with improvements done on Test Platform repo
cc @MarcoRossignoli @cvpoienaru

Improve release notes generator

---

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt

Fix ThrowsException methods return nullability

---

Localize/lcl/cs/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/de/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/es/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/fr/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/it/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ja/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ko/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pl/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/pt-BR/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/ru/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/tr/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hans/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hant/src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221116101612171 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221116101612171 to main

---

Localize/lcl/fr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/fr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/tr/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/tr/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl
Localize/lcl/zh-Hant/src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.xlf.lcl
Localize/lcl/zh-Hant/src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.xlf.lcl

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221117105220572 to main with localized lcls

LEGO: Pull request from lego/hb_63a2d317-b544-477f-9d48-4250bdd255f0_20221117105220572 to main

---

src/TestFramework/TestFramework.Extensions/Attributes/DeploymentItemAttribute.cs

DeploymentItemAttribute only works for a test class with test method

---

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs

Assert.ThrowsException Func argument should allow returning null

---

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
src/Adapter/MSTest.TestAdapter/Helpers/EnvironmentWrapper.cs
src/Adapter/MSTest.TestAdapter/Helpers/IEnvironment.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestResult.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestResultTest.cs
test/UnitTests/MSTestAdapter.UnitTests/ObjectModel/UnitTestResultTests.cs

Add computer name on the test result

---

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs

Assert.AreEqual/AreNotEqual overloads with IEquatable

---

eng/Versions.props

Bump version to 3.0.1

---

src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
src/TestFramework/TestFramework/Assertions/Assert.IsNull.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsNull.cs

Add NotNullAttribute postcondition to Assert APIs

---

src/TestFramework/TestFramework.Extensions/PrivateObject.cs
src/TestFramework/TestFramework.Extensions/Properties/AssemblyInfo.cs

Revert Framework.Extension project to be CLSCompliant

---

src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/net462/PublicAPI.Shipped.txt
src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/net6.0/PublicAPI.Shipped.txt
src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs
src/TestFramework/TestFramework.Extensions/TestContext.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestDeploymentTests.cs

Deprecate TestContext properties kept for compatibility

---

src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/net462/PublicAPI.Shipped.txt
src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
src/TestFramework/TestFramework.Extensions/PublicAPI/net462/PublicAPI.Shipped.txt
src/TestFramework/TestFramework.Extensions/TestContext.cs

Remove deprecated BeginTimer and EndTimer methods

---

test/E2ETests/Smoke.E2E.Tests/SuiteLifeCycleTests.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfAssemblyAndBeforeEachDerivedClass.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfAssemblyAndNone.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfClassAndBeforeEachDerivedClass.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfClassAndNone.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfAssemblyAndBeforeEachDerivedClass.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfAssemblyAndNone.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfClassAndBeforeEachDerivedClass.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfClassAndNone.cs

https://github.com/microsoft/testfx/issues/1093

Add Integration tests for cleanup inheritance behaviors with different scenarios 

---

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
src/TestFramework/TestFramework/Assertions/Assert.AreSame.cs
src/TestFramework/TestFramework/Assertions/Assert.Fail.cs
src/TestFramework/TestFramework/Assertions/Assert.Inconclusive.cs
src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
src/TestFramework/TestFramework/Assertions/Assert.IsNull.cs
src/TestFramework/TestFramework/Assertions/Assert.IsTrue.cs
src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
src/TestFramework/TestFramework/Assertions/Assert.cs
src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
src/TestFramework/TestFramework/Assertions/StringAssert.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/StringAssertTests.cs

Cherry-pick commit from `rel/3.0.1`

Allow most APIs to accept nullable values or arguments (#1467)

---

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs
test/E2ETests/Smoke.E2E.Tests/SuiteLifeCycleTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs

Fix class/assembly cleanups log collect and attachment (#1470)

---

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs
test/E2ETests/Smoke.E2E.Tests/SuiteLifeCycleTests.cs
test/E2ETests/TestAssets/SuiteLifeCycleTestProject/LifecycleInheritance.cs

Fix cleanup inheritance calls

---

test/Utilities/TestFramework.ForTestingMSTest/AdapterToTestPlatform.cs

@SimonCropp this will help your PR #1527

Discover and run Task test methods

---

Directory.Build.props
src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj
src/TestFramework/TestFramework/TestFramework.csproj

This got broken when finalizing the migration to arcade.

Fix generation of documentation files

---

docs/delta-with-MSTestV1.md

fix: https://github.com/microsoft/testfx/issues/1321

Document LegacySettings- support as discontinued delta from MSTestV1

---

docs/README.md

fix: https://github.com/microsoft/testfx/issues/1323

Document data source configuration

---

Directory.Build.props
eng/Analyzers.props

Use trick found on some other repo to have better separation of concerns for analyzer properties.

Extract analyzers to their own props file

---

Directory.Build.props
azure-pipelines.yml
samples/FxExtensibility/FxExtensibility.csproj
src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj
src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.nuspec
src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj
src/TestFramework/TestFramework/TestFramework.csproj
test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests.csproj
test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/PlatformServices.Desktop.IntegrationTests.csproj
test/IntegrationTests/TestAssets/SampleFrameworkExtensions/SampleFrameworkExtensions.csproj
test/IntegrationTests/TestAssets/TestProject/TestProjectForDiscovery.csproj
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj
test/UnitTests/MSTestAdapter.UnitTests/MSTestAdapter.UnitTests.csproj
test/UnitTests/TestFramework.UnitTests/TestFramework.UnitTests.csproj

Simplify projects, nuspecs and symbol creation

Use embedded symbols (#1601

---

azure-pipelines.yml
eng/AfterSolutionBuild.targets

Call verify-nupkgs.ps1 at the end of the pack step

---

docs/Changelog.md

fix: https://github.com/microsoft/testfx/issues/1634

Update release note for v3.0.0 preview to refer to vs grouping updates

---

src/Adapter/MSTestAdapter.PlatformServices/Services/ThreadOperations.cs

Through the process of simplification and unification of behaviors for the different target frameworks, we dropped usage of a thread to use only Task.Run. This has the unexpected side effect of causing .NET framework tests to no longer be run in STA thread.
We are reverting the change for now and are tracking the implementation of a better solution with https://github.com/microsoft/testfx/issues/1674
Fixes #1616

Revert change for timeout test execution

---

src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtility.cs

Fix out of range exception in deployment tool

---

src/Adapter/MSTest.TestAdapter/Execution/ExceptionHelper.cs
src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
src/Adapter/MSTest.TestAdapter/Extensions/ExceptionExtensions.cs
src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Extensions/ExceptionExtensionsTests.cs

Prevent swallowing inner exception in async error

---

eng/Versions.props
src/Adapter/MSTest.TestAdapter/PublicAPI/PublicAPI.Shipped.txt
src/Adapter/MSTest.TestAdapter/PublicAPI/PublicAPI.Unshipped.txt

Bump version to 3.2.0
Mark all unshipped APIs as shipped

Prepare new release

---

eng/Version.Details.xml
eng/Versions.props
global.json

Bump and cleanup global versions

---

NuGet.config

Clean nuget.config

---

src/Platform/Microsoft.Testing.Platform/Messages/TestNodeUid.cs
src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt

Fixes issue with filtering cc: @drognanar

Add `==` and `!=` operator to `TestNodeUid`

---

.github/workflows/enable-auto-merge.yml

Allow to auto-merge dotnet bot PRs for dependencies bump

Update auto-merge condition

---

eng/Version.Details.xml
eng/Versions.props
src/Package/MSTest.Sdk/MSTest.Sdk.csproj

@Evangelink updating darc manually I need to understand because is not working.

Manually update darc

---

test/IntegrationTests/MSTest.IntegrationTests/ClsTests.cs
test/IntegrationTests/TestAssets/ClsTestProject/MyTests.cs

Improve CLS test

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs

Took the same number of chars of msbuild banner.

Refactor banner version

---

TestFx.sln
samples/Playground/Playground.csproj
samples/Playground/Program.cs
samples/Playground/Tests.cs

Add Playground project to simplify the development

---

azure-pipelines.yml

Use Ubuntu 2004 instead of 1804

---

samples/runner_vs_vstest/README.md

Took the best of 3 run per set in release

Add comparison stats

---

samples/runner_vs_vstest/README.md

Performance measurements

---

src/Platform/Microsoft.Testing.Platform/BannedSymbols.txt
src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/Parser.cs
src/Platform/Microsoft.Testing.Platform/Helpers/ArgumentGuard.cs
src/Platform/Microsoft.Testing.Platform/Helpers/RoslynString.cs
src/Platform/Microsoft.Testing.Platform/Helpers/TaskExtensions.cs
src/Platform/Microsoft.Testing.Platform/Helpers/TimeSpanParser.cs
src/Platform/Microsoft.Testing.Platform/Logging/TypeNameHelper.cs
src/Platform/Microsoft.Testing.Platform/Messages/TestNodeUid.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/ServerModeManager.cs
src/Platform/Microsoft.Testing.Platform/Services/CurrentTestApplicationModuleInfo.cs
src/Platform/Microsoft.Testing.Platform/Services/TestApplicationResult.cs
src/Platform/Microsoft.Testing.Platform/Telemetry/TelemetryManager.cs

Rename TAString into RoslynString

---

src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj

Update name of extensions on InternalsVisibleTo

---

src/Adapter/Build/Common/MSTest.TestAdapter.props
src/Adapter/MSTest.TestAdapter/PublicAPI/PublicAPI.Unshipped.txt
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBridgedTestFramework.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestExtension.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestingPlatformBuilderHook.cs

Fix mstest runner namespace

---

src/Adapter/MSTestAdapter.PlatformServices/Services/ThreadOperations.cs

[bug] Do not wait timeout duration in case of user cancellation

---

src/Platform/Microsoft.Testing.Platform/CommandLine/PlaltformCommandLineProvider.cs

Cache platform command line options

---

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/DiagnosticTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TelemetryTests.cs

closes https://github.com/microsoft/testfx/issues/2134

Set default verbosity to `Trace`

---

src/Platform/Microsoft.Testing.Platform/Messages/TestNodeUid.cs
src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt
src/Platform/Microsoft.Testing.Platform/TestHost/SessionUid.cs

contributes to https://github.com/microsoft/testfx/issues/2133

Improve logging

---

samples/mstest-runner/RunInDocker/MyServer.Tests/MyServer.Tests.csproj
samples/mstest-runner/Simple1/Simple1.csproj

Fix code samples

---

samples/mstest-runner/CustomReportExtension/CustomReportExtension/CustomReportExtension.csproj

Fixes required sdk for the sample, see https://github.com/microsoft/testfx/pull/2246#issuecomment-1924696621

Sample project should be using net8.0

---

samples/runner_vs_vstest/measure.ps1

Wrote it to save my own sanity when comparing the runner.

Add measure script

---

eng/Version.Details.xml
eng/Versions.props

Bump version of coverage and platform

---

src/Platform/Microsoft.Testing.Platform/Logging/ILogger.cs
src/Platform/Microsoft.Testing.Platform/Logging/ILoggerFactory.cs
src/Platform/Microsoft.Testing.Platform/Logging/LoggerFactoryExtensions.cs

Document logging public APIs

---

src/Platform/Microsoft.Testing.Platform/Capabilities/TestFrameworkAdapter/ITestFrameworkCapabilities.cs
src/Platform/Microsoft.Testing.Platform/Capabilities/TestFrameworkAdapter/ITestFrameworkCapability.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/CloseTestSessionContext.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/CloseTestSessionResult.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/CreateTestSessionContext.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/CreateTestSessionResult.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/ExecuteRequestContext.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/ITestFramework.cs

Document test framework public APIs

---

src/Platform/Microsoft.Testing.Platform/Messages/DataWithSessionUid.cs
src/Platform/Microsoft.Testing.Platform/Messages/FileArtifacts.cs
src/Platform/Microsoft.Testing.Platform/Messages/IData.cs
src/Platform/Microsoft.Testing.Platform/Messages/IDataConsumer.cs
src/Platform/Microsoft.Testing.Platform/Messages/IDataProducer.cs
src/Platform/Microsoft.Testing.Platform/Messages/IMessageBus.cs

Document messages public APIs

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOption.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineManager.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineOptions.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineOptionsProvider.cs

Document command line public APIs

---

src/Platform/Microsoft.Testing.Platform/Requests/DiscoverTestExecutionRequest.cs
src/Platform/Microsoft.Testing.Platform/Requests/IRequest.cs
src/Platform/Microsoft.Testing.Platform/Requests/ITestExecutionFilter.cs
src/Platform/Microsoft.Testing.Platform/Requests/RunTestExecutionRequest.cs
src/Platform/Microsoft.Testing.Platform/Requests/TestExecutionRequest.cs
src/Platform/Microsoft.Testing.Platform/Requests/TestNodeUidListFilter.cs

Document requests public APIs

---

src/Platform/Microsoft.Testing.Platform/Configurations/ConfigurationExtensions.cs
src/Platform/Microsoft.Testing.Platform/Configurations/IConfiguration.cs

Document configuration public APIs

---

src/Platform/Microsoft.Testing.Platform/TestHost/ClientInfo.cs
src/Platform/Microsoft.Testing.Platform/TestHost/ITestApplicationLifecycleCallbacks.cs
src/Platform/Microsoft.Testing.Platform/TestHost/ITestHostExtension.cs
src/Platform/Microsoft.Testing.Platform/TestHost/ITestHostManager.cs
src/Platform/Microsoft.Testing.Platform/TestHost/ITestSessionLifetimeHandler.cs
src/Platform/Microsoft.Testing.Platform/TestHost/SessionUid.cs
src/Platform/Microsoft.Testing.Platform/TestHost/TestSessionContext.cs
src/Platform/Microsoft.Testing.Platform/TestHost/WellKnownClients.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/EnvironmentVariable.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/IEnvironmentVariables.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/IReadOnlyEnvironmentVariables.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/ITestHostControllerManager.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/ITestHostControllersExtension.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/ITestHostEnvironmentVariableProvider.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/ITestHostProcessInformation.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/ITestHostProcessLifetimeHandler.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/OwnedEnvironmentVariable.cs

Document testhost related public APIs

---

src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf

close https://github.com/microsoft/testfx/issues/2279

Fix resource message

---

src/Platform/Microsoft.Testing.Platform/BannedSymbols.txt
src/Platform/Microsoft.Testing.Platform/Capabilities/ICapabilities.cs
src/Platform/Microsoft.Testing.Platform/Capabilities/ICapability.cs
src/Platform/Microsoft.Testing.Platform/Extensions/CompositeExtensionsFactory.cs
src/Platform/Microsoft.Testing.Platform/Extensions/IAsyncCleanableExtension.cs
src/Platform/Microsoft.Testing.Platform/Extensions/IAsyncInitializableExtension.cs
src/Platform/Microsoft.Testing.Platform/Extensions/ValidationResult.cs
src/Platform/Microsoft.Testing.Platform/Services/ServiceProviderExtensions.cs

Document extensions/services public APIs

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/ArgumentArityTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs

contributes to https://github.com/microsoft/testfx/issues/2308
@Evangelink  I'll cherry pick this one it's a ux bug.

Fix command line banner output

---

src/Package/MSTest.Sdk/MSTest.Sdk.csproj
src/Package/MSTest.Sdk/Sdk/Sdk.props.template
src/Package/MSTest.Sdk/Sdk/Sdk.targets

Complete the sdk with extensions

---

src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs

Reserve analyzer IDs for upcoming analyzers in order to avoid clashes

Reserve analyzer IDs

---

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs
src/Platform/Microsoft.Testing.Platform/Capabilities/ICapabilities.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ArgumentArity.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/FormattedTextOutputDeviceData.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/IColor.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/IOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/IOutputDeviceData.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/IOutputDeviceDataProducer.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/SystemConsoleColor.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TextOutputDeviceData.cs
src/Platform/Microsoft.Testing.Platform/TestHost/ClientInfo.cs
src/Platform/Microsoft.Testing.Platform/TestHostControllers/EnvironmentVariable.cs

Document more public API for the platform

---

src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs

Fix resources to specify 'ValueTask' is valid

---

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs

Backport #2381 and relates to #2365

Assert.AreEqual allow IEquatable<T> for actual and expected

---

src/Analyzers/MSTest.Analyzers/AssemblyCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/AssemblyInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Helpers/IMethodSymbolExtensions.cs
src/Analyzers/MSTest.Analyzers/TestCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/TestInitializeShouldBeValidAnalyzer.cs

Add helper for lifecycle method visibility

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/Configurations/AggregatedConfiguration.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/ArgumentArityTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs

contributes to https://github.com/microsoft/testanywhere/issues/1893

Fix msbuild integration

---

src/Adapter/MSTest.TestAdapter/Discovery/TypeValidator.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeValidatorTests.cs

Improve warning message for generic non-abstract test classes

---

src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj

Add internals visible to for NativeAot prototype.

add internals visible to

---

test/Utilities/Microsoft.Testing.TestInfrastructure/TargetFrameworks.cs

Revert "Add .NET Latest data source"

---

src/Package/MSTest.Sdk/MSTest.Sdk.nuspec
src/Package/MSTest.Sdk/Sdk/Runner/Runner.targets.template
src/Package/MSTest.Sdk/Sdk/Runner/TestingPlatform.targets
src/Package/MSTest.Sdk/Sdk/Sdk.props.template

closes https://github.com/microsoft/testfx/issues/2509
closes https://github.com/microsoft/testfx/issues/2508

Apply `MSTest.Sdk` feedbacks

---

src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs

fixes https://github.com/microsoft/testanywhere/issues/1967

Fix protocol version

---

azure-pipelines-official.yml
azure-pipelines.yml

Clean conditions from public pipeline, and use outputs in official pipeline.

Clean public, and outputs in official

---

azure-pipelines-official.yml

Waits for https://dnceng.visualstudio.com/internal/_build/results?buildId=2397978&view=results to pass.

Use image instead of override

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md

Update shipped analyzers

---

eng/Versions.props

Bump MSTest to v3.4.0

---

src/Analyzers/MSTest.Analyzers/AssertionArgsShouldBePassedInCorrectOrderAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AssertionArgsShouldBePassedInCorrectOrderAnalyzerTests.cs

Fix false positive in AssertionArgsShouldBePassedInCorrectOrderAnalyzer

---

src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf

Improve error message when dynamic data source layout is invalid

---

src/Package/MSTest.Sdk/Sdk/Runner/Common.targets

Add global using feature in MSTest.Sdk

---

global.json

reduces friction for contributors

allow rollForward of sdk to latestFeature

---

src/Package/MSTest.Sdk/Sdk/Runner/Common.targets

SDK: add playwright default using

---

src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets

SDK: add global usings to VSTest targets

---

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets
src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets

I cannot find any documentation about this and I don't see any project using this pattern.
Follow-up from #2727

Remove SDK part of the PackageReference

---

test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj

Relates to https://github.com/microsoft/testanywhere/issues/2075

TestInfrastructure should not be recognized as test project

---

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Microsoft.Testing.Platform.UnitTests.csproj
test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj

fix https://github.com/microsoft/testanywhere/issues/2075

Output exe for test projects

---

samples/DemoMSTestSdk/ProjectUsingMSTestRunner/ProjectUsingMSTestRunner.csproj
samples/DemoMSTestSdk/ProjectUsingVSTest/ProjectUsingVSTest.csproj
samples/DemoMSTestSdk/ProjectWithNativeAOT/ProjectWithNativeAOT.csproj
samples/DemoMSTestSdk/global.json

Make MSTest.Sdk samples use the global.json

---

samples/DemoMSTestSdk/Directory.Packages.props
samples/mstest-runner/Directory.Packages.props

Opt-out from CPM in samples

---

docs/Changelog.md

Add new entries to changelog

---

docs/Changelog.md

Typo in Changelog.md

---

docs/Changelog.md

One more time. I was editing it in online editor and one of the changes got reverted.

Fix PR number in Changelog.md

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt

Update public API and analyzer releases

---

eng/Versions.props

Bump version to 3.5.0

---

Directory.Packages.props

Bump infra and test third-parties versions

---

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssemblyResolverTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DynamicDataTests.cs

Fix some IDEXXX warnings

---

src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/Properties/launchSettings.json

fix: https://github.com/microsoft/testfx/issues/2822

Include timeout duration in timeout message

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf

Localize strings to be compliant. 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2035504

Localize console service

---

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs

Cleanup variable logging in TestApplication.CreateBuilderAsync

---

docs/Changelog.md

Fix release years in changelog

---

Directory.Packages.props

Use latest released version for Playwright and Aspire

---

src/Adapter/MSTestAdapter.PlatformServices/Services/TestSourceHost.cs

Manually tested and validated. Sadly, I cannot write a test as the issue is only happening in VS.
Fixes #3019

Fix assembly resolution with DeploymentItem

---

src/Adapter/MSTestAdapter.PlatformServices/Services/TestSourceHost.cs

Fix assembly resolution with DeploymentItem (#3034)

---

docs/testingplatform/Index.md
docs/testingplatform/capabilities.md
docs/testingplatform/ibannermessageownercapability.md
docs/testingplatform/iplatforminformation.md
docs/testingplatform/itestframeworkcapability.md

Follow-up of #2919 
cc @MarcoRossignoli

Document IBannerMessageOwnerCapability

---

eng/Version.Details.xml
eng/Versions.props

Revert version of Code Coverage to 17.10.4

---

src/Platform/Microsoft.Testing.Platform/Helpers/TestApplicationBuilderExtensions.cs
src/Platform/Microsoft.Testing.Platform/Requests/TreeNodeFilter/TreeNodeFilter.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs

Make tree node filter public and experimental

---

samples/public/DemoMSTestSdk/ProjectUsingMSTestRunner/ProjectUsingMSTestRunner.csproj
samples/public/DemoMSTestSdk/ProjectUsingMSTestRunner/Usings.cs
samples/public/DemoMSTestSdk/ProjectUsingPlaywright/ProjectUsingPlaywright.csproj
samples/public/DemoMSTestSdk/ProjectUsingVSTest/ProjectUsingVSTest.csproj
samples/public/DemoMSTestSdk/ProjectUsingVSTest/Usings.cs
samples/public/DemoMSTestSdk/ProjectWithNativeAOT/ProjectWithNativeAOT.csproj
samples/public/DemoMSTestSdk/ProjectWithNativeAOT/Usings.cs

Fix https://github.com/microsoft/testfx/issues/3069

Replace Usings.cs with <Using> in SDK samples

---

src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/Json/Json.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/PerRequestServerDataConsumerService.cs
test/Performance/MSTest.Performance.Runner/PipelinesRunner.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestAssemblyInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Helpers/SystemAsyncMonitorTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/AsynchronousMessageBusTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/ServerTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TestsRunWatchDog.cs
test/Utilities/TestFramework.ForTestingMSTest/AdapterToTestPlatform.cs

Fix some typos and use method group

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs

fix: https://github.com/microsoft/testfx/issues/3110

Info display for arity one or more is broken

---

test/UnitTests/MSTestAdapter.UnitTests/Helpers/ReflectHelperTests.cs

Check that Reflect Helper caches inherited and non-inherited attributes separately

---

src/Platform/Microsoft.Testing.Platform/Helpers/System/IProcess.cs
src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs

Make IProcess disposable

---

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceAssert.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Properties/launchSettings.json

Add acceptance tests for info with all extensions

---

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs

Pass the TestContext CTS to the method fixtures

---

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs

Helped me find the race condition issue, it could maybe help with the randomic NRE (cc @fhnaseer )

Print exceptions occuring during Task.WaitAll

---

src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ValueTaskTests.cs

Ensure ValueTask test methods are awaited

---

docs/testingplatform/codesample.md

To make it more obvious where the solution is.

Link to solution in samples doc

---

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/IgnoreTests.cs

ClassCleanup are not executed if testclass is ignored

---

Directory.Packages.props
eng/Version.Details.xml
eng/Versions.props
samples/Playground/Playground.csproj
src/Package/MSTest.Sdk/MSTest.Sdk.csproj
src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
src/Package/MSTest.Sdk/Sdk/Sdk.props.template
test/Directory.Build.targets
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/NativeAotTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/DiagnosticTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ExecutionTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceTestBase.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuild.KnownExtensionRegistration.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.ConfigurationFile.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Solution.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs

Follow-up of open-sourcing the extensions to the testing platform.

Cleanup post open-sourcing of platform extensions

---

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceTestBase.cs

Refactor logic for internal extensions

---

src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/Json/Json.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/RpcMessages.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/SerializerUtilities.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/ServerTests.cs

closes https://github.com/microsoft/testfx/issues/3211

Return the pid during the handshake inside the InitializeResponseArgs

---

src/Analyzers/MSTest.Analyzers/AssemblyCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/AssemblyInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Helpers/FixtureUtils.cs
src/Analyzers/MSTest.Analyzers/TestCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/TestInitializeShouldBeValidAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AssemblyCleanupShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AssemblyInitializeShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/ClassCleanupShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/ClassInitializeShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestCleanupShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestInitializeShouldBeValidAnalyzerTests.cs

Fixes #3244, fixes #3245 and fixes #3246

Update fixture analyzers to report on missing [TestClass]

---

eng/Versions.props

Bump MSTest to 3.6 and Platform to 1.4

---

src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs

Fix timeout message to reflect that 0 is not allowed

---

src/Analyzers/MSTest.Analyzers/TestCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/TestInitializeShouldBeValidAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestCleanupShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestInitializeShouldBeValidAnalyzerTests.cs

Fix TestInitialize and TestCleanup analyzers to allow generic class

---

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs

Avoid creation of tasks

---

src/Platform/Microsoft.Testing.Extensions.HangDump/Serializers/GetInProgressTestsResponse.cs
src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxProcessLifetimeHandler.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
src/Platform/Microsoft.Testing.Platform/Logging/LoggerFactory.cs

effectively some better memory usage

initialise list size where count is known

---

src/Platform/Microsoft.Testing.Platform/Messages/PropertyBag.cs

also removes a duplicate enumeration

remove redundant any in PropertyBag

---

src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs

Last round of improvement around threading linked to support of STA thread

For fixtures in STA thread, use TCS instead of Task.Run

---

src/Analyzers/MSTest.Analyzers/PublicMethodShouldBeTestMethodAnalyzer.cs
src/Platform/Microsoft.Testing.Platform/TestHostOrcherstrator/TestHostOrchestratorManager.cs
test/UnitTests/MSTest.Analyzers.UnitTests/PublicMethodShouldBeTestMethodAnalyzerTests.cs

fix: https://github.com/microsoft/testfx/issues/3291

Fix MSTEST0029 false positive on TestInitialize/TestCleanup

---

src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
test/IntegrationTests/TestAssets/DataRowTestProject/DataRowTests_Regular.cs

Fix passing null to DataRow when signature is object[]

---

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TimeoutInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethodOptions.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs

Fix cooperative cancellation for TestInit/TestCleanup

---

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs

Followup of https://github.com/microsoft/testfx/pull/3317
cc: @mariam-abdulla

Add  the `DotnetTestDataConsumer` for the test host controller

---

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/IgnoreTests.cs

Fix: Skip AssemblyInitialize/Cleanup when all tests are skipped

---

src/Analyzers/MSTest.Analyzers/ClassCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/ClassCleanupShouldBeValidAnalyzerTests.cs

fix: https://github.com/microsoft/testfx/issues/3224

MSTEST0011: report when class is abstract and inheritance is not specified

---

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
src/TestFramework/TestFramework/Assertions/Assert.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs

Fix Assert.VerifyThrows to use standard message pattern

---

src/Analyzers/MSTest.Analyzers/ClassInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/ClassInitializeShouldBeValidAnalyzerTests.cs

fix: https://github.com/microsoft/testfx/issues/3348

MSTEST0010: report if InheritanceBehavior.BeforeEachDerivedClass is set on a sealed class

---

Directory.Packages.props
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs
src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt
src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/UseDeploymentItemWithTestMethodOrTestClassAnalyzer.cs
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/Properties/launchSettings.json
test/UnitTests/MSTest.Analyzers.UnitTests/UseDeploymentItemWithTestMethodOrTestClassAnalyzerTests.cs

fix: https://github.com/microsoft/testfx/issues/3192

Add analyzer for DeploymentItem

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs

I think the suppression message is wrong

remove CommandLineHandler _process

---

src/Adapter/MSTestAdapter.PlatformServices/Services/TestDataSource.cs

remove redundant catch around GetConnectionProperties

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs

i think the suppression message is wrong

remove CommandLineHandler _environment

---

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

remove GetNonDerivedAttributes

---

docs/mstest-runner-protocol/001-protocol-intro.md

Add support for a callback provider that allows the server to connect multiple RPC servers to process the test run.
The goal of this is to better handle the `client->server->workerNode` configurations and allows the workerNode to send callbacks to the client directly. For instance, the main server might decide to load balance a run across multiple workerNodes with retries or create a workerNode under different environments like docker/WSL. With the `testing.callbackProvider` capability, the process inside of WSL can directly communicate back with the client and does not need to route all of the callbacks back through the main test runner process.
All of the `client->server` requests are still sent to the server node and not to the workerNodes, as the client has no knowledge of how the …

Add information about data collector nodes to the spec

---

src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx
src/Analyzers/MSTest.Analyzers.CodeFixes/PublicTypeShouldBeTestClassFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf

related: https://github.com/microsoft/testfx/pull/3482

fix MSTEST0004: Add code fix

---

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs

fix: https://github.com/microsoft/testfx/issues/3471

Warn on invalid DisableParallelization configuration entry

---

test/Utilities/TestFramework.ForTestingMSTest/AdapterToTestPlatform.cs

cc @MarcoRossignoli and @nohwnd

Reduce verbosity of internal test framework

---

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs

fix: https://github.com/microsoft/testfx/issues/3560

Fix `DisableParallelization` shows invalid value warning always

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FrameworkHandlerAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsPatcher.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/TestCaseDiscoverySinkAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestDiscoverTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestRunTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/VSTestBridgedTestFrameworkBase.cs
src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs
src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs
src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt
src/Platform/Microsoft.Testing.Platform/Services/ClientInfoService.cs
src/Platform/Microsoft.Testing.Platform/Services/IClientInfo.cs
src/Platform/Microsoft.Testing.Platform/Services/ServiceProviderExtensions.cs
src/Platform/Microsoft.Testing.Platform/TestHost/TestSessionContext.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/RunSettingsPatcherTests.cs

Closes https://github.com/microsoft/testfx/issues/3355

Refactor `ClientInfo`

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/TargetFrameworkParser.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TargetFrameworkParserTests.cs

Fix shortening TFM and architecture

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/MSTest.Acceptance.IntegrationTests.csproj
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.launcher.config.json
test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj
test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.launcher.config.json
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/Microsoft.Testing.Extensions.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests.launcher.config.json
test/UnitTests/Microsoft.Testing.Platform.MSBuild.UnitTests/Microsoft.Testing.Platform.MSBuild.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Microsoft.Testing.Platform.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Microsoft.Testing.Platform.UnitTests.launcher.config.json

At the moment VS supports only `.exe`
cc: @drognanar

Support VS TA testing

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

Fix stack frame formatting

---

src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets
src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets

MSTest.Sdk warn or error on invalid or untested properties

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminalTestProgressFrame.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs

Change skipped indicator to downward arrow

---

Directory.Packages.props

Update TestPlatform to 17.11.0

---

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/AbortionTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CrashDumpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CrashPlusHangDumpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuild.KnownExtensionRegistration.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/UnhandledExceptionPolicyTests.cs

Remove retries

---

src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/StreamMessageHandler.cs

fixes https://github.com/microsoft/testfx/issues/3622

Fix `Content-Length`

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsPatcher.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestDiscoverTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestRunTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/ExtensionResources.Designer.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/ExtensionResources.resx
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.cs.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.de.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.es.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.fr.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.it.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ja.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ko.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.pl.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ru.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.tr.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.zh-Hant.xlf
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RunsettingsTests.cs

Warn about unsupported runsettings entries

---

docs/testingplatform/Source/TestingPlatformExplorer/Program.cs
docs/testingplatform/Source/TestingPlatformExplorer/Properties/launchSettings.json
docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.cs
docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFrameworkCapabilities.cs
docs/testingplatform/Source/TestingPlatformExplorer/TestingPlatformExplorer.csproj

Support Trx for the documented sample 

---

src/Platform/Microsoft.Testing.Platform/Capabilities/TestFramework/TestFrameworkCapabilitiesExtensions.cs
src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt

It's useful for extensions and testing framework too.

Expose `TestFrameworkCapabilitiesExtensions` in experimental mode

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsProxy.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/Hosts/ToolsTestHost.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/OutputDeviceManager.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs

closes https://github.com/microsoft/testfx/issues/3552

Allow `ICommandLineOptions` inside the `IPlatformOutputDevice` extension

---

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/Logging/FileLoggerInformation.cs
src/Platform/Microsoft.Testing.Platform/Logging/IFIleLoggerInformation.cs
src/Platform/Microsoft.Testing.Platform/Logging/LoggerFactoryProxy.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/OutputDeviceManager.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf
src/Platform/Microsoft.Testing.Platform/Services/ServiceProviderExtensions.cs

closes https://github.com/microsoft/testfx/issues/3676

Expose file logging info using a service

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FastFilter.cs

Remove redundant cast

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/NativeAotTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

Retry globally the flaky native aot tests

---

Directory.Packages.props
src/Platform/Microsoft.Testing.Platform.MSBuild/Microsoft.Testing.Platform.MSBuild.csproj
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/DotnetMuxerLocator.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs

closes https://github.com/microsoft/testfx/issues/3689

Manual resolution of the muxer for `dotnet test` MSBuild extension

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Properties/launchSettings.json

fixes https://github.com/microsoft/testfx/issues/3705

Fix the usage of the DOTNET_HOST_PATH

---

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets

Ref https://github.com/microsoft/testfx/issues/3478#issuecomment-2313889212

Add warning comment on MSBuild task name

---

src/Analyzers/MSTest.Analyzers/DoNotUseShadowingAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/DoNotUseShadowingAnalyzerTests.cs

Fix MSTEST0036 to report only on ordinary methods

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs

Fix Console is already in batching mode when writing to terminal

---

azure-pipelines-official.yml
azure-pipelines.yml

Cleanup pipelines trigger

---

eng/Versions.props

Bump main to next versions

---

src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt
src/Platform/Microsoft.Testing.Platform/Requests/IExecuteRequestCompletionNotifier.cs
src/Platform/Microsoft.Testing.Platform/Requests/IRequestCompleteNotifier.cs
src/Platform/Microsoft.Testing.Platform/Requests/SemaphoreSlimRequestCompleteNotifier.cs
src/Platform/Microsoft.Testing.Platform/Requests/TestHostTestFrameworkInvoker.cs
src/Platform/Microsoft.Testing.Platform/TestFramework/ExecuteRequestContext.cs

Closes https://github.com/microsoft/testfx/issues/3716

Expose `ExecuteRequestContext` ctor for testability

---

src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
src/Analyzers/MSTest.Analyzers/UseClassCleanupBehaviorEndOfClassAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseClassCleanupBehaviorEndOfClassAnalyzerTests.cs

fix: https://github.com/microsoft/testfx/issues/3662

Fix MSTEST0034 doesn't handle ClassCleanupExecutionAttribute

---

docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.Attributes.cs
docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.cs
docs/testingplatform/Source/TestingPlatformExplorer/UnitTests.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs

Fix missing skip reason

---

Directory.Packages.props

Bump all deps

---

src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf

MSTEST0016: Fix typo in rule message and description

---

eng/verify-nupkgs.ps1
src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec

Fix resources included in MSTest.TestAdapter nupkg

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

[chore] re-enable test

---

src/Adapter/MSTest.TestAdapter/Execution/TestRunCancellationToken.cs

Fix concurrency issue with registering callback on TestRunCancellationToken

---

eng/Version.Details.xml
eng/Versions.props

Extract CC and TA bumps from #3944

Bump code coverage and TA deps

---

src/Analyzers/MSTest.Analyzers/TypeContainingTestMethodShouldBeATestClassAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TypeContainingTestMethodShouldBeATestClassAnalyzer.cs

Fix MSTEST0030 to correctly handle all methods

---

src/Analyzers/MSTest.Analyzers/TypeContainingTestMethodShouldBeATestClassAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TypeContainingTestMethodShouldBeATestClassAnalyzer.cs

[rel/3.6] Fix MSTEST0030 to correctly handle all methods

---

src/Analyzers/MSTest.Analyzers/DynamicDataShouldBeValidAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/DynamicDataShouldBeValidAnalyzerTests.cs

Fix MSTEST0018 FP with IEnumerable<SomeType[]>

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/IHotReloadPlatformOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporterOptions.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

Forward merging #3983 to main.

Fix live output with HotReload (#3983)

---

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpActivityIndicator.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpOutputTests.cs

Forward merge https://github.com/microsoft/testfx/pull/3992

Fix hangdump not showing tests in progress (#3992)

---

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpTests.cs

Fix hangdump space in dump path (#3994)

---

samples/public/Directory.Build.props

Bump versions used for samples

---

src/Adapter/MSTest.TestAdapter/Helpers/AttributeComparer.cs

Fix IsNonDerived implementation for attribute comparison

---

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs
src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt
src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt
src/TestFramework/TestFramework.Extensions/TestContext.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs

Add TestDisplayName property to the TestContext

---

src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs
src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt

Add key only overload to TestMetadataProperty

---

samples/public/mstest-runner/MSTestRunnerWinUI/UnitTest/App.xaml.cs
samples/public/mstest-runner/MSTestRunnerWinUI/UnitTest/UnitTest.csproj

Improve WinUI MSTest runner sample

---

azure-pipelines.yml
eng/install-access-database-engine.ps1
src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DataSourceTests.cs

Fix DataSourceAttribute not being discovered with TestDataSourceDiscoveryOption.DuringDiscovery

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs

Enable UseProperAssertMethodsAnalyzer by default

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs

Fix broken acceptance tests on pipeline

---

.github/ISSUE_TEMPLATE/rfc.md

Adjust "auto label" issues from RFC template

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

Bump publish to native aot timeout step to 3min

---

Directory.Packages.props

Bump Aspire.Hosting.Testing from 8.2.1 to 8.2.2

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/MSBuildResources.resx
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.cs.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.de.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.es.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.fr.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.it.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ja.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ko.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.pl.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ru.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.tr.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.zh-Hant.xlf
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs

Improve error message for incompatible architecture

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs

Use Polyfill lock

---

src/Platform/Microsoft.Testing.Platform/Extensions/CompositeExtensionsFactory.cs
src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs

Further `System.Threading.Lock` usages

---

azure-pipelines-official.yml
azure-pipelines.yml

Follow winforms repo logic https://github.com/dotnet/winforms/blob/ebf4629befde9a9be0fc741e9748ef388de8b6de/eng/pipelines/build.yml#L137-L143

Add codecov.io to official pipeline

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf

Show the text that timed out in regex match

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs

Refactor WarnOnUnsupportedEntries

---

.config/dotnet-tools.json
Directory.Packages.props
eng/CodeCoverage.proj

Fix merging of coverage using MS CC

---

eng/Versions.props

Prepare release of MSTest 3.6.4

---

Directory.Packages.props

Bump vulnerable deps

---

src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj

Fix analyzers package to support VB.NET

---

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs

Cleanup FailedStates in TrxReportEngine

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsValidator.cs

Avoid Linq allocations from usage of Union

---

src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

Simplify Ignore handling in IsTestMethodRunnable

---

src/Adapter/MSTest.TestAdapter/Helpers/AttributeComparer.cs

Simplify AttributeComparer.IsDerived

---

src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs

[Performance] Create dictionary with the right capacity

---

test/UnitTests/MSTestAdapter.UnitTests/Helpers/DictionaryHelperTests.cs

remove redundant ascending

---

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/Services/CurrentTestApplicationModuleInfo.cs
test/IntegrationTests/MSTest.IntegrationTests/Extensions/VerifyE2E.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/DiagnosticTests.cs
test/IntegrationTests/TestAssets/DiscoverInternalsProject/UnitTest1.cs
test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
test/UnitTests/MSTestAdapter.UnitTests/DynamicDataAttributeTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Helpers/DictionaryHelperTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs

remove param values where same as default

---

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs

Avoid dictionary resizes when the size is approximately known

---

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs

Cleanup duplicate logic for timeout handling when creating assembly info

---

eng/Version.Details.xml
eng/Versions.props

Update dependencies from devdiv/DevDiv/vs-code-coverage, microsoft/testanywhere

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestNodeResultsState.cs

Fix displaying progress in non-ansi terminal

---

eng/Versions.props

Move main to MSTest 3.8 and MTP 1.6

---

azure-pipelines-official.yml
azure-pipelines.yml

Upload test results for all OSes

---

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

Improve doc comment

---

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

Fix incorrect doc comment

---

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

Remove unnecessary overloads in ReflectHelper

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md

Mark analyzers as released

---

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
src/TestFramework/TestFramework/Attributes/TestMethod/STATestClassAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/TestClassAttribute.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs

Fixes https://github.com/microsoft/testfx/issues/4278

Don't consider TestClassAttribute for inheritance when calculating assembly initialize/cleanup

---

src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.NonWindows.nuspec
src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.nuspec

Make MSTest.TestFramework depends upon MSTest.Analyzers

---

test/Utilities/Microsoft.Testing.TestInfrastructure/SlowestTestsConsumer.cs

Use test display name instead of UID for slowest tests

---

src/Analyzers/MSTest.Analyzers/PreferTestCleanupOverDisposeAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/PreferTestCleanupOverDisposeAnalyzerTests.cs

Fix false positive for PreferTestCleanupOverDispose on non-test classes

---

src/Analyzers/MSTest.Analyzers/PreferTestCleanupOverDisposeAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/PreferTestCleanupOverDisposeAnalyzerTests.cs

[Backport][3.7] Fix false positive for PreferTestCleanupOverDispose on non-test classes

---

src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf

Remove unused resources in TestAdapter

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RunsettingsTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/RetryFailedTestsTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs

Improve some flaky tests

---

test/Directory.Build.targets
test/Performance/MSTest.Performance.Runner/Program.cs
test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj
test/Utilities/Microsoft.Testing.TestInfrastructure/Constants.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj

Simplify test dependencies

---

src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/DiagnosticExtensions.cs

Fix DiagnosticExtensions class name

---

src/Adapter/MSTest.TestAdapter/DynamicDataOperations.cs
src/Analyzers/MSTest.Analyzers/DynamicDataShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DynamicDataTests.cs
test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DynamicDataTests.cs
test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/DynamicDataShouldBeValidAnalyzerTests.cs

Allow any IEnumerable as return type to DynamicData source member

---

test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DynamicDataTests.cs

Fix DynamicDataTests

---

test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DynamicDataTests.cs

Fix one more dynamic data test

---

src/Adapter/MSTest.TestAdapter/build/uwp/MSTest.TestAdapter.targets

Fix MSTestV2Files msbuild items

---

src/Adapter/MSTest.TestAdapter/Extensions/ExceptionExtensions.cs

also fixes a nullability warning

fix exception nullability in TryGetMessage

---

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs

use EnumPolyfill.IsDefined

---

src/Analyzers/MSTest.Analyzers/Helpers/ApplicationStateGuard.cs

UnreachableException is more correct

---

src/Adapter/MSTestAdapter.PlatformServices/AssemblyResolver.cs

not possible for it to be null

remove redundant requestedName != null check

---

src/Adapter/MSTest.TestAdapter/SourceGeneratedDynamicDataOperations.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/IProgressMessage.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/IPushOnlyProtocolConsumer.cs
src/TestFramework/TestFramework/Attributes/TestMethod/STATestClassAttribute.cs

remove redundant bodies

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/DotnetMuxerLocator.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsProxy.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/AssemblyResolverTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/MSTestAdapterSettingsTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs

merge some conditional expressions

---

test/UnitTests/MSTest.Analyzers.UnitTests/TestContextShouldBeValidAnalyzerTests.cs

Test coverage for TestContext analyzer for case sensitivity

---

src/Analyzers/MSTest.Analyzers/TestContextShouldBeValidAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestContextShouldBeValidAnalyzerTests.cs

Fixes https://github.com/microsoft/testfx/issues/4411

Best effort tracking for properties assigned indirectly via fields for TestContext analyzer

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AnalyzersTests.cs

Fix main build

---

src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf

Fix typo in analyzer message

---

test/IntegrationTests/MSTest.IntegrationTests/Utilities/CLITestBase.discovery.cs
test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/DesktopTestSourceHostTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/DesktopTestSourceHostTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/MSTestSettingsProviderTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestDeploymentTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Helpers/UnitTestOutcomeHelperTests.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestExecutorTests.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs
test/UnitTests/MSTestAdapter.UnitTests/RunConfigurationSettingsTests.cs
test/Utilities/Automation.CLI/CLITestBase.common.cs
test/Utilities/Automation.CLI/CLITestBase.e2e.cs

Rename runSettingXml into runSettingsXml

---

src/Analyzers/MSTest.Analyzers/AssertionArgsShouldBePassedInCorrectOrderAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AssertionArgsShouldBePassedInCorrectOrderAnalyzerTests.cs

Fix MSTEST0017 false positive when both actual/expected are constants

---

Directory.Packages.props
test/IntegrationTests/MSTest.IntegrationTests/MSTest.IntegrationTests.csproj
test/IntegrationTests/MSTest.IntegrationTests/Utilities/TestCaseFilterFactory.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj
test/UnitTests/MSTestAdapter.UnitTests/MSTestAdapter.UnitTests.csproj
test/Utilities/TestFramework.ForTestingMSTest/TestFramework.ForTestingMSTest.csproj

Fix "Could not load file or assembly 'System.Runtime.CompilerServicesUnsafe'"

---

src/TestFramework/TestFramework/Attributes/DataSource/DataTestMethodAttribute.cs

Hide DataTestMethodAttribute from IntelliSense

---

eng/Version.Details.xml

This unblocks the polyfill update.

Update SB reference packages

---

src/Analyzers/MSTest.Analyzers/AssemblyCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/AssemblyInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/ClassInitializeShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/Helpers/FixtureUtils.cs
src/Analyzers/MSTest.Analyzers/Helpers/IMethodSymbolExtensions.cs
src/Analyzers/MSTest.Analyzers/PreferConstructorOverTestInitializeAnalyzer.cs
src/Analyzers/MSTest.Analyzers/PreferDisposeOverTestCleanupAnalyzer.cs
src/Analyzers/MSTest.Analyzers/TestCleanupShouldBeValidAnalyzer.cs
src/Analyzers/MSTest.Analyzers/TestInitializeShouldBeValidAnalyzer.cs

Simplify unnecessary extension methods in analyzers

---

src/Analyzers/MSTest.Analyzers/UseParallelizeAttributeAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj
test/UnitTests/MSTest.Analyzers.UnitTests/UseParallelizeAttributeAnalyzerTests.cs

Don't report MSTEST0001 when TestAdapter isn't referenced (#4481)

---

src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf

Fix typo in analyzer message (#4452)

---

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs

method scope fix (#4415)

---

eng/verify-nupkgs.ps1
src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AnalyzersTests.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs

Fix analyzer messages not localized (#4434)

---

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethodOptions.cs

Mark TestMethodOptions.Executor as non-nullable

---

src/Analyzers/MSTest.Analyzers/UseDeploymentItemWithTestMethodOrTestClassAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseDeploymentItemWithTestMethodOrTestClassAnalyzerTests.cs

Don't report diagnostic for DeploymentItem on abstract class

---

src/Analyzers/MSTest.Analyzers/UseDeploymentItemWithTestMethodOrTestClassAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseDeploymentItemWithTestMethodOrTestClassAnalyzerTests.cs

[3.7] Don't report diagnostic for DeploymentItem on abstract class

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/ExceptionFlattener.cs

remove un-used list in ExceptionFlattener.cs

---

src/Platform/Microsoft.Testing.Platform/CommandLine/ResponseFileHelper.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

remove redundant string.ToString()

---

test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/AsynchronousMessageBusTests.cs

missing usings on MessageBusProxy instances

---

src/Platform/Microsoft.Testing.Platform/Logging/TypeNameHelper.cs

remove object based override of GetTypeDisplayName

---

src/Platform/Microsoft.Testing.Extensions.Telemetry/AppInsightsProvider.cs
src/Platform/Microsoft.Testing.Platform/Helpers/DisposeHelper.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs

Cleanup unnecessary await CompletedTask

---

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs

remove redundant conditional compilation in TypeCache

---

src/Platform/Microsoft.Testing.Platform/Messages/AsynchronousMessageBus.cs

use dictionary Values directly when Key is not used

---

src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodFilterTests.cs

inline string literals

---

.github/workflows/backport-base.yml
.github/workflows/backport.yml

This is expected to **not** work. But will need to temporary merge to better understand the next needed steps. Merging isn't going to block CI for other PRs. Currently, it's mostly a copy from dotnet/arcade.

Add backport GH Actions

---

.github/workflows/backport.yml

Backport GH Action

---

.github/workflows/backport-base.yml

Remove env from backport

---

.github/workflows/backport-base.yml

Attempt to handle conflicts in backport action

---

.github/workflows/backport-base.yml

Handle conflicts in backport GH Action

---

.github/workflows/backport-base.yml

Adjust backport PR branch name

---

.github/workflows/backport-base.yml

Fix backport PR description

---

src/TestFramework/TestFramework/Internal/DebugEx.cs

Make Debug.Assert failure clear in CI

---

eng/Version.Details.xml
eng/Versions.props

Bump TA to 1.5.1

---

eng/Versions.props

Update version prefix for 3.7 branch

---

src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj

Cleanup unneeded IVT

---

src/Platform/Microsoft.Testing.Extensions.TrxReport.Abstractions/TrxReportProperties.cs
src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxReportPropertiesTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodePropertiesTests.cs

Ensure IProperty record implementation have nice array display

---

src/Platform/Microsoft.Testing.Platform/CommandLine/ArgumentArity.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOption.cs

Remove non-working <inheritdoc />

---

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBridgedTestFramework.cs
src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs
test/UnitTests/MSTestAdapter.UnitTests/MSTestExecutorTests.cs

Do more async work

---

test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs

Drop tests that are irrelevant

---

test/UnitTests/MSTestAdapter.UnitTests/Execution/TestExecutionManagerTests.cs

Fix bad auto merge

---

.github/ISSUE_TEMPLATE/z-apidocs-feedback.yml

Borrowed from https://github.com/dotnet/roslyn/blob/main/.github/ISSUE_TEMPLATE/z-apidocs-feedback.yml
Contributes to https://github.com/MicrosoftDocs/mtp-api-docs/issues/5

Add API docs feedback template

---

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
src/Adapter/MSTest.TestAdapter/Extensions/TestResultExtensions.cs
src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs
src/Adapter/MSTest.TestAdapter/Helpers/UnitTestOutcomeHelper.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/TestFailedException.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestResult.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestAssemblyInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestResultTest.cs
test/UnitTests/MSTestAdapter.UnitTests/Extensions/MethodInfoExtensionsTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Helpers/UnitTestOutcomeHelperTests.cs
test/UnitTests/MSTestAdapter.UnitTests/ObjectModel/UnitTestResultTests.cs

Cleanup unit test outcome conversion

---

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/Adapter/MSTest.TestAdapter/ObjectModel/FixtureTestResult.cs

[Refactor] Simplify FixtureTestResult

---

src/Adapter/MSTest.TestAdapter/Extensions/UnitTestOutcomeExtensions.cs

Delete unused extension method `ToAdapterOutcome`

---

docs/Changelog-Platform.md
docs/Changelog.md

Update changelog for 3.7.2/1.5.2 release

---

eng/Versions.props

Bump patch version for 3.7

---

src/TestFramework/TestFramework/Assertions/Assert.HasCount.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
src/TestFramework/TestFramework/PublicAPI/net/PublicAPI.Unshipped.txt
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.HasCount.cs

Add Assert.HasCount

---

test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs

[tests] print content of the runtimeconfig when it's malformed

---

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/IgnoreExitCodeTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuild.KnownExtensionRegistration.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.ConfigurationFile.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Solution.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/RetryFailedTestsTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/UnhandledExceptionPolicyTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/LoggerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/NopLoggerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Services/TestApplicationResultTests.cs

Drop explicit use of DynamicDataSourceType

---

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs

Fix wrong Trx warning

---

Directory.Packages.props
src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj

Remove redundant properties

---

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumeratorWrapper.cs
test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs

Cleanup dead code

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/TestMethodShouldNotBeIgnoredAnalyzer.cs

Disable MSTEST0015 in various profiles

---

src/TestFramework/TestFramework/Attributes/TestMethod/OSConditionAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/OperatingSystems.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt

Rename MacOSX to OSX and introduce FreeBSD

---

src/Platform/Microsoft.Testing.Platform/Configurations/AggregatedConfiguration.cs

Delete unused method

---

samples/public/Directory.Build.props
samples/public/global.json

Bump version used in samples to latest

---

src/TestFramework/TestFramework/Assertions/Assert.Contains.cs
src/TestFramework/TestFramework/Assertions/Assert.Count.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt

Add Contains/DoesNotContain assert APIs

---

src/Platform/Microsoft.Testing.Extensions.Retry/RetryExtensions.cs
src/Platform/Microsoft.Testing.Extensions.Telemetry/AppInsightsTelemetryProviderExtensions.cs
src/Platform/Microsoft.Testing.Platform/Builder/TestApplicationBuilder.cs

Fixes https://github.com/microsoft/testfx/pull/4795#discussion_r1930185846

Fix builder extension names

---

src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs

Use field keyword

---

src/TestFramework/TestFramework/Attributes/TestMethod/GitHubWorkItemAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/WorkItemAttribute.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
test/UnitTests/TestFramework.UnitTests/GitHubWorkItemTests.cs

Add GitHubWorkItem

---

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj

Cleanup props/targets copy to output

---

src/Adapter/MSTest.TestAdapter/Execution/TestRunCancellationToken.cs

Cleanup dead code in TestRunCancellationToken

---

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj

Fix doc about supported tfms

---

src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf

Remove wrong closing double quotes in diag messages

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/FileUtilities.cs

remove redundant PathComparer

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminalTestProgressFrame.cs

remove redundant RenderedHeight

---

src/Platform/Microsoft.Testing.Platform/Helpers/ActionResult.cs

remove un-used ActionResult  builders

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressState.cs

remove TestProgressState Attachments

---

src/Platform/Microsoft.Testing.Platform/IPC/INamedPipeBase.cs
src/Platform/Microsoft.Testing.Platform/IPC/IServer.cs

remove INamedPipeBase

---

src/Platform/Microsoft.Testing.Platform/Helpers/System/IConsole.cs
src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemConsole.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

only wrap required console members

---

src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/IMethodSymbolExtensions.cs

remove IsAsyncDisposeImplementation

---

src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/PooledHashSet.cs

remove un-used members from PooledHashSet

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/TestingPlatformEntryPointTask.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs

Cleanup VB entrypoint

---

src/Package/MSTest/PACKAGE.md

Fix MSTest metapackage README

---

Directory.Packages.props
src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj

Drop unnecessary `PackageVersion` entries

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs

convert _testApplicationModuleInfo to a local variable

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/OutputDeviceManager.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs

remove TerminalOutputDevice _process

---

src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
src/Platform/Microsoft.Testing.Platform/Services/CurrentTestApplicationModuleInfo.cs
src/Platform/Microsoft.Testing.Platform/Services/ExecutableInfo.cs

since it is actually the full file path

rename ExecutableInfo FileName to FilePath

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/FailedTestHelper.cs

use range in FailedTestHelper.cs

---

src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/DiagnosticExtensions.cs

remove ReportNoLocationDiagnostic

---

Directory.Packages.props

Disable CentralPackageTransitivePinningEnabled

---

src/Analyzers/MSTest.GlobalConfigsGenerator/GlobalConfigBuilder.cs

Fix DiagnosticSeverity.Info in generated globalconfig

---

src/Adapter/MSTestAdapter.PlatformServices/Extensions/ExceptionExtensions.cs

and move it to a string builder

GetExceptionMessage exception cant be null

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ContextAdapterBase.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/DiscoveryContextAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunContextAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestDiscoverTestExecutionRequest.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestDiscoverTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestRunTestExecutionRequest.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestRunTestExecutionRequestFactory.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestTestExecutionFilter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/VSTestBridgedTestFrameworkBase.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/RunContextAdapterTests.cs

Remove dead code related to filtering

---

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpCommandLineProvider.cs
src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpExtensions.cs
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/HangDumpTests.cs

remove _hangDumpConfiguration

---

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblySettingsProvider.cs
src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestAssemblySettingsProviderTests.cs

Ensure to use the test execution AppDomain for loading the test assembly

---

.editorconfig
TestFx.sln
eng/Analyzers.props
src/Platform/Microsoft.Testing.Extensions.Retry/Microsoft.Testing.Extensions.Retry.csproj
src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
src/TestFramework/TestFramework/Assertions/Assert.AreSame.cs
src/TestFramework/TestFramework/Assertions/Assert.Contains.cs
src/TestFramework/TestFramework/Assertions/Assert.Count.cs
src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
src/TestFramework/TestFramework/Assertions/Assert.IsNull.cs
src/TestFramework/TestFramework/Assertions/Assert.IsTrue.cs
src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs

Rely on CS1591 instead of SA1600 and SA1601

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ParameterizedTestTests.cs

Workaround UsingTestDataRowVariousCases flakiness

---

src/Package/MSTest/MSTest.csproj
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AnalyzersTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/PublishAotNonNativeTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TimeoutTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs

Add CodeCoverage to MSTest metapackage

---

Directory.Build.props
eng/Version.Details.xml
eng/Versions.props
src/Adapter/MSTest.Engine/MSTest.Engine.csproj
src/Analyzers/MSTest.SourceGeneration/MSTest.SourceGeneration.csproj
src/Package/MSTest.Sdk/MSTest.Sdk.csproj
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/MSTest.Acceptance.IntegrationTests.csproj
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceTestBase.cs

Follow-up to the move of SourceGen + Engine

---

Directory.Packages.props
eng/Version.Details.xml
eng/Versions.props

The upgrades are being done to main in #4985

[rel/3.8] Update deps

---

eng/Versions.props

Bump main version to 3.9/1.7

---

samples/public/Directory.Build.props
samples/public/global.json

Bump samples to latest

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md

Move AnalyzerReleases.Unshipped to AnalyzerReleases.Shipped

---

Directory.Packages.props

Update Aspire and Playwright dependencies

---

src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/net9.0-windows10.0.17763.0/PublicAPI.Shipped.txt
src/TestFramework/TestFramework.Extensions/PublicAPI/net9.0-windows10.0.17763.0/PublicAPI.Shipped.txt

Fix PublicAPI.Shipped.txt

---

src/Analyzers/MSTest.Analyzers/AvoidAssertAreSameWithValueTypesAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs

Fixes https://github.com/microsoft/testfx/issues/5007

Fix MSTEST0038 message

---

test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TestAssetFixtureBase.cs

Avoid potential duplicate binlog file names in integration tests

---

src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemConsole.cs

Fix handling of unsupported platforms of CancelKeyPress

---

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets

Revert _IncludeGenerateAutoRegisteredExtensionsIntoCompilation target rename

---

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs
src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
src/Platform/Microsoft.Testing.Platform/Configurations/AggregatedConfiguration.cs
src/Platform/Microsoft.Testing.Platform/Configurations/JsonConfigurationProvider.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/Services/CurrentTestApplicationModuleInfo.cs
src/Platform/Microsoft.Testing.Platform/Services/ITestApplicationModuleInfo.cs
src/Platform/Microsoft.Testing.Platform/Telemetry/TelemetryManager.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/AggregatedConfigurationTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Telemetry/TelemetryManagerTests.cs

Refactor logic around GetCurrentTestApplicationFullPath

---

src/Adapter/MSTest.Engine/Helpers/TestApplicationBuilderExtensions.cs
src/Adapter/MSTest.Engine/TestFramework/MSTestEngineBannerCapability.cs
src/Adapter/MSTest.Engine/TestFramework/TestFrameworkCapabilities.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ContextAdapterBase.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/NativeAotTests.cs

Add banner for MSTest.Engine

---

THIRD-PARTY-NOTICES.TXT
src/Analyzers/MSTest.SourceGeneration/Helpers/EquatableArray{T}.cs
src/Analyzers/MSTest.SourceGeneration/Helpers/HashCode.cs
src/Analyzers/MSTest.SourceGeneration/MSTest.SourceGeneration.csproj
src/Analyzers/MSTest.SourceGeneration/ObjectModels/TestMethodInfo.cs
src/Analyzers/MSTest.SourceGeneration/ObjectModels/TestTypeInfo.cs

Improve MSTest.SourceGeneration incrementality

---

samples/public/Directory.Build.props
samples/public/global.json

Update samples to 3.8.1

---

eng/Versions.props

Bump patch version for 3.8

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/NamespaceHelpers.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/TestingPlatformAutoRegisteredExtensions.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/TestingPlatformEntryPointTask.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/UnicodeCharacterUtilities.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuild.KnownExtensionRegistration.cs

Handle if RootNamespace contains invalid identifier characters

---

docs/Changelog-Platform.md
docs/Changelog.md

Update Changelog for 3.8.2

---

samples/public/Directory.Build.props

Update samples to 3.8.2

---

eng/Versions.props

[rel/3.8] Bump patch to .3

---

Directory.Packages.props

Update MSTestVersion to 3.9 preview

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RunnerTests.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuild.KnownExtensionRegistration.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TypeForwardingTests.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetMuxerResult.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs

Cleanup integration tests binlogs

---

src/Analyzers/MSTest.Analyzers.CodeFixes/UseNewerAssertThrowsFixer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseNewerAssertThrowsAnalyzerTests.cs

Fix discard handling for newer Assert.Throws codefix

---

Directory.Packages.props
src/Platform/Microsoft.Testing.Extensions.TrxReport.Abstractions/Microsoft.Testing.Extensions.TrxReport.Abstractions.csproj
src/Platform/Microsoft.Testing.Extensions.TrxReport.Abstractions/TrxReportProperties.cs
src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs

use StringBuilder AppendJoin

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestRunArtifact.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

Remove dead code in TerminalTestReporter

---

src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemConsole.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ConsoleTests.cs

Hopefully fixes https://github.com/microsoft/testfx/issues/5158

Fix possible deadlock when writing to console

---

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
src/Platform/Microsoft.Testing.Platform/build/Microsoft.Testing.Platform.targets
src/Platform/Microsoft.Testing.Platform/buildMultiTargeting/Microsoft.Testing.Platform.targets
src/Platform/Microsoft.Testing.Platform/buildTransitive/Microsoft.Testing.Platform.targets

Move logic relevant to core MTP out of MTP.MSBuild

---

azure-pipelines-official.yml

Try workaround for official builds

---

azure-pipelines-official.yml

Don't publish Linux packages

---

Directory.Packages.props

Update dogfooded MSTest version

---

eng/Versions.props
samples/Playground/Tests.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs

Add assembly name

---

src/Platform/Microsoft.Testing.Platform/Services/IPlatformInformation.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CustomBannerTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/NoBannerTests.cs

Correct branding as Microsoft.Testing.Platform

---

eng/Versions.props

[rel/3.8] Bump patch version

---

samples/public/Directory.Build.props

Uppdate MSTest dependency of public samples

---

src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs

Fix Retry for dotnet test

---

src/TestFramework/TestFramework/Assertions/Assert.Contains.cs

Fix stackoverflow in Assert.DoesNotContain

---

eng/Versions.props

Revert wrong version change

---

src/Platform/Microsoft.Testing.Platform/Configurations/ConfigurationManager.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs

Use FileAccess.Read when reading testconfig.json file

---

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs

Fix TypeCache re-calculating info when running in parallel

---

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs

Fix test property not considering the test class correctly

---

src/Analyzers/MSTest.Analyzers/ReviewAlwaysTrueAssertConditionAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/ReviewAlwaysTrueAssertConditionAnalyzerTests.cs

Fix MSTEST0032 false positive with nullability analysis

---

src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/TestFramework/TestFramework/Attributes/TestMethod/RetryContext.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt

Add RetryContext.FirstRunResults

---

Directory.Packages.props

Update MSTestVersion and MTPVersion

---

src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs
src/TestFramework/TestFramework/Attributes/DataSource/DataSourceAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/TestClassAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs

Fix XML doc comments

---

src/Platform/Microsoft.Testing.Extensions.HotReload/HotReloadHandler.cs
src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj
src/Platform/Microsoft.Testing.Platform/OutputDevice/BrowserOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/OutputDeviceManager.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs
src/Platform/Microsoft.Testing.Platform/Services/CTRLPlusCCancellationTokenSource.cs

There are likely more needed changes to properly support wasi, but this is a good step at least.
Related to #5366, but likely more changes will be needed.
cc @jjonescz

Mark APIs not supported in wasi

---

src/Platform/Microsoft.Testing.Extensions.AzureDevOps/AzureDevOpsReporter.cs

remove redundant null check in WriteExceptionAsync

---

src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentItemUtility.cs

remove redundant null checks in DeploymentItemUtility

---

test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs

fix nullability in GetRepoRoot

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs

remove redundant null check in FormatInnerExceptions

---

src/Adapter/MSTest.Engine/Engine/ThreadPoolTestNodeRunner.cs
src/Adapter/MSTest.Engine/TestFramework/TestFramework.cs
test/Utilities/TestFramework.ForTestingMSTest/TestFramework.cs

remove redundant catch

---

samples/Playground/ServerMode/v1.0.0/TestingPlatformClient.cs
src/Adapter/MSTest.Engine/Engine/ThreadPoolTestNodeRunner.cs
src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs
src/Platform/Microsoft.Testing.Extensions.AzureDevOps/AzureDevOpsReporter.cs
src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs
src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs
src/Platform/Microsoft.Testing.Extensions.Telemetry/AppInsightsProvider.cs
src/Platform/Microsoft.Testing.Platform/Helpers/NonCooperativeParentProcessListener.cs
src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs
src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs
src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RunnerTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ServerMode/v1.0.0/TestingPlatformClient.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/AppInsightsProviderTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/IPC/IPCTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/ExpectedExceptionBaseAttributeTests.cs

remove redundant control flow statements

---

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs

remove redundant ReflectHelper constructor

---

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/ExtensionResources.resx
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.cs.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.de.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.es.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.fr.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.it.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ja.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ko.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.pl.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.pt-BR.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ru.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.tr.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.zh-Hans.xlf
src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.zh-Hant.xlf

For context: https://github.com/dotnet/diagnostics/issues/2215

Show disk info when hang dump fails

---

.editorconfig
samples/Playground/Program.cs
src/Adapter/MSTest.Engine/TestFramework/TestFramework.cs
src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/DotnetTestConnection.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ConsoleTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/TestAssets/DynamicDataTestProject/DataProvider.cs
test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
test/IntegrationTests/TestAssets/LibProjectReferencedByDataSourceTest/User.cs
test/Performance/MSTest.Performance.Runner/Steps/PlainProcess.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs
test/UnitTests/MSTest.Engine.UnitTests/BFSTestNodeVisitorTests.cs
test/UnitTests/MSTest.SourceGeneration.UnitTests/Helpers/SyntaxExtensions.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/DiaSessionOperationsTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeEnumeratorTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs
test/UnitTests/MSTestAdapter.UnitTests/Extensions/TestResultExtensionsTests.cs
test/Utilities/Automation.CLI/CLITestBase.common.cs
test/Utilities/TestFramework.ForTestingMSTest/TestFramework.cs

remove redundant braces and mark as error in rider and R#

---

.editorconfig
src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidExpectedExceptionAttributeFixer.cs

avoid redundant where and mark as an error for rider and r#

---

test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs

remove redundant null checks in UnitTestRunnerTests

---

test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs

remove redundant null checks in AssemblyEnumeratorTests

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/DotnetMuxerLocator.cs

remove redundant  null check for OpenBaseKey return

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs

remove redundant null check in GetStringFromIndexOrDefault

---

src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestElement.cs

remove redundant null check in UnitTestElement

---

.editorconfig

Downgrade error entries in .editorconfig to warning

---

src/Adapter/MSTest.Engine/Engine/BFSTestNodeVisitor.cs

remove un-used TestNodeProcessor

---

test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs

Remove incorrect TestMethod attributes

---

src/Analyzers/MSTest.SourceGeneration/ObjectModels/IParameterInfo.cs

remove un-used IParameterInfo

---

Directory.Packages.props

Update MTP's telemetry dependency on Microsoft.ApplicationInsights to 2.23.0

---

test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs

Remove dead code in TestInfrastructure

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/TestingPlatformEntryPointTask.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
test/UnitTests/Microsoft.Testing.Platform.MSBuild.UnitTests/MSBuildTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs

Rename MTP entrypoint to MicrosoftTestingPlatformEntryPoint

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs
src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt
src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
src/Analyzers/MSTest.Analyzers/Resources.resx
src/Analyzers/MSTest.Analyzers/UseRetryWithTestMethodAnalyzer.cs
src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/UseRetryWithTestMethodAnalyzerTests.cs

Implement analyzer for RetryAttribute to be present on test methods

---

.editorconfig
src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidExpectedExceptionAttributeFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/PreferConstructorOverTestInitializeFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/PreferDisposeOverTestCleanupFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/PreferTestInitializeOverConstructorFixer.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/PassiveNode.cs

use null propagation and mark as warning in editorconfig

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RetryTests.cs

Tests what was implemented in #5425

Add test for TestContext.TestRunCount

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs

Add test for TestProperty attribute

---

src/Analyzers/MSTest.Analyzers.CodeFixes/AssemblyCleanupShouldBeValidFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/AssemblyInitializeShouldBeValidFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/ClassCleanupShouldBeValidFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/ClassInitializeShouldBeValidFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/TestCleanupShouldBeValidFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/TestInitializeShouldBeValidFixer.cs

FindNode cant return null

---

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/UnicodeCharacterUtilities.cs

remove un-used methods in UnicodeCharacterUtilities

---

src/Analyzers/MSTest.SourceGeneration/Helpers/TestNodeHelpers.cs

use-char-based-replace-in-string

---

.editorconfig
src/Platform/Microsoft.Testing.Extensions.Retry/RetryExecutionFilterFactory.cs
src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs
src/Platform/Microsoft.Testing.Platform/Services/ServiceProviderExtensions.cs

Remove some redundant casts and mark as a warning for rider and R#

---

src/Analyzers/MSTest.SourceGeneration/Helpers/EquatableArray{T}.cs

remove un-used static class EquatableArray

---

Directory.Packages.props

Fixes #5483
3.8.* requires latest Fakes

Update Fakes dependency

---

Directory.Packages.props
test/IntegrationTests/MSTest.IntegrationTests/MSTest.IntegrationTests.csproj
test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/PlatformServices.Desktop.IntegrationTests.csproj
test/UnitTests/MSTest.SourceGeneration.UnitTests/Helpers/SourceCodeAssertionExtensions.cs
test/UnitTests/MSTest.SourceGeneration.UnitTests/Helpers/SourceCodeAssertions.cs
test/UnitTests/MSTest.SourceGeneration.UnitTests/MSTest.SourceGeneration.UnitTests.csproj
test/Utilities/Automation.CLI/Automation.CLI.csproj

Move to AwesomeAssertions

---

src/Analyzers/MSTest.Analyzers/AssertionArgsShouldBePassedInCorrectOrderAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/AssertionArgsShouldBePassedInCorrectOrderAnalyzerTests.cs

Fix MSTEST0017 (actual/expected order) false negative for conversions

---

test/Utilities/TestFramework.ForTestingMSTest/TestFrameworkEngine.cs

[Internal test framework] Produce Trx properties

---

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs

Handle `DebugOrTraceTrxMessage` in TrxReportEngine

---

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
src/TestFramework/TestFramework/Attributes/TestMethod/TestResult.cs
test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
test/UnitTests/TestFramework.UnitTests/TestResultTests.cs

Avoid overwriting TestFailureException

---

Directory.Packages.props

Update MSTest/MTP dogfooding version

---

src/Platform/Microsoft.Testing.Extensions.AzureDevOps/AzureDevOpsReporter.cs
src/Platform/Microsoft.Testing.Extensions.Retry/RetryDataConsumer.cs
src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs
src/Platform/Microsoft.Testing.Platform/Extensions/AbortForMaxFailedTestsExtension.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/DotnetTestDataConsumer.cs

UseSingleOrDefault for test node state

---

test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Contains.cs
test/UnitTests/TestFramework.UnitTests/TestFramework.UnitTests.csproj

Add some unit tests for Assert.Contains/DoesNotContain

---

src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseProperAssertMethodsAnalyzerTests.cs

Fix false positive of Assert.IsTrue(x == null) when x is a pointer type

---

eng/build.ps1

Set _TestingPlatformDiagnostics_ in VS

---

eng/Versions.props

Update branding to MSTest 3.10 and MTP 1.8

---

azure-pipelines-official.yml

Disable also post steps that publish to darc.

Remove post steps

---

Directory.Packages.props

Update Fakes dependency to 17.14.1

---

src/TestFramework/TestFramework/Attributes/TestMethod/OSConditionAttribute.cs

OSConditionAttribute: Make ignore message depend on ConditionMode

---

global.json
src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/IOperationExtensions.cs

Ensures we are dogfooding the latest `dotnet test`

Update SDK to 10.0.100-preview.5.25269.23

---

src/Platform/Microsoft.Testing.Platform/CommandLine/Parser.cs

use char based APIs in TryUnescape

---

src/Platform/Microsoft.Testing.Platform/CommandLine/Parser.cs

attribute param nullability in TryUnescape

---

src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/RpcMessages.cs

Delete unused ClientTestingCapabilities

---

src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs

Cleanup unneeded count variable in `SerializeAsync`

---

docs/Changelog-Platform.md
docs/Changelog.md
docs/README.md
docs/RFCs/007-DataSource-Attribute-VS-ITestDataSource.md

Fix changelog date

---

src/Platform/Microsoft.Testing.Platform/Services/TestApplicationResult.cs

- `IsOptionSet` isn't too cheap and was called previously on every `ConsumeAsync` in TestApplicationResult (for every test result we get). Now we calculate it once in TestApplicationResult constructor.
- We used to keep a list of `_failedTests` for no good reason. We only need the count.

Cleanup TestApplicationResult

---

src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs
src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs
src/Analyzers/MSTest.Analyzers/UseAttributeOnTestMethodAnalyzer.cs
src/TestFramework/TestFramework/Attributes/TestMethod/OwnerAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/PriorityAttribute.cs
test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/ReflectionUtilityTests.cs

Inherit OwnerAttribute and PriorityAttribute from TestPropertyAttribute

---

src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs

Cleanup always-true #if NETCOREAPP

---

Directory.Packages.props

This version has the fix from https://github.com/SimonCropp/Polyfill/pull/330

Update Polyfill to 7.32.0

---

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs

Add missing overload for Assert.Throws

---

src/Platform/Microsoft.Testing.Extensions.Telemetry/AppInsightTelemetryClient.cs
src/Platform/Microsoft.Testing.Platform/Configurations/EnvironmentVariablesConfigurationProvider.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/StreamMessageHandler.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs

remove redundant fields

---

samples/public/Directory.Build.props
samples/public/global.json

Update MSTest version in samples

---

Directory.Packages.props

Update dogfooding versions

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs

[VSTestBridge] Avoid creating Uri instance for every test case.

---

src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs
src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.Designer.cs
src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.resx
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.de.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.es.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.it.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.zh-Hant.xlf

Error if framework/adapter versions are mismatched at runtime

---

azure-pipelines.yml

Revert "Exclude folders"

---

src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodInfo.cs
src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodRunner.cs
src/Adapter/MSTestAdapter.PlatformServices/Execution/TypeCache.cs
src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TypeCacheTests.cs

Cleanup two equivalent properties in TestMethodInfo

---

.github/copilot-instructions.md

Add `copilot-instructions.md`

---

docs/Changelog-Platform.md
docs/Changelog.md

Add changelogs for 3.9.3

---

azure-pipelines.yml

Enable local dumps for handle not initialized issue

---

.editorconfig

Add support for xlf in editorconfig

---

src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs

Change IsInstanceOfType to return the instance of type T

---

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestDiscoverer.cs
src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs
src/Adapter/MSTestAdapter.PlatformServices/AssemblyResolver.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/AssemblyResolverTests.cs

Internalize obsolete types

---

src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodInfo.cs

Make TestMethodInfo internal

---

src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ObjectModel/ITestMethod.cs
src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs
src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TypeEnumeratorTests.cs

Make ITestMethod internal

---

src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs

TestCase.Id shouldn't include executor uri

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs

Bump AvoidExpectedExceptionAttributeAnalyzer to warning

---

src/TestFramework/TestFramework/Assertions/Assert.Contains.cs
src/TestFramework/TestFramework/Assertions/Assert.EndsWith.cs
src/TestFramework/TestFramework/Assertions/Assert.IComparable.cs
src/TestFramework/TestFramework/Assertions/Assert.Matches.cs
src/TestFramework/TestFramework/Assertions/Assert.StartsWith.cs
src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Contains.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IComparableTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInRange.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Items.cs

@Evangelink Are you fine with the simplified APIs in 3.10?

Adjust new assert APIs before shipping

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/UseNewerAssertThrowsAnalyzer.cs

Bump UseNewerAssertThrowsAnalyzer to warning

---

.github/dependabot.yml
src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs

Merge main to dev/v4

---

src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs

Remove unused internal property TestMethod.UniqueName

---

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
src/Analyzers/MSTest.Analyzers/UseCooperativeCancellationForTimeoutAnalyzer.cs

Make UseCooperativeCancellationForTimeoutAnalyzer warning

---

src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/UnitTestDiscovererTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestSettingsTests.cs

Default TreatDiscoveryWarningsAsErrors to true

---

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs

[MTP] Handle metadata properties in TrxReport

---

azure-pipelines.yml

Fix race in artifact publishing in PRs

---

src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
src/Adapter/MSTestAdapter.PlatformServices/Discovery/TypeEnumerator.cs
src/Adapter/MSTestAdapter.PlatformServices/EngineConstants.cs
src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs
src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs
src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs

Include parameter types in test id

---

src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/BridgedTraceLogger.cs

check logging level in BridgedTraceLogger

---

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs

remove redundant assignment in TryGetOptionArgumentList

---

src/Platform/Microsoft.Testing.Extensions.HangDump/WindowsMiniDumpWriteDump.cs

missing using in WindowsMiniDumpWriteDump

---

src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestResultExtensions.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/Condition.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ContextAdapterBase.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FastFilter.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
test/IntegrationTests/TestAssets/FxExtensibilityTestProject/TestDataSourceExTests.cs

use some string interpolation

---

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs

[MTP] Fix TrxReport not including test ignore reason

---

Directory.Packages.props
src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
src/Adapter/MSTestAdapter.PlatformServices/Services/TestSourceHost.cs
src/Analyzers/MSTest.SourceGeneration/ObjectModels/DynamicDataTestMethodArgumentsInfo.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs
src/Platform/Microsoft.Testing.Platform/Services/ExecutableInfo.cs
src/TestFramework/TestFramework/Internal/TestDataSourceUtilities.cs
test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/ReflectionUtilityTests.cs
test/UnitTests/MSTest.SourceGeneration.UnitTests/Helpers/SyntaxExtensions.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/CommandLine.cs
test/Utilities/Microsoft.Testing.TestInfrastructure/TargetFrameworks.cs

use char based overloads

---

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

We removed the old TFMs already.

[rel/4.0] Fix tests

---

src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs

Handle framework's Logger to write to test context

---

src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs
src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
src/Platform/Microsoft.Testing.Platform/Helpers/EnvironmentVariableConstants.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/RetryFailedTestsTests.cs

Ensure TestRun id for retries is the same in TRX

---

src/Platform/Microsoft.Testing.Platform/Helpers/ActionResult.cs

remove non generic ActionResult

---

Directory.Packages.props
src/Platform/Microsoft.Testing.Platform/IPC/Serializers/BaseSerializer.cs

use ReadExactly from Polyfill

---

Directory.Build.props
src/Adapter/MSTest.Engine/Engine/BFSTestNodeVisitor.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBannerCapability.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestGracefulStopTestExecutionCapability.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs
src/Platform/Microsoft.Testing.Extensions.HotReload/HotReloadTestHostTestFrameworkInvoker.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FrameworkHandlerAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsPatcher.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/TestCaseDiscoverySinkAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/VSTestBridgedTestFrameworkBase.cs
test/UnitTests/MSTest.Engine.UnitTests/Adapter_ExecuteRequestAsyncTests.cs
test/UnitTests/MSTest.Engine.UnitTests/BFSTestNodeVisitorTests.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs

suppress TPEXP warning for solution

---

azure-pipelines.yml

This, IMO, provides better output.

Use --no-progress

---

Directory.Build.props
Directory.Packages.props
azure-pipelines.yml
src/Adapter/MSTest.Engine/Engine/BFSTestNodeVisitor.cs
src/Adapter/MSTest.Engine/Engine/TestArgumentsManager.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBannerCapability.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestGracefulStopTestExecutionCapability.cs
src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs
src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
src/Platform/Microsoft.Testing.Extensions.HotReload/HotReloadTestHostTestFrameworkInvoker.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FrameworkHandlerAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsPatcher.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/TestCaseDiscoverySinkAdapter.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/VSTestBridgedTestFrameworkBase.cs
src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/DotnetMuxerLocator.cs
src/Platform/Microsoft.Testing.Platform/Helpers/System/IProcess.cs
src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemFileSystem.cs
src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs
src/Platform/Microsoft.Testing.Platform/IPC/Serializers/BaseSerializer.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs
src/Platform/Microsoft.Testing.Platform/Services/CurrentTestApplicationModuleInfo.cs
src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
test/UnitTests/MSTest.Engine.UnitTests/Adapter_ExecuteRequestAsyncTests.cs
test/UnitTests/MSTest.Engine.UnitTests/BFSTestNodeVisitorTests.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs

Merge main to rel/4.0

---

src/Platform/Microsoft.Testing.Platform/Messages/AsynchronousMessageBus.cs

use TryAdd instead of TryGetValue and Add in Async MessageBus

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressState.cs

fix nullability of TestProgressState.DiscoveredTests

---

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs

Do not create TestResults dir for help and info options

---

Directory.Packages.props
src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
src/Platform/Microsoft.Testing.Platform/Helpers/Sha256Hasher.cs

also addresses a missing using in TrxReportEngine

update Polyfill and simplify SHA256 usage

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs

reduce some linq alloc in AppendTestDiscoverySummary

---

src/Platform/Microsoft.Testing.Platform/Logging/FileLoggerInformation.cs
src/Platform/Microsoft.Testing.Platform/Logging/IFIleLoggerInformation.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs

fix Syncronous typo

---

src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs

Add clarifying comment to NamedPipeServer.WaitConnectionAsync

---

src/Analyzers/MSTest.SourceGeneration/Helpers/SystemPolyfills.cs

remove some un-used polyfills

---

.github/copilot-instructions.md

Update copilot instructions

---

Directory.Packages.props
eng/Versions.props
test/Directory.Build.targets
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AnalyzersTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CrashDumpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceAssert.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ServerLoggingTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs
test/UnitTests/MSTest.Engine.UnitTests/DynamicDataNameProviderTests.cs
test/UnitTests/MSTest.SourceGeneration.UnitTests/TestUtilities/TestingFrameworkVerifier.cs
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationExtensionsTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/IPC/IPCTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/AsynchronousMessageBusTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/PropertyBagTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodeUidTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Services/ServiceProviderTests.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/TestApplicationBuilderTests.cs

Use newer version of MSTest

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminal.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporterOptions.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestRunArtifact.cs
src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs

Further cleanup to terminal test reporter

---

src/Analyzers/MSTest.Analyzers.CodeFixes/PreferTestMethodOverDataTestMethodFixer.cs
src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs
src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
src/Analyzers/MSTest.Analyzers/PreferTestMethodOverDataTestMethodAnalyzer.cs
src/TestFramework/TestFramework/Attributes/DataSource/DataTestMethodAttribute.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DataSourceTests.cs
test/IntegrationTests/TestAssets/DiscoverInternalsProject/UnitTest1.cs
test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
test/IntegrationTests/TestAssets/TestIdProject.DefaultStrategy/TestIdCases.cs
test/UnitTests/MSTest.Analyzers.UnitTests/DataRowShouldBeValidAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/PreferTestMethodOverDataTestMethodAnalyzerTests.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseAsyncSuffixTestMethodSuppressorTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TypeEnumeratorTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/DynamicDataAttributeTests.cs

This reverts commit 512a54c396a29a33a6263262b68dc87e04aa4df7.
Related to #1285

[rel/4.0] Revert "Drop DataTestMethodAttribute (#5831)"

---

src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AppDomainTests.cs

Workaround DisableAppDomain issue for VSTest

---

azure-pipelines-official.yml

Produce test binlogs for official pipeline

---

src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs
src/Adapter/MSTestAdapter.PlatformServices/RunConfigurationSettings.cs

MSTestSettings removed deps to IDiscoveryContext

---

global.json

Update SDK to latest from main

---

src/Adapter/MSTestAdapter.PlatformServices/Helpers/AttributeHelpers.cs
src/TestFramework/TestFramework/Attributes/TestMethod/CIConditionAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/ConditionBaseAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/IgnoreAttribute.cs
src/TestFramework/TestFramework/Attributes/TestMethod/OSConditionAttribute.cs
test/UnitTests/TestFramework.UnitTests/Attributes/CIConditionAttributeTests.cs

ConditionBaseAttribute.ShouldRun -> IsConditionMet

---

src/TestFramework/TestFramework/Attributes/TestMethod/TestTimeout.cs
src/TestFramework/TestFramework/Attributes/TestMethod/TimeoutAttribute.cs
src/TestFramework/TestFramework/FrameworkConstants.cs
test/IntegrationTests/TestAssets/TimeoutTestProject/TimeoutTestClass.cs

Obsolete `TestTimeout`

---

test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj

Move MSTest.Analyzers.UnitTests to net472 instead of net462

---

azure-pipelines-official.yml

Fix official pipeline

---

eng/Version.Details.xml
eng/Versions.props

[rel/3.10] Use stable CC

---

samples/public/Directory.Build.props
samples/public/global.json

Update public samples to 3.10

---

eng/Versions.props
src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
test/Directory.Build.props

Use MS CC 18.1 preview

---

src/Package/MSTest/MSTest.csproj

Fix MSTest metapackage

---

src/Adapter/MSTestAdapter.PlatformServices/Discovery/UnitTestDiscoverer.cs
src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.Designer.cs
src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.resx
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.cs.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.de.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.es.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.fr.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.it.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ja.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ko.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.pl.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.pt-BR.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.ru.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.tr.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.zh-Hans.xlf
src/Adapter/MSTestAdapter.PlatformServices/Resources/xlf/Resource.zh-Hant.xlf
src/TestFramework/TestFramework/Exceptions/MSTestException.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/UnitTestDiscovererTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj

Replaces #6202 and fixes #5992

Fail on warn as error in discovery

---

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
src/Platform/Microsoft.Testing.Extensions.AzureDevOpsReport/Microsoft.Testing.Extensions.AzureDevOpsReport.csproj
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

Make azdo extension stable

---

src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
src/Adapter/MSTestAdapter.PlatformServices/Execution/TypeCache.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestDiscoveryWarningsTests.cs
test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/AssemblyEnumeratorTests.cs

Fixes https://github.com/microsoft/testfx/issues/6275

Don't return null types from AssemblyEnumerator when ReflectionTypeLoadException is encountered

---

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs

- Reduce nesting
- factorize code

Cleanup TerminalTestReporter

---

docs/Changelog-Platform.md
docs/Changelog.md
samples/public/Directory.Build.props
samples/public/global.json

Post-release changes for 3.10.1

---

eng/Versions.props

Update 3.10 patch version

---

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

Don't include Microsoft.NET.Test.Sdk for MTP in MSTest.Sdk

---

src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets
test/Directory.Build.props
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs

[rel/4.0]: MSTest.Sdk: Enable CC in NativeAOT.targets and in our tests

---

eng/Version.Details.xml
eng/Versions.props

[rel/4.0] Update CC version

---

MSTest.slnf

Add missing MSTest.GlobalConfigsGenerator to MSTest.slnf

---

src/Package/MSTest.Sdk/MSTest.Sdk.csproj

MSTest.Sdk: temporary hardcode MTP version to release

---

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets

Add aka.ms link for dotnet.config error

---

docs/mstest-runner-protocol/001-protocol-intro.md
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs
test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs

Remove unused JsonRpc protocol properties

---

src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx
src/Analyzers/MSTest.Analyzers.CodeFixes/UseExecuteAsyncOverrideFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/UseExecuteAsyncOverrideFixerTests.cs

Implement codefix to switch Execute to ExecuteAsync

---

src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx
src/Analyzers/MSTest.Analyzers.CodeFixes/TestContextPropertiesContainsKeyFixer.cs
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf
src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf
test/UnitTests/MSTest.Analyzers.UnitTests/TestContextPropertiesContainsKeyFixerTests.cs

Implement codefix for migrating TestContext.Properties to generic IDictionary

---

src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/UseProperAssertMethodsAnalyzerTests.cs

Replaces https://github.com/microsoft/testfx/pull/6341
Fixes #6312

MSTEST0037: Recognize IsTrue(collection.[Count|Length] [==|>|!=] 0) patterns and cleanup

---

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Configurations/RunSettingsConfigurationProvider.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Helpers/RunSettingsHelpers.cs
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs

Fixes https://github.com/microsoft/testfx/issues/6421

Unify reading runsettings

---

docs/Changelog-Platform.md
docs/Changelog.md

Update Changelog for 3.10.3

---

src/Analyzers/MSTest.Analyzers.CodeFixes/TestMethodShouldBeValidCodeFix.cs
test/UnitTests/MSTest.Analyzers.UnitTests/TestMethodShouldBeValidAnalyzerTests.cs

Fix some bugs with TestMethodShouldBeValidCodeFix

---

src/Analyzers/MSTest.Analyzers.CodeFixes/TestMethodShouldBeValidCodeFix.cs

Follow-up from comment in #6450

Use SyntaxFactory.IdentifierName instead of ParseTypeName

---

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpActivityIndicator.cs
src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs
src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxTestApplicationLifecycleCallbacks.cs
src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeClient.cs
src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/DotnetTestConnection.cs

Don't keep MTP process alive if pipe disconnects

---

src/Analyzers/MSTest.Analyzers.CodeFixes/StringAssertToAssertFixer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/StringAssertToAssertAnalyzerTests.cs

Fix StringAssertToAssertFixer to swap StringComparison and message arguments

---

test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreSame.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.InconclusiveTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInRange.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsNull.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsTrueTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Items.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
test/UnitTests/TestFramework.UnitTests/Assertions/StringAssertTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/DynamicDataAttributeTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/ExpectedExceptionAttributeTests.cs
test/UnitTests/TestFramework.UnitTests/Attributes/ExpectedExceptionBaseAttributeTests.cs
test/UnitTests/TestFramework.UnitTests/GitHubWorkItemTests.cs
test/UnitTests/TestFramework.UnitTests/LoggerTests.cs
test/UnitTests/TestFramework.UnitTests/TestDataRowTests.cs
test/UnitTests/TestFramework.UnitTests/TestResultTests.cs

Use AwesomeAssertions for framework UTs

---

src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeClient.cs
src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs

More pipe improvements

---

src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs
test/IntegrationTests/MSTest.Acceptance.IntegrationTests/HelpInfoTests.cs
test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs

Rename --debug-wait-attach to --debug

---

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets

Update warning message to not mention dotnet.config

---

src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs

Follow-up to #6292. We lost the user message in that PR.

Follow-up on CollectionAssert change

---

src/Analyzers/MSTest.Analyzers.CodeFixes/FlowTestContextCancellationTokenFixer.cs
src/Analyzers/MSTest.Analyzers/FlowTestContextCancellationTokenAnalyzer.cs
test/UnitTests/MSTest.Analyzers.UnitTests/FlowTestContextCancellationTokenAnalyzerTests.cs

Fix flow cancellation token codefix to use named arg when necessary

---

eng/Versions.props

Use stable CC in rel/3.11

---

docs/Changelog-Platform.md
docs/Changelog.md

Update Changelog for 3.11.0

---

src/Platform/Microsoft.Testing.Extensions.HangDump/Helpers/IProcessExtensions.cs

Cleanup IProcessExtensions

---

Directory.Build.props
src/Adapter/MSTest.Engine/MSTest.Engine.csproj
src/Platform/Microsoft.Testing.Extensions.AzureDevOpsReport/Microsoft.Testing.Extensions.AzureDevOpsReport.csproj
src/Platform/Microsoft.Testing.Extensions.CrashDump/Microsoft.Testing.Extensions.CrashDump.csproj
src/Platform/Microsoft.Testing.Extensions.HangDump/Microsoft.Testing.Extensions.HangDump.csproj
src/Platform/Microsoft.Testing.Extensions.HotReload/Microsoft.Testing.Extensions.HotReload.csproj
src/Platform/Microsoft.Testing.Extensions.MSBuild/Microsoft.Testing.Extensions.MSBuild.csproj
src/Platform/Microsoft.Testing.Extensions.Retry/Microsoft.Testing.Extensions.Retry.csproj
src/Platform/Microsoft.Testing.Extensions.Telemetry/Microsoft.Testing.Extensions.Telemetry.csproj
src/Platform/Microsoft.Testing.Extensions.TrxReport.Abstractions/Microsoft.Testing.Extensions.TrxReport.Abstractions.csproj
src/Platform/Microsoft.Testing.Extensions.TrxReport/Microsoft.Testing.Extensions.TrxReport.csproj
src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Microsoft.Testing.Extensions.VSTestBridge.csproj
src/Platform/Microsoft.Testing.Platform.MSBuild/Microsoft.Testing.Platform.MSBuild.csproj
src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj
test/UnitTests/MSTest.Engine.UnitTests/MSTest.Engine.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Extensions.UnitTests/Microsoft.Testing.Extensions.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests.csproj
test/UnitTests/Microsoft.Testing.Platform.UnitTests/Microsoft.Testing.Platform.UnitTests.csproj
test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj
test/Utilities/TestFramework.ForTestingMSTest/TestFramework.ForTestingMSTest.csproj

Cleanup MicrosoftTestingTargetFrameworks

---

Directory.Packages.props

Update VSTest to 18.0.0

---

eng/Versions.props

Updated MicrosoftTestingExtensionsCodeCoverageVersion to stable version.

Update CC to 18.1.0 stable

---

eng/Versions.props

Update main to 4.1/2.1
