microsoft/testfx

src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs
Fix for #136 . We were not checking if Test Initialize was complete. Doing so now.
=> TestInitialize failure and ExpectedException.

src/Adapter/MSTest.CoreAdapter/Execution/LogMessageListener.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/ObjectModel/TestMethodOptions.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/LogMessageListenerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs
We were wrapping LogMessageListener over the test methods execution multiple times.
Fixing #114 .
=> Logger.LogMessage fix

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumeratorWrapper.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.CoreAdapter/MSTestSettings.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/AssemblyEnumeratorTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/AssemblyEnumeratorWrapperTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/UnitTestDiscovererTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/UnitTestRunnerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestDiscovererTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs
Tied to #23. We were not honoring these settings in the app domains that discover/execute tests. Doing so now.
=> Honor settings in App domain

src/TestFramework/MSTest.Core/Assertions/Assert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs
Not sure if the tests provided are desired, so i can remove them if necessary.
=> fix #178 InstanceOfType on null value

src/TestFramework/MSTest.Core/Attributes/DynamicDataAttribute.cs, src/TestFramework/MSTest.Core/Interfaces/ITestDataSource.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/DynamicDataExMoreTests.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/DynamicDataExTests.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/TestDataSourceExTests.cs, test/UnitTests/MSTest.Core.Unit.Tests/Attributes/DynamicDataAttributeTests.cs
Removed Attribute from the namespace for DynamicDataAttribute
=> Removed Attribute from the namespace for DynamicDataAttribute

src/Adapter/MSTest.CoreAdapter/MSTestSettings.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs
=> Making EnableBaseClassTestMethodsFromOtherAssemblies as True by default

src/Adapter/MSTest.CoreAdapter/Constants.cs
=> Renaming TestProperty Ids to keep them consistent with platform.

src/TestFramework/MSTest.Core/Assertions/Assert.cs, src/TestFramework/MSTest.Core/Assertions/CollectionAssert.cs, src/TestFramework/MSTest.Core/Assertions/StringAssert.cs
Fix for #223.
Making all assert ctor's private and the classes sealed. We want users to extend from Assert.That instead and not by creating instances of the Assert class or extending from it.
=> Assertion fix up.

src/Adapter/PlatformServices.Desktop/Constants.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Utilities/DeploymentItemUtilityTests.cs
The deploymentItem Attribute was doing string comparison while deploying items, it was expecting "MSTestDiscoverer2" but test property name has been changed to "MSTestDiscoverer" in recent commit.
[(https://github.com/Microsoft/testfx/pull/221)]
=> Fix where Deployment Item attribute was not deploying items.

test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/UnitTestDiscovererTests.cs
The Unit Tests were failing on local machine due to static field dependency.Added that field in Test Cleanup.
=> Fix where Unit Tests were failing on local machine.

test/UnitTests/PlatformServices.NetCore.Unit.Tests/PlatformServices.NetCore.Unit.Tests.csproj
Dotnet Tests are failing because while running we are using older version of .NET sdk.
=> Upgrading version of .NET Sdk for fixing CI build

src/TestFramework/MSTest.Core/Internal/Helper.cs
The order of arguments for `ArgumentException` is not correct, as the constructor signature is 
```
public ArgumentException(string message, string paramName)
```
=> Arguments order for ArgumentException

src/Adapter/MSTest.CoreAdapter/Discovery/UnitTestDiscoverer.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/MSTestDiscoverer.cs, src/Adapter/MSTest.CoreAdapter/TestMethodFilter.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/UnitTestDiscovererTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodFilterTests.cs
TPv2 now exposes filtering support at discovery. 
Using that support via reflection (As filtering support is not exposed to IDiscoveryContext)
=> Adding filtering support at discovery

src/Adapter/MSTest.CoreAdapter/Discovery/UnitTestDiscoverer.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.resx, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.cs.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.de.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.es.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.fr.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.it.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ja.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ko.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.pl.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.pt-BR.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ru.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.tr.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.zh-Hans.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.zh-Hant.xlf
Put prefix of [MSTest][Discovery][<source>] for warning messages during discovery
Warning message as reported by the user https://developercommunity.visualstudio.com/content/problem/114611/visual-studio-20173-unit-test-do-not-appear-random.html -- does not have right contextual info.
=> Put prefix of [MSTest][Discovery][<source>] for warning messages during discovery

src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs
To help solve issues found in #249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/testfx/277)
=> Improve handling of Assert.Inconclusive

scripts/common.lib.ps1, src/Adapter/PlatformServices.Desktop/Utilities/AppDomainUtilities.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Utilities/AppDomainUtilitiesTests.cs
Issue: https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_workitems/edit/507887
Fix: Dont throw exception if target framework is ".NETPortable,Version=v4.5,Profile=Profile259"
=> Dont throw exception if target framework is ".NETPortable,Version=v4.5,Profile=Profile259"

test/UnitTests/PlatformServices.Universal.Unit.Tests/packages.config
This is part of #301 which could be accepted according to review. 
Since I still want to be able build project on my computer, I probably try to find way build project on my computer if needed and find way which will work both on your CI and on my PC.
=> Add missing Microsoft.Internal.TestPlatform.ObjectModel

scripts/Build.ps1, scripts/SetBuildNumber.ps1, scripts/build/TestFx.targets
https://github.com/Microsoft/testfx/issues/268
=> Update Fileversion for adapter and framework dlls

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumeratorWrapper.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.resx, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.cs.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.de.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.es.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.fr.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.it.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ja.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ko.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.pl.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.pt-BR.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.ru.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.tr.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.zh-Hans.xlf, src/Adapter/MSTest.CoreAdapter/Resources/xlf/Resource.zh-Hant.xlf, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/AssemblyEnumeratorWrapperTests.cs
Having indicate location of the assembly from which discovery happens allow developer reason about possible failures, and manually troubleshoot his configuration issues which cause asembly to fail
This allow simplify resolution of the issues like #295 and similar where it is not clear what exactly happens. For example when you run tests from multiple assemblies, like in VSTS CI build
=> Add information about which assembly failed to discover test into

src/TestFramework/MSTest.Core/Assertions/Assert.cs
The current message for the return value of the `Assert.ThrowsException` method is that `The type of exception expected to be thrown.` will be returned. But the method returns the exception instead. This patches corrects the documentation.
=> Corrected return message in `Assert.ThrowsException`.

src/TestFramework/MSTest.Core/GenericParameterHelper.cs, test/UnitTests/MSTest.Core.Unit.Tests/GenericParameterHelperTests.cs
See #361 for more details.
I make a static `Random` instance so that it would return a different value every time when calling `Next`. This can fix the different behavior between running and step-by-step debugging unit tests.
=> Make GenericParameterHelper's behavior same between running and debugging

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumeratorWrapper.cs
- Show the right error message on assembly load failures.
- Remove [SILVERLIGHT](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvset%2FAgile%2FTestPlatform%2FMSTest%2Fv1%2FMSAppContainerAdapter%2FCoreSystem%2FMSPhoneTestDiscoverer.cs&version=GBlab%2Fvsumain&_a=contents&line=196&lineStyle=plain&lineEnd=200&lineStartColumn=1&lineEndColumn=20) specific code.
**Before fix**
```
[MSTest][Discovery][D:\g\samples\Test Explorer fails to show tests\ClassLibrary.Tests\bin\Debug\ClassLibrary.Tests.dll] Failed to discover tests from assembly D:\g\samples\Test Explorer fails to show tests\ClassLibrary.Tests\bin\Debug\ClassLibrary.Tests.dll. Reason:The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
No test is available in D:\g\samples\Test Explorer fails …
```
=> Fix masking assembly load failure error message

Nuget.config, scripts/Build.ps1, scripts/PortableToFullPdb.ps1, scripts/SetBuildNumber.ps1, scripts/build/TestFx.targets, scripts/toolset/packages.config, src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumeratorWrapper.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/TestMethodFilter.cs, src/Package/MSTest.Internal.TestFx.Documentation.nuspec, src/Package/MSTest.TestAdapter.Dotnet.nuspec, src/Package/MSTest.TestAdapter.Enu.nuspec, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestAdapter.symbols.nuspec, src/Package/MSTest.TestFramework.enu.nuspec, src/Package/MSTest.TestFramework.nuspec, src/Package/MSTest.TestFramework.symbols.nuspec, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/UnitTestRunnerTests.cs
PR: 
* https://github.com/Microsoft/testfx/pull/328 (Jaya)
* https://github.com/Microsoft/testfx/pull/350 (Sarab)
* https://github.com/Microsoft/testfx/pull/372 (Sidd)
* https://github.com/Microsoft/testfx/pull/375 (Jaya)
* https://github.com/Microsoft/testfx/pull/337 (Jaya)
* https://github.com/Microsoft/testfx/pull/332 (Mayank)
* https://github.com/Microsoft/testfx/pull/382 (Satya)
=> Porting Fixes for 1.2.1

src/TestFramework/MSTest.Core/Attributes/DynamicDataAttribute.cs, src/TestFramework/MSTest.Core/Interfaces/ITestDataSource.cs, src/TestFramework/MSTest.Core/Resources/FrameworkMessages.Designer.cs, src/TestFramework/MSTest.Core/Resources/FrameworkMessages.resx, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.cs.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.de.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.es.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.fr.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.it.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.ja.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.ko.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.pl.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.pt-BR.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.ru.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.tr.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.zh-Hans.xlf, src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.zh-Hant.xlf, test/UnitTests/MSTest.Core.Unit.Tests/Attributes/DataRowAttributeTests.cs, test/UnitTests/MSTest.Core.Unit.Tests/Attributes/DynamicDataAttributeTests.cs
Fixes #351 
Added dynamic display name to DynamicDataAttribute
=> Dynamic data display name

src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.CoreAdapter/MSTestSettings.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs
Making test timeout configurable via runsettings
https://github.com/Microsoft/testfx-docs/pull/40
=> TestTimeout in RunSettings

TestFx.sln, src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumeratorWrapper.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/PlatformServices.Desktop/Services/DesktopTestSourceHost.cs, src/Adapter/PlatformServices.Interface/ITestSourceHost.cs, src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestSourceHost.cs, test/E2ETests/Smoke.E2E.Tests/CompatTests.cs, test/E2ETests/Smoke.E2E.Tests/Smoke.E2E.Tests.csproj, test/E2ETests/TestAssets/CompatTestProject/CompatTestProject.csproj, test/E2ETests/TestAssets/CompatTestProject/UnitTest1.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestSourceHostTests.cs
Temporarily we are restting appbase to point to location where adapter is getting picked up from. Then we reset the appbase later to point to test source location.
https://github.com/Microsoft/testfx/issues/384
=> Compatibility fix by resetting appbase

src/Adapter/MSTest.CoreAdapter/Constants.cs, src/Adapter/MSTest.CoreAdapter/Execution/TcmTestPropertiesProvider.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TcmTestPropertiesProviderTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj
**Description**:
VS IDE has support of association in test explorer. Currently this support is disabled for mstest v2. 
Support for mstest v2 will be enabled with this PR: https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/135489?_a=overview
When association is enabled for mstest v2 tests, user can associate mstest v2 tests with a test case and then run it via test plan flow.
In test plan flow, user might need to use tcm properties (like test case id, test run id, test plan id etc) in test method code. This PR contains changes to allow tcm properties to flow to test context.
**Validation Scenarios**:
Validated that for full framework and net core, tcm properties are properly passed to test context.
**Note**: In talk with @PBoraMSFT if RFC is required in mstest …
=> Enabling tcm properties flow to test context

Templates/CSharp/UWP/ProjectTemplates/CSharp/Windows UAP/Package.appxmanifest, Templates/VisualBasic/UWP/ProjectTemplates/VisualBasic/Windows UAP/Package.appxmanifest
This is needed to allow tcp connections on Xbox, SurfaceHub, etc
(Ported from 1.2.1 branch into master)
=> Add "privateNetworkClientServer" capability to UWP test templates

Templates/CSharp/Desktop/packages.config, Templates/CSharp/UWP/packages.config, Templates/VisualBasic/Desktop/packages.config, Templates/VisualBasic/UWP/packages.config, WizardExtensions/MSTestv2IntelliTestExtensionPackage/packages.config, WizardExtensions/MSTestv2UnitTestExtensionPackage/packages.config, scripts/build/TestFx.Settings.targets, scripts/build/TestFx.targets
Upgrading the version of VSSDK Build tools nuget, because the older one is incompatible with the latest VSSDK.
=> Upgrade VSSDK

src/TestFramework/MSTest.Core/Attributes/VSTestAttributes.cs
Attributes like Description should not inherit from TestPropertyAttribute, as eventually TestPropertyAttributes are treated as traits.
Fix for https://github.com/Microsoft/testfx/issues/478
Docs: Microsoft/testfx-docs#54
=> Description, WorkItem, CssIteration, CssProjectStructure should *NOT* be treated as traits.

src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs, src/TestFramework/Extension.Desktop/TestContext.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestContextImplTests.cs
When running a test project compiled for netstandard, and running in full framework throws the following error:
Error: System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Object> Microsoft.VisualStudio.TestTools.UnitTesting.TestContext.get_Properties()'..
It is expecting IDictionary`2<System.String,System.Object> hence causing run time error.
=> MissingMethodException Fix

src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs, src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs, src/TestFramework/Extension.Desktop/TestContext.cs, src/TestFramework/Extension.Shared/TestContext.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/PlatformServiceProviderTests.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestContextImplTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.0/ns10TestContextImplementationTests.cs
Ensured that the TestContext exposed is always IDictionary for backcompat reasons.
=> TestContext Properties type fixed to be IDictionary

src/Adapter/MSTest.CoreAdapter/MSTestSettings.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/UnitTestOutcomeHelperTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/ObjectModel/UnitTestResultTests.cs
Setting MSTest settings option MapNotRunnableToFailed to true by default. This will lead all tests that cannot be executed to result in failed outcome.
=> Setting MapNotRunnableToFailed to true by default

src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, src/TestFramework/MSTest.Core/Attributes/DataRowAttribute.cs, test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs, test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs, test/E2ETests/TestAssets/DataRowTestProject/DerivedClass.cs, test/UnitTests/MSTest.Core.Unit.Tests/Attributes/DataRowAttributeTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs
=> Datarow tests - support methods with optional parameters

src/TestFramework/MSTest.Core/Assertions/Assert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs
Fixed IsNotInstanceOfType failing when objected being asserted on is null
Null is not an instance of any type.
Issue #617
=> Fixed IsNotInstanceOfType failing when objected being asserted on is null

scripts/Build.ps1, scripts/common.lib.ps1
The main change is to try to find msbuild using the 'Current' version
instead of the '15.0' version.  The MSBuild team has stated that
'Current' will be used going forward to avoid a breaking change to the
path when the version revs.
Also necessary in this change was to drop the /toolsVersion flag from
msbuild.  It was passing 15.0 but that tools version is not recognized in the
current MSBuild.
Lastly, added the UWP.Support component as a required build component.
When the build script picks an instance of VS missing this feature, the build
will fail when trying to import Microsoft.Windows.UI.Xaml.CSharp.Targets.
=> Fix build script to work with VS2019

src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs, src/Adapter/PlatformServices.Desktop/Services/DesktopThreadOperations.cs, src/Adapter/PlatformServices.Interface/IThreadOperations.cs, src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10ThreadOperations.cs, src/TestFramework/MSTest.Core/Attributes/VSTestAttributes.cs
Because the timeout property is a plain int instead of an easily understandable TimeSpan, it's not clear what is the scale for timeout. The XMLDoc also helps nothing, it doesn't give anything new compared to what we already know from the code. And different part of .NET requires different scale (most millisecs, some part seconds - for example ADO.NET). 
For avoiding API break I updated the XML Doc to clear how the Timeout attribute work.
=> Add information for Timeout parameters/property of the scale.

src/Adapter/MSTest.CoreAdapter/Execution/TestAssemblyInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionRecorderWrapper.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.CoreAdapter/Extensions/TestResultExtensions.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/ObjectModel/TestMethod.cs, src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestElement.cs, src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestResult.cs, src/TestFramework/MSTest.Core/Attributes/VSTestAttributes.cs, src/TestFramework/MSTest.Core/Interfaces/ITestMethod.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestAssemblyInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/UnitTestRunnerTests.cs
This is a fix for #340 so that data collectors can get start/end events for individual execution of data driven tests. Also solves to allow the custom test execution extension to run a test multiple times and get multiple start/end events. 
Solving for #464 might be a better approach but seems like a much bigger change. 
One side effect of this change is ClassInitialize happens before any start event gets fired. IMO this is fine, it always seemed weird that this execution would be lumped into the first test that happened to execute. This also make it so ClassInitialize is now identical to ClassCleanup which doesn't get captured.
=> Record test start/end events for data driven tests

src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs
Fixing two bugs related to feature #143 
- Call base class cleanup even if top level test class doesn't have class cleanup
- Fix null ref when a class more than 1 level of inheritance has a class init/cleanup method.
=> Fix bugs in parent class init/cleanup logic

test/UnitTests/MSTest.Core.Unit.Tests/GenericParameterHelperTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/LogMessageListenerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestAssemblySettingsProviderTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodFilterTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TypeCacheTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/ExceptionExtensionsTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/TestCaseExtensionsTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/RunSettingsUtilitiesTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/ObjectModel/UnitTestElementTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/ObjectModel/UnitTestResultTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/RunConfigurationSettingsTests.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/AssemblyResolverTests.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestSourceHostTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.0/Services/ns10MSTestAdapterSettingsTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.0/ns10FileOperationsTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.3/Services/ns13MSTestSettingsProviderTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.3/ns13TraceListenerTests.cs, test/UnitTests/PlatformServices.Universal.Unit.Tests/Services/UniversalFileOperationsTests.cs
This PR is to fix some asserts in the TestPlatform.sln solution, the expected and actual are round the wrong way.
e.g.
`Assert.AreEqual(aggregator.RunContextAttachments.Count, 1, "RunContextAttachments List must have data.");`
should be
`Assert.AreEqual(1, aggregator.RunContextAttachments.Count, "RunContextAttachments List must have data.");`
Fixes #684
=> switch arguments for expected and actual in Assert.AreEquals in multiple tests

src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs, src/Adapter/PlatformServices.NetCore/Services/NetCoreTestContextImplementation.cs, src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs, src/TestFramework/Extension.Core/NetCoreTestContext.cs, src/TestFramework/Extension.Desktop/DesktopTestContext.cs, src/TestFramework/Extension.Shared/TestContext.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestContextImplTests.cs, test/UnitTests/PlatformServices.NetCore.Unit.Tests/Services/NetCoreTestContextImplementationTests.cs, test/UnitTests/PlatformServices.Shared.Unit.Tests/netstandard1.0/ns10TestContextImplementationTests.cs
Created Write() method.
Created some tests for the testing of newline and carriage return.
It's basically a carbon copy of the WriteLine implementation but calling the StringWriter.Write 
Resolves Issue:
#645
NOTE: I'm pretty inexperienced in C# i might struggle with advanced concepts if i've missed something.
=> Create Write() in TestContext

README.md
blog url migrated to devblogs.microsoft.com/devops/
Fixes #681
=> fix blog link

TestFx.sln, src/Adapter/MSTest.CoreAdapter/Extensions/TestCaseExtensions.cs, test/E2ETests/Automation.CLI/CLITestBase.cs, test/E2ETests/Automation.CLI/RunEventsHandler.cs, test/E2ETests/Smoke.E2E.Tests/Smoke.E2E.Tests.csproj, test/E2ETests/Smoke.E2E.Tests/TestProjectFSharpTests.cs, test/E2ETests/TestAssets/FSharpTestProject/FSharpTestProject.fsproj, test/E2ETests/TestAssets/FSharpTestProject/Tests.fs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/TestCaseExtensionsTests.cs
Initial failing test to aid with #682
=> Add FSharp E2E test

src/Adapter/Build/Desktop/MSTest.TestAdapter.props, src/Adapter/Build/NetCore/MSTest.TestAdapter.props, src/Adapter/Build/Universal/MSTest.TestAdapter.props
Without this change, files from this nuget package will be included
automatically when the consuming project is packing.
Example error when packing a project:
> C:\Program Files\dotnet\sdk\3.1.200\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5):
warning NU5100: The assembly 'content\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll' is
not inside the 'lib' folder and hence it won't be added as a reference
when the package is installed into a project. Move it into the 'lib'
folder if it needs to be referenced.
Additionally, add the contents to an ItemGroup so they can be seperated later if needed.
=> Change NuGet package to use `None` ItemGroup to copy files to output directory

src/TestFramework/MSTest.Core/Attributes/VSTestAttributes.cs
This PR fixes a wrong XML documentation comment for the `displayName` parameter on the `TestMethodAttribute` constructor.
=> Fixed documentation for the TestMethodAttribute

src/TestFramework/MSTest.Core/Assertions/CollectionAssert.cs
Added the information that collections' elements are compared using `object.Equals` method when a custom `IComparer` is not specified for the assertion.
=> Improve CollectionAssert.Are*Equal documentation (#711)

src/TestFramework/MSTest.Core/Attributes/VSTestAttributes.cs
To me it was unclear if it's once per `[TestClass]` or once per `[TestMethod]`.
=> enhance documentation on when the TestCleanup is executed

src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs
This avoids a bug where the base class initialize method gets called before every test method if the derived test class doesn't have a class initialize method.
=> Set IsClassInitializeExecuted=true after base class initialize

src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs
If the executing test has no test class cleanup method but a base class does and it fails, we hit a null ref exception because we try to use the method name of the executing test class cleanup but there isn't one.
=> Fix null ref bug when base class cleanup fails

src/TestFramework/MSTest.Core/Assertions/Assert.cs
Fixes https://github.com/MicrosoftDocs/feedback/issues/2943
@mairaw, would `<see cref="TypeName" />` be more suitable than `<c>TypeName</c>`?
I'm currently using `<c>` per your comment https://github.com/MicrosoftDocs/feedback/issues/2943#issuecomment-663307767
=> Fix XML doc comments (code -> c)

src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/MSTestSettings.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestExecutionManagerTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs
Assembly/Class cleanup errors mostly go unnoticed today (they get logged as a warning which for most automated CI systems means nobody sees the warning since it doesn't fail the test run). Even if the warning was surfaced, any output from these cleanups are discarded so it's harder to debug the issue.
There are two parts to this change:
- Add a setting to treat assembly/class cleanup warnings as errors to cause the test run to fail
- Log stdout & stderr captured during cleanup to help in debugging.
=> Add support to treat class/assembly warnings as errors

src/TestFramework/MSTest.Core/Assertions/Assert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs
Description:
An attempt on handling nullable bools for Assert.IsTrue() Assert.IsFalse()
Implemented these overrides and added some tests for them
`public static void IsTrue(bool? condition);`
`public static void IsTrue(bool? condition, string message);`
`public static void IsTrue(bool? condition, string message, params object[] parameters);`
`public static void IsFalse(bool? condition);`
`public static void IsFalse(bool? condition, string message);`
`public static void IsFalse(bool? condition, string message, params object[] parameters);`
Resolves #652
=> Assert.IsTrue() & False() to handle nullable bools

src/TestFramework/MSTest.Core/Assertions/StringAssert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/StringAssertTests.cs
Description:
Added StringComparison to StringAssert Contains, EndsWith & StartsWith
Added tests to test functionality
Added API comment on StringComparison Enum
Updated APIs to default to StringComparison.Ordinal 
Probably needs API documentation updates if this gets merged.
Resolves #154
=> Added StringComparison to StringAssert Contains(), EndsWith() & StartsWith()

scripts/test.ps1, src/Adapter/MSTest.CoreAdapter/Properties/AssemblyInfo.cs, test/UnitTests/PlatformServices.Desktop.Unit.Tests/Services/DesktopTestSourceHostTests.cs
Added functionality to MSTestAdapter from Test Platform, where we load only necessary types from assemblies.
=> Load specific types from adapter

README.md, src/Adapter/MSTest.CoreAdapter/Discovery/TypeEnumerator.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/TypeEnumeratorTests.cs
The `TypeEnumerator` class returned an `Attribute[]`, which cannot be casted to an `WorkItemAttribute[]`. Even though the method signature specified an `Attribute[]`, the mock was set up to return a `WorkItemAttribute[]` array, which causes the test to pass but the `as` conversion to fail at runtime.
=> BugFix: WorkItemAttribute not extracted 

scripts/build/TestFx.Versions.targets, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/Properties/AssemblyInfo.cs, src/Adapter/MSTest.CoreAdapter/Properties/TypesToLoadAttribute.cs, src/Adapter/PlatformServices.Desktop/packages.config, src/Adapter/PlatformServices.Interface/packages.config, src/Adapter/PlatformServices.Portable/packages.config, test/ComponentTests/PlatformServices.Desktop.Component.Tests/packages.config, test/E2ETests/Automation.CLI/CLITestBase.cs, test/E2ETests/Automation.CLI/packages.config, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/packages.config, test/UnitTests/PlatformServices.Desktop.Unit.Tests/packages.config, test/UnitTests/PlatformServices.Portable.Unit.Tests/packages.config, test/UnitTests/PlatformServices.Universal.Unit.Tests/packages.config
TestFx updated to implement changes in https://github.com/microsoft/vstest/pull/2674; this should fix the compatibility issue introduced in https://github.com/microsoft/vstest/pull/2537 and https://github.com/microsoft/testfx/pull/739.
=> Fixed TypesToLoadAttribute compatibility

src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs
TypeCache class has testAssemblyInfoCache and classInfoCache data members of type Dictionary<>.
Updates where under the lock, but reads were not, which sometimes causes the following error:
``
An exception occurred while invoking executor 'executor://mstestadapter/v2': One or more errors occurred. (Object reference not set to an instance of an object.) while running test
``
Stack:
```
---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TypeCache.GetClassInfo(TestMethod testMethod)
at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Executi …
```
=> Fixed concurrency issues in the TypeCache class.

Nuget.config, scripts/Build.ps1, scripts/build/TestFx.Versions.targets, src/Adapter/MSTest.CoreAdapter/Extensions/TestCaseExtensions.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/ObjectModel/TestMethod.cs, src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestElement.cs, src/Adapter/PlatformServices.Desktop/packages.config, src/Adapter/PlatformServices.Interface/packages.config, src/Adapter/PlatformServices.Portable/packages.config, src/Adapter/PlatformServices.Universal/project.json, src/Package/MSTest.TestAdapter.Enu.nuspec, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestFramework.enu.nuspec, src/Package/MSTest.TestFramework.nuspec, src/TestFramework/Extension.UWP/project.json, test/ComponentTests/PlatformServices.Desktop.Component.Tests/packages.config, test/E2ETests/Automation.CLI/Automation.CLI.csproj, test/E2ETests/Automation.CLI/CLITestBase.cs, test/E2ETests/Automation.CLI/packages.config, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/packages.config, test/UnitTests/PlatformServices.Desktop.Unit.Tests/packages.config, test/UnitTests/PlatformServices.NetCore.Unit.Tests/PlatformServices.NetCore.Unit.Tests.csproj, test/UnitTests/PlatformServices.Portable.Unit.Tests/packages.config, test/UnitTests/PlatformServices.Universal.Unit.Tests/packages.config
- Updated the Test Platform version to 16.9.0-preview-20210129-05.
- Refactored the adapter to conform to the new implementation.
- Fixed some warnings.
- Fixes #748
=> ManagedName and backward compatibility fixes.

src/Adapter/MSTest.CoreAdapter/Helpers/DictionaryHelper.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Helpers/DictionaryHelperTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTest.CoreAdapter.Unit.Tests.csproj, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/packages.config
Merge session and source level settings safely. Linq.Concat will throw "key has already been added" exception when there are duplicates. This add a helper method that will merge the dictionaries safely.
=> Merge settings safely

src/Adapter/MSTest.CoreAdapter/MSTestExecutor.cs, src/Adapter/PlatformServices.Desktop/Services/DesktopAdapterTraceLogger.cs, src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TraceLogger.cs
When running on .NET Core forward logs to EqtTrace to be written into diag log when it is enabled.
=> Forward logs to EqtTrace

src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestElement.cs
Fixes #793
Partially reverts changes introduced in https://github.com/microsoft/testfx/pull/766
=> Unit test display name issue fixed.

src/TestFramework/MSTest.Core/Assertions/StringAssert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/StringAssertTests.cs
Similar to https://github.com/microsoft/testfx/commit/5dafe82fa2975cf4f7792c92176ef96b2d034e43
=> Fix StackOverflowException in StringAssert.DoesNotMatch

TestFx.sln, src/Adapter/Build/WinUI/MSTest.TestAdapter.props, src/Adapter/Build/WinUI/MSTest.TestAdapter.targets, src/Adapter/PlatformServices.Shared/netstandard1.0/ns10RecursiveDirectoryPath.cs, src/Adapter/PlatformServices.Shared/netstandard1.3/Services/ns13TestDeployment.cs, src/Adapter/PlatformServices.WinUI/Friends.cs, src/Adapter/PlatformServices.WinUI/PlatformServices.WinUI.csproj, src/Adapter/PlatformServices.WinUI/Properties/AssemblyInfo.cs, src/Adapter/PlatformServices.WinUI/Resources/README.txt, src/Adapter/PlatformServices.WinUI/Services/WinUIAdapterTraceLogger.cs, src/Adapter/PlatformServices.WinUI/Services/WinUIFileOperations.cs, src/Adapter/PlatformServices.WinUI/Services/WinUITestSource.cs, src/Package/MSTest.TestAdapter.Enu.nuspec, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestAdapter.symbols.nuspec, src/Package/MSTest.TestFramework.enu.nuspec, src/Package/MSTest.TestFramework.nuspec, src/Package/MSTest.TestFramework.symbols.nuspec, src/TestFramework/Extension.WinUI/Extension.WinUI.csproj
This adds a new adapter TFM (net5.0-windows10.0.18362.0), which is used for WinUI projects.
Complemented by https://github.com/microsoft/vstest/pull/2849
=> Added WinUI TestAdapter.

src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.resx
I have a dump that throws access violation exception in native code and the test run fails with: 
`An exception occurred while invoking executor 'executor://mstestadapter/v2': Object reference not set to an instance of an object.`
I looked through the code and the only way I can get this result is when ex would be null in the handler. Otherwise it fails with different error, either from the asserts in the `StackTraceHelper` methods or in upstream error handlers.
=> Handle possible null ref in error handler

src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs
Reverting an unintended breaking change in reflection.
Thank you, @azchohfi, for reporting it; this makes #824 unnecessary.
=> Reverting an unintended breaking-change.

scripts/Build.ps1, src/Package/MSTest.Internal.TestFx.Documentation.nuspec, src/Package/MSTest.TestAdapter.Enu.nuspec, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestAdapter.symbols.nuspec, src/Package/MSTest.TestFramework.enu.nuspec, src/Package/MSTest.TestFramework.nuspec, src/Package/MSTest.TestFramework.symbols.nuspec
- Replaced LICENSE files in NuGet packages with a license expression, and added a licenseUrl.
- Fixes #804
=> Switching to use a LICENSE expression instead of a file

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.CoreAdapter/Extensions/TestCaseExtensions.cs, src/Adapter/MSTest.CoreAdapter/Helpers/DataSerializationHelper.cs, src/Adapter/MSTest.CoreAdapter/ObjectModel/TestMethod.cs, src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestElement.cs, src/Adapter/PlatformServices.Desktop/AssemblyResolver.cs, test/E2ETests/Automation.CLI/CLITestBase.common.cs, test/E2ETests/Automation.CLI/RunConfiguration.cs, test/E2ETests/DiscoveryAndExecutionTests/DataRowTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Extensions/AssertionExtensions.cs, test/E2ETests/DiscoveryAndExecutionTests/Utilities/TestCaseFilterFactory.cs, test/E2ETests/TestAssets/DataRowTestProject/DerivedClass.cs
- Fixed a bug causes that types of some `ITestDataSource` data were lost during their transfer between application domain boundaries.
- Fixed a bug preventing test discovery when non-serializable values are provided with `ITestDataSource`.
- Fixed #844
=> Fixed serialization issues with ITestDataSource.

scripts/Build.ps1, src/Adapter/MSTest.CoreAdapter/Helpers/DataSerializationHelper.cs
=> Fixed DataSource deserialization.

eng/Versions.props, src/TestFramework/Extension.WinUI/UITestMethodAttribute.cs
The dispatcher has moved to a new namespace.
Without this change I can't really move to 0.8.0, since I can't verify test runs.
=> Upgraded winui to 0.8.0

scripts/Install-WindowsSDK.ps1, scripts/PortableToFullPdb.ps1, scripts/verify-sign.ps1, scripts/write-release-notes.ps1, src/TestFramework/Extension.WinUI/Extension.WinUI.csproj, test/E2ETests/Automation.CLI/CLITestBase.common.cs
* Added missing framework references
* Updated license headers on PowerShell files
* Included a script to install required Windows SDK
=> Added missing framework references for WinUI

src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs
The initial issue reported in #799 was related to test suites failing to execute completely in Visual Studio because sometimes, the cleanup phase was throwing with messages like this:
```
An exception occurred while invoking executor 'executor://mstestadapter/v2': The parameter cannot be null or empty.
Parameter name: message
Stack trace:
at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.LogCleanupResult(ITestExecutionRecorder testExecutionRecorder, RunCleanupResult result)
at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunCleanup(ITestExecutionRecorder …
```
=> Fixes #799 by testing logged messages against "null or whitespace" instead of "null or empty"

src/Adapter/PlatformServices.Desktop/Deployment/AssemblyLoadWorker.cs, src/Adapter/PlatformServices.Desktop/Utilities/DesktopAssemblyUtility.cs, src/Adapter/PlatformServices.Desktop/Utilities/DesktopDeploymentUtility.cs
When there are dependencies that the project installs, but they would only resolve via a reference that is located in GAC (e.g. System.ValueTuple via netstandard) then the deployment into Out folder would ignore it. 
If user then installs a version that is newer than what is in GAC it will get into their assembly redirects, but won't get copied into Out folder, resulting into TypeLoad exception for tests with DeploymentItem attribute. 
This change fixes the resolver to look through all the dependencies including GAC dependencies and then copy over only the ones that are found in the bin folder, because ultimately Out should be just a subset (or the same) as the contents in bin folder. 
Looking through GAC assemblies does not seem to add significant overhead the whole resolve is under …
=> Resolve dependencies from GAC

scripts/Build.ps1, scripts/build/TestFx.Sign.props, scripts/build/TestFx.Sign.targets, scripts/build/TestFx.props, scripts/build/TestFx.targets, scripts/common.lib.ps1, scripts/verify-sign.ps1, src/Adapter/PlatformServices.NetCore/PlatformServices.NetCore.csproj, src/Adapter/PlatformServices.WinUI/PlatformServices.WinUI.csproj, src/TestFramework/Extension.WinUI/Extension.WinUI.csproj
- Fixes #948 
- Adds signature verification for assemblies
=> Fixed missing strong-name and Authenticode signatures

eng/Versions.props
Fixing [this](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/111969/alert/4311839?typeId=537149).
Changing parameter shows version of `Microsoft.NETCore.UniversalWindowsPlatform` package which contains vulnerable dll.
=> Fix vulnerability CVE-2017-0247

src/Package/MSTest.TestAdapter.Enu.nuspec, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestAdapter.symbols.nuspec
Fix for incorrect Microsoft.TestPlatform.AdapterUtilities.dll for net45 target (#980)
=> Fix for incorrect Microsoft.TestPlatform.AdapterUtilities.dll for net45 target (#980)

src/TestFramework/MSTest.Core/Assertions/Assert.cs
Fixes #1004 
When adding these attributes, I did hesitate on the IsTrue/IsFalse overloads accepting nullable bools, because it does look odd to see
`[DoesNotReturnIf(true)] bool? condition` 
right next to a check like
`if (condition == true || condition == null)`
knowing that for both `true` and `null` the method will not return - but only for `true` will the nullability analysis kick in. Passing `null` will result in the call site still not knowing if the method returns or not so the user will still have to perform their own additional check.
But my thought process was that the attribute is still accurate and still helps. `[DoesNotReturnIf(true)]` means just that - the method does not return if the parameter exactly matches `true`. It does not say whether or not the method returns if …
=> Add DoesNotReturnIf to Assert.IsTrue/Assert.IsFalse and DoesNotReturn to Assert.Fail

src/TestFramework/MSTest.Core/Attributes/Lifecycle/Cleanup/ClassCleanupAttribute.cs
Attribute enum parameters must be constant. The parameter "cleanupBehavior" can't be of type Nullable<ClassCleanupBehavior> as it is not possible to create a constant attribute parameter for it.
=> Remove nullability option from cleanupBehavior parameter

src/Adapter/MSTest.CoreAdapter/Execution/UnitTestRunner.cs
Fix cleanup for DataRow, to remove tests from the dictionary by using the same name (DisplayName) as what they were added. This affects DataRow tests and probably any test that uses DisplayName. Because then the entry in the hashmap and the key used to remove it (MethodName) are not the same.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1448552
=> Fix EndOfClass cleanup for DataRow

src/TestFramework/Extension.UWP/UITestMethodAttribute.cs, src/TestFramework/Extension.WinUI/UITestMethodAttribute.cs
Changed the argument of `ITestMethod` invocation call in `UITestMethod` from an empty array to null.
`DataRowAttribute` and other data driven testing [depends on the argument being null](https://github.com/microsoft/testfx/blob/aad795f4321d640caa4ed0db846d374d10b0362e/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs#L113-L116) to inject the parameters from data source or data row. Sending an empty array into `ITestMethod.Invoke` breaks this mechanism. 
_There is no existing test for these two attributes, thus not tests are updated._
=> [UITestMethod] should invoke test method with null

scripts/Build.ps1, scripts/common.lib.ps1, src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumerator.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Discovery/AssemblyEnumeratorTests.cs
Reflection only loading for executable files was preventing us to discover and run tests because of different attribute reading mechanism. Now loading assemblies entirely, regardless of type.
- Fixes #1019
=> Fixed test run executable files.

src/Adapter/PlatformServices.Shared/netstandard1.3/Services/ns13ThreadSafeStringWriter.cs
Replace instance lock with static lock, because there can be multiple different ThreadSafeStringWriters writing into the same async context. Reduce the locking only to state initialization and dictionary lookups and edits, but don't hold the lock over StringBuilder operations. 
Add a wrapper for StringBuilder that locks on every method on the instance level, so when two threads get the same instance of StringBuilder then will sync together, but they won't sync with other threads that have different string builder.
Fix #1063
=> Fix write conflicts in parallel output

src/Adapter/MSTest.CoreAdapter/Execution/StackTraceHelper.cs
Address thread-safety issue https://github.com/microsoft/testfx/issues/1053 by initializing the static field StackTraceHelper.typesToBeExcluded statically instead of on demand.
=> Static init of StackTraceHelper.typesToBeExcluded

scripts/Build.ps1, src/Package/MSTest.nuspec
Our consumers can simplify their test project by depending on `MSTest` package instead of `MSTest.TestAdapter`, `MSTest.TestFramework` and `Microsoft.NET.Test.Sdk` packages. 
This meta package will guarantee all the parts are compatible.
[This](https://github.com/microsoft/testfx/files/8540471/MSTestProjects.zip) solution can be used to verify.
=> Added MSTest meta-package

src/Adapter/MSTest.CoreAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.CoreAdapter/MSTest.CoreAdapter.csproj, src/Adapter/MSTest.CoreAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.CoreAdapter/Resources/Resource.resx, test/E2ETests/DiscoveryAndExecutionTests/TestDataSourceExtensibilityTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Utilities/CLITestBase.discovery.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/CustomTestExTests.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/DynamicDataDiscoveryBailOutTests.cs, test/E2ETests/TestAssets/FxExtensibilityTestProject/FxExtensibilityTestProject.csproj, test/E2ETests/TestAssets/FxExtensibilityTestProject/TestDataSourceExTests.cs
IDataSource tests don't support duplicate test names, or unserializable objects. Added bail out paths and warnings for those scnerios.
=> Added more fail paths for data serialization.

src/TestFramework/MSTest.Core/Assertions/Assert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/StringAssertTests.cs
Fixes https://github.com/dotnet/sdk/issues/25373
=> Prevent format exceptions when parameters array is empty

src/TestFramework/MSTest.Core/Assertions/Assert.cs, src/TestFramework/MSTest.Core/Assertions/CollectionAssert.cs, src/TestFramework/MSTest.Core/Assertions/StringAssert.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs, test/UnitTests/MSTest.Core.Unit.Tests/Assertions/StringAssertTests.cs
Update the assertion message construction order to ensure user message is built first (user message could fail with FormatException) and then include this user message in our messages. This switch of order ensure we will never throw FormatException because our built message becomes an invalid format composite.
Fixes https://github.com/dotnet/sdk/issues/25373
=> Ensure assertions do not fail with FormatException

src/Adapter/PlatformServices.Desktop.Legacy/Utilities/DesktopDeploymentUtility.cs, src/Adapter/PlatformServices.Desktop/Utilities/DesktopDeploymentUtility.cs, src/Adapter/PlatformServices.NetCore/Utilities/NetCoreDeploymentUtility.cs
I ran into the issue in #678 today, so we wanted to contribute a fix for it. I'm happy to revise if I've not followed the contributor guidelines.
- Fixes #678
=> TestResults folder names are now cross platform compatible, as per #678

src/Adapter/MSTest.CoreAdapter/Execution/TestAssemblyInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.CoreAdapter/Extensions/ExceptionExtensions.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestAssemblyInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTest.CoreAdapter.Unit.Tests/Extensions/ExceptionExtensionsTests.cs
Use the same informative message for all XXXInitialize and XXXCleanup methods whatever the kind of exception. We used to have a simpler handling for Assert exceptions that was removing the information about the method throwing the exception.
Fixes #1142 and fixes [AB#1543904](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1543904)
=> Better messages for XXXInitialize and XXXCleanup

scripts/common.lib.ps1, test/E2ETests/Automation.CLI/CLITestBase.common.cs, test/E2ETests/Automation.CLI/CLITestBase.e2e.cs
Stop relying on build script to update a constant defined in E2E test and instead reads the version from the Versions.props file.
=> Find TP package version using Versions.props

scripts/Build.ps1, scripts/build/TestFx.props, scripts/build/TestFx.targets
Fixes #1051 
Example when running locally:
Obviously, version number will be the correct ones when coming from CI.
=> Improve assembly versions and available metadata

scripts/Build.ps1
This step can no longer be run and downloaded SDK is outdated. Besides, an external script already exists for the same action (and it up-to-date).
=> Remove unused build step

TestFx.sln, test/E2ETests/DiscoveryAndExecutionTests/NoNamespaceTests.cs, test/E2ETests/TestAssets/HierarchyProject/ClassWithNamespace.cs, test/E2ETests/TestAssets/HierarchyProject/ClassWithNoNamespace.cs, test/E2ETests/TestAssets/HierarchyProject/HierarchyProject.csproj
Actual fix lays on Test Platform side as we are simply using an API they provide. We still want to add some tests as safetynet against regression.
Fixes #889
=> Fix issue causing null ref when test class has no namespace

src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
Fixes the issue #1180 that was preventing to have exactly 2 arrays as argument of DataRowAttribute ctor because the compiler was considering the second array as the params array and not as a first item of it.
=> Refactor available ctors for DataRowAttribute

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, test/E2ETests/Smoke.E2E.Tests/SuiteLifeCycleTests.cs
Fix: https://github.com/microsoft/testfx/issues/1328
=> Remove class/assembly initialization messages from logs.

src/TestFramework/TestFramework.Extensions/AppModel.cs, src/TestFramework/TestFramework.Extensions/Attributes/DeploymentItemAttribute.cs, src/TestFramework/TestFramework.Extensions/Attributes/UWP_UITestMethodAttribute.cs, src/TestFramework/TestFramework.Extensions/Attributes/WinUITestTargetAttribute.cs, src/TestFramework/TestFramework.Extensions/Attributes/WinUI_UITestMethodAttribute.cs, src/TestFramework/TestFramework.Extensions/PrivateObject.cs, src/TestFramework/TestFramework.Extensions/PrivateType.cs, src/TestFramework/TestFramework.Extensions/Properties/AssemblyInfo.cs, src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net462/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net462/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net6.0-windows10.0.18362.0/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net6.0-windows10.0.18362.0/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/uap10.0.16299/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/PublicAPI/uap10.0.16299/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/RuntimeTypeHelper.cs, src/TestFramework/TestFramework.Extensions/TestContext.cs, src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj, src/TestFramework/TestFramework/Internal/DebugEx.cs, src/TestFramework/TestFramework/Internal/Helper.cs, src/TestFramework/TestFramework/Internal/StringEx.cs
=> Enable nullable for TestFramework.Extensions

test/E2ETests/Automation.CLI/CLITestBase.common.cs
It seems that the solution in place isn't working on all machines for some reason (unknown) so switching over to `GetExecutingAssembly` which seems to be working correctly on machines were current solution is broken.
=> Update testfx repo detection mechanism

src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Shipped.txt, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework.Extensions/TestContext.cs
Fixes #1376
Also, enforces the non-nullability of the `TestContext`.
=> Fix TestContext nullabilities

src/Adapter/Build/Desktop/MSTest.TestAdapter.props, src/Adapter/Build/Desktop/MSTest.TestAdapter.targets, src/Adapter/Build/Net6/MSTest.TestAdapter.props, src/Adapter/Build/Net6/MSTest.TestAdapter.targets, src/Adapter/Build/NetCore/MSTest.TestAdapter.props, src/Adapter/Build/Universal/MSTest.TestAdapter.props, src/Adapter/Build/Universal/MSTest.TestAdapter.targets, src/Package/MSTest.TestAdapter.nuspec, src/Package/MSTest.TestAdapter.symbols.nuspec
=> Rename folder containing localization dlls in MSTest.TestAdapter NuGet package

src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/E2ETests/Smoke.E2E.Tests/Parameterized tests/DataRowTests.cs, test/E2ETests/TestAssets/DataRowTestProject/DataRowTests_OverrideGetDisplayName.cs, test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
fix: https://github.com/microsoft/testfx/issues/1336
=> Allow to override GetDisplayName method from DataRowAttribute

src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestElement.cs, test/E2ETests/DiscoveryAndExecutionTests/TestId.LegacyStrategy.cs, test/UnitTests/MSTestAdapter.UnitTests/ObjectModel/UnitTestElementTests.cs
In addition to the fix on Test Platform side, I have realized that we don't store the ID strategy property so we always restore it as the new strategy which is causing some issue for inner results (in case of Legacy strategy).
Relates to #1149
=> Ensure test ID strategy is saved as property

test/E2ETests/DiscoveryAndExecutionTests/DiscoverInternalsTests.cs, test/E2ETests/DiscoveryAndExecutionTests/FSharpTestProjectTests.cs, test/E2ETests/DiscoveryAndExecutionTests/OutputTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Parameterized tests/DataExtensibilityTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Parameterized tests/DataRowTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Parameterized tests/DataSourceTests.cs, test/E2ETests/DiscoveryAndExecutionTests/Parameterized tests/DynamicDataTests.cs, test/E2ETests/DiscoveryAndExecutionTests/TestId.DefaultStrategy.cs, test/E2ETests/DiscoveryAndExecutionTests/TestId.DisplayNameStrategy.cs, test/E2ETests/DiscoveryAndExecutionTests/TestId.FullyQualifiedStrategy.cs, test/E2ETests/DiscoveryAndExecutionTests/TestId.LegacyStrategy.cs, test/E2ETests/DiscoveryAndExecutionTests/Utilities/CLITestBase.discovery.cs, test/E2ETests/TestAssets/OutputTestProject/UnitTest1.cs, test/E2ETests/TestAssets/OutputTestProject/UnitTest2.cs
CI is often failing on test `OutputIsNotMixedWhenAsyncTestsRunInParallel`, try to refactor the test to fix it.
=> Fix output E2E tests

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs, src/TestFramework/TestFramework/Resources/FrameworkMessages.resx, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs
=> Remove Assert.AreEqual/AreNotEqual overloads with object object

src/Adapter/MSTestAdapter.PlatformServices/Services/TestSourceHost.cs
Fixes #1437 
Something changed in the way the extensions dll is being resolved. It's not clear if that's the change of infra, the merging of projects, the bump of target frameworks (as happened on TP) or something else. This seems to be the best fix but I will ask for a full vendor testing round to ensure this won't break non-automated tests.
=> Add parent domain assembly resolver for netfx

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs, test/E2ETests/Smoke.E2E.Tests/SuiteLifeCycleTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs
- Ensures Trace/Debug/Console logs calls inside `ClassCleanup `and `AssemblyCleanup `methods are correctly collected.
- Ensures that failed `ClassCleanup `or `AssemblyCleanup` is attached to last test run
Fixes #1448
=> Fix class/assembly cleanups log collect and attachment

src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
During our internal tests we had the following issue raised:
```An exception occurred while invoking executor 'executor://mstestadapter/v2': The given key 'Microsoft.CodeCoverage.Core.Tests.Configurations.SimpleExpressionTests' was not present in the dictionary. Stack trace: at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.ClassCleanupManager.MarkTestComplete(TestMethodInfo testMethodInfo, TestMethod testMethod, Boolean& shouldRunEndOfClassCleanup, Boolean& shouldRunEndOfAssemblyCleanup) at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunRequiredCleanups(ITestContext testContext, TestMethodInfo testMethodInfo, TestMethod testMethod, UnitTestResult[] results) …
```
=> Fix some race condition issue

src/Adapter/MSTestAdapter.PlatformServices/Deployment/AssemblyLoadWorker.cs, src/Adapter/MSTestAdapter.PlatformServices/Utilities/AppDomainUtilities.cs
When setuping DeploymentEnabled, MSTest fails with `An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`. After investigation, it seems related to a chage introduced in 2.2.7 where some logs were added, adding a dependency to this dll which cannot be resolved by the custom assembly resolver.
The special appdomain and resolver are meant to isolate and detect dll coming from the user bin folder to enable automatic copy of these dlls so we cannot easily fix the resolver as it could lead to conflicts or missing dlls copied. Simplest solution is to remove the log …
=> Fix issue cannot load Microsoft.TestPlatform.CoreUtilities

azure-pipelines.yml
Allows to avoid the un-needed `xUnit` step.
=> Update CI testResultsFormat to vstest

src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/Adapter/MSTest.TestAdapter/PublicAPI/PublicAPI.Shipped.txt, src/Adapter/MSTest.TestAdapter/PublicAPI/PublicAPI.Unshipped.txt, test/UnitTests/MSTestAdapter.UnitTests/Discovery/UnitTestDiscovererTests.cs, test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs
Addresses #1544 by adding a setting TreatDiscoveryWarningsAsErrors which will report discovery warnings as errors to loggers.
=> Add TreatDiscoveryWarningsAsErrors setting

src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs, src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Shipped.txt, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
Rework DataRow to remove the limit on argument count while still allowing to pass arrays.
Fixes #1503 and [AB#1807559](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1807559)
=> Remove DataRowAttribute argument count limitation

src/Adapter/MSTestAdapter.PlatformServices/Utilities/AssemblyUtility.cs
Force loading the resource assembly into the current domain so that we can get the resource strings even when the custom assembly resolver kicks in.
This should not be required based on the algorithm followed during the [satellite assembly resolution](https://learn.microsoft.com/dotnet/core/extensions/package-and-deploy-resources#net-framework-resource-fallback-process)   BUT for some unknown reason the point 10 is not working as explained. Satellite resolution should fallback to the `NeutralResourcesLanguageAttribute` that we set to `en` but don't resulting in a FileNotFoundException.
See https://github.com/microsoft/testfx/issues/1598 for the error and https://github.com/microsoft/vstest/pull/4150 for the idea of the fix.
Fixes #1598
=> Fix assembly resolution error

src/Adapter/MSTestAdapter.PlatformServices/AssemblyResolver.cs
Fixes #1598
@avivanoff Now this is correctly fixing both of your repros.
=> Fix issue/crash with deployment items and disabled app domains

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
Fixes #1146
There is no integration test because it seems that using translation layer, I cannot reproduce the exact same case as what is done with command line. But I was able to validate manually that the change is fixing the issue.
I will keep the PR open until next week to validate manually the artifact and try one more time to add the integration test as it is worrying me to not be able to reproduce the issue automatically.
=> Fix parallel output isolation

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
Avoid unlikely bug where test is marked as inconclusive but then fails, and the duration is captured from the first stop of the stopwatch that happened in the inconclusive branch.
There is no issue to link to, I just noticed this when digging in code.
=> Don't stop

Directory.Build.props, Directory.Build.targets, azure-pipelines.yml, eng/Analyzers.props, eng/Publishing.props, eng/Versions.props, samples/FxExtensibility/FxExtensibility.csproj, src/Adapter/Build/Desktop/MSTest.TestAdapter.props, src/Adapter/Build/Desktop/MSTest.TestAdapter.targets, src/Adapter/Build/Net6/MSTest.TestAdapter.props, src/Adapter/Build/Net6/MSTest.TestAdapter.targets, src/Adapter/Build/Net6/MSTest.TestFramework.targets, src/Adapter/Build/NetCore/MSTest.TestAdapter.props, src/Adapter/Build/Universal/MSTest.TestAdapter.props, src/Adapter/Build/Universal/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/TestFramework/TestFramework/TestFramework.csproj, test/Directory.Build.targets, test/IntegrationTests/MSTest.IntegrationTests/MSTest.IntegrationTests.csproj, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests.csproj, test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/PlatformServices.Desktop.IntegrationTests.csproj, test/IntegrationTests/TestAssets/SampleFrameworkExtensions/SampleFrameworkExtensions.csproj, test/IntegrationTests/TestAssets/TestProject/TestProjectForDiscovery.csproj, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj, test/UnitTests/MSTestAdapter.UnitTests/MSTestAdapter.UnitTests.csproj, test/UnitTests/TestFramework.UnitTests/TestFramework.UnitTests.csproj, test/Utilities/Automation.CLI/Automation.CLI.csproj
See commits for description of changes. **Review by commits**.
=> Code clean-up 

Directory.Build.props, eng/MSTestRunner/MSTestRunner.targets, eng/Versions.props
This trick allows me to shortcircuit arcade that would force having one of the predefined test framwork when we want to use our local custom test framework to test MSTest.
=> Use custom runner that calls vstest runner

src/Platform/Microsoft.Testing.Platform/Logging/ILogger.cs, src/Platform/Microsoft.Testing.Platform/Logging/LogLevel.cs, src/Platform/Microsoft.Testing.Platform/Logging/LoggingExtensions.cs
We will share named pipe infra to a different project and we don't want to expose contracts from there. 
At the moment all IPC is internal and it's using logging that's exposed, this update will let us to internalize the type definitions to avoid to expose the interface in the other projects.
=> Housekeeping for named pipe infrastructure sharing

TestFx.sln, src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/IntegrationTests/MSTest.IntegrationTests/ClsTests.cs, test/IntegrationTests/TestAssets/ClsTestProject/ClsTestProject.csproj, test/IntegrationTests/TestAssets/ClsTestProject/MyTests.cs
=> Fix DataRowAttribute to be cls compliant

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, test/IntegrationTests/TestAssets/FSharpTestProject/Tests.fs
=> Workaround issue with managed type name utility

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/testsbaseline.txt
=> MSTEST0006: Avoid '[ExpectedException]'

docs/mstest-runner-protocol/001-protocol-intro.md, docs/mstest-runner-protocol/002-protocol-vstest.md, docs/mstest-runner-protocol/003-protocol-ide-integration-extensions.md
Adds documentation about the MSTest Runner's protocol, what RPC messages are supported and what is the shape of the payloads.
=> Add protocol documentation

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/UseParallelizeAttributeAnalyzer.cs
Follow-up from internal dogfood, when team have many test projects, having this rule as warning by default leads to headache and doesn't well align with us trying to follow semantic versioning. So we decided to downgrade the rule default severity to `Info` and we will bump it back to `Warning` as part of v4.
=> MSTEST0001: Set default severity to Info

src/Adapter/MSTest.TestAdapter/Execution/ExceptionHelper.cs
We detected the issue on Linux
=> TrimStackTrace should handle empty stacktrace

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs, src/Platform/Microsoft.Testing.Platform/Extensions/CompositeExtensionsFactory.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcessHandler.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs, src/Platform/Microsoft.Testing.Platform/Logging/LoggerFactoryExtensions.cs, src/Platform/Microsoft.Testing.Platform/Messages/PropertyBag.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/OutputDeviceManager.cs, src/Platform/Microsoft.Testing.Platform/Requests/ConsoleTestExecutionRequestFactory.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/SerializerUtilities.cs, src/Platform/Microsoft.Testing.Platform/TestHostControllers/TestHostControllersManager.cs, src/Platform/Microsoft.Testing.Platform/TestHostOrcherstrator/TestHostOrchestratorManager.cs
`ArgumentGuard` is made to check only arguments, for internal state, we should use `ApplicationStateGuard` instead.
=> Ensure proper usage of Guard helpers

src/Adapter/Build/Common/MSTest.TestAdapter.targets, src/Adapter/Build/NetWithWinUI/MSTest.TestAdapter.targets
`Include` should be the name of the dll without the .dll suffix and `HintPath` should be the full path.
Relates to #2173
=> Fix setup of MSBuild Reference item entry

src/Adapter/Build/NetWithWinUI/MSTest.TestAdapter.targets, src/Adapter/Build/NetWithWinUI/MSTest.TestFramework.targets
When introducing net8.0 and net9.0, we broke the referencing of the specifically built dll. Instead of referencing the same dll multiple times, I have decided to update the target to copy the net6 one.
I will investigate separately the complexity and benefit of multi-targeting the netX-windowsY entries.
Fixes #2188 
@abdes you should be able to modify the locally extracted NuGet package to apply the same change if you want to do some manual double checking. It works for me on the project shared in the linked issue.
=> Fix support of winui for net6+

src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs, src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs, src/TestFramework/TestFramework/Resources/FrameworkMessages.resx, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf, test/UnitTests/TestFramework.UnitTests/Attributes/DynamicDataAttributeTests.cs
To avoid breaking public API, we decided to convert the tuple in `object[]` to preserve it. The current solution relies on `ITuple` which is only available in NET471+. Given we currently target net462 for full framework, that means that the feature will only be available for netcore. I'll weigh the benefit/cost ratio of adding net471 build
in the package so this feature can be available more widely.
Fixes #1335 and fixes #1624
=> Allow IEnumerable of tuple for DynamicData source

samples/mstest-runner/CustomReportExtension/CustomReportExtension.sln, samples/mstest-runner/CustomReportExtension/CustomReportExtension/CustomReportExtension.csproj, samples/mstest-runner/CustomReportExtension/CustomReportExtension/Program.cs, samples/mstest-runner/CustomReportExtension/CustomReportExtension/TestResultConsoleLogger.cs, samples/mstest-runner/CustomReportExtension/CustomReportExtension/UnitTest1.cs
Contributes to #2242
Provides a sample of extending the platform to provide a custom report generator through some simple (naive) console logger.
=> Add a console logger sample for the runner

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs
Reduce allocations by ~39 per test
Before
After
=> Set correct diagnostic default and cut allocations

Directory.Build.Local.props, eng/Version.Details.xml, eng/Versions.props, global.json
Revert to using net sdk 8 to ensure easier contribution from community.
I might have to do a follow-up PR as I need a few confirmations from infra teams that's PDT timezone.
Fixes #2253.
=> Downgrade infra to net8

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
We don't block by-design for performance reason, it's up to the extension decide how to do it.
cc: @Evangelink
=> Add comment on 'OnTestHostProcessStartedAsync' design

eng/Versions.props
VSTest 17.8.0 -> 17.9.0
Code analysis 3.11.0-beta1.23525.2 -> 3.11.0-beta1.23614.1 Threading analyzers  17.7.30 -> 17.9.28
MSBuildStructuredLogger 2.1.858 -> 2.2.169
Polly 8.2.0 -> 8.3.0
StreamJsonRpc 2.16.36 -> 2.17.11
=> Bump dependencies

src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs
contributes to https://github.com/microsoft/testfx/issues/2297
this plus update in the retry extension should shorten the above use case to 84:
`"/var/folders/jd/70dmjhl15_94kvft_dz552ph0000gq/T/6c71eeb55820467f8cf1bc78248b762d/.p"`
=> Shorten server pipe name

src/Adapter/Build/Common/MSTest.TestAdapter.targets
See https://github.com/microsoft/testfx/issues/2173 and https://github.com/dotnet/msbuild/issues/9698
=> [rel/3.2] Workaround harmless MSBuild warning in VS

src/Adapter/Build/Common/MSTest.TestAdapter.targets
See https://github.com/microsoft/testfx/issues/2173 and https://github.com/dotnet/msbuild/issues/9698
=> Workaround harmless MSBuild warning in VS

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticDescriptorHelper.cs
The learn doc link was shorten and updated to simplifying lookup and improve SEO. This fix follows the new format.
=> [rel/3.2] Fix analyzers doc link

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Shipped.md, src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticDescriptorHelper.cs
The learn doc link was shorten and updated to simplifying lookup and improve SEO. This fix follows the new format.
=> Fix analyzers doc link

eng/Version.Details.xml, eng/Versions.props, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/MSTest.Acceptance.IntegrationTests.csproj, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj, test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Microsoft.Testing.Platform.UnitTests.csproj, test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj
Microsoft.Testing.Framework will rename the nugets and namespaces to Microsoft.Testing.Internal.Framework, split the version in dependencies, so we don't break you when we stop producing it. 
Fix for the new package names and namespaces will revert this.
=> Split Microsoft.Testing.Framework version

src/Platform/Microsoft.Testing.Platform/CommandLine/PlaltformCommandLineProvider.cs, src/Platform/Microsoft.Testing.Platform/Helpers/ExitCodes.cs, src/Platform/Microsoft.Testing.Platform/Helpers/NonCooperativeParentProcessListener.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, src/Platform/Microsoft.Testing.Platform/build/Microsoft.Testing.Platform.props, src/Platform/Microsoft.Testing.Platform/buildMultiTargeting/Microsoft.Testing.Platform.props, src/Platform/Microsoft.Testing.Platform/buildTransitive/Microsoft.Testing.Platform.props, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs
contributes to https://github.com/microsoft/testanywhere/issues/1026
Integrations follow-up
=> Introduce `--exit-on-process-exit`

samples/mstest-runner/EnsureTestFramework/EnsureTestFramework.sln, samples/mstest-runner/EnsureTestFramework/EnsureTestFramework/EnsureTestFramework.cs, samples/mstest-runner/EnsureTestFramework/EnsureTestFramework/EnsureTestFramework.csproj, samples/mstest-runner/EnsureTestFramework/EnsureTestFramework/EnsureTestFrameworkCapabilities.cs, samples/mstest-runner/EnsureTestFramework/EnsureTestFramework/EnsureTestFrameworkExtension.cs, samples/mstest-runner/EnsureTestFramework/EnsureTestFramework/TestApplicationBuilderExtensions.cs, samples/mstest-runner/EnsureTestFramework/MyTestProject/MyTestProject.csproj, samples/mstest-runner/EnsureTestFramework/MyTestProject/Program.cs
Add example for simple test framework called Contoso.EnsureTestFramework, that does the bare minimum to wire together the infrastructure needed.
=> Add example for simple framework without VSTest bridge

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.Linux.nuspec, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/Program.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Program.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Program.cs
Remove the `Microsoft.Testing.Extensions.Telemetry` from the package it will come from the VSBridge
=> Remove the `Microsoft.Testing.Extensions.Telemetry` from the package

src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtility.cs
Append pid to make the deploy directory unique during parallel test run.
Fixes https://github.com/microsoft/testfx/issues/2219
=> Make `RootDeploymentDirectory` name unique

.gitignore, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestExtension.cs, src/Adapter/MSTest.TestAdapter/Versions.cs, src/Adapter/MSTest.TestAdapter/Versions.cs.template
@Evangelink I had to add the source file because Compile items cannot be added if we don't update the project for "manual" Includes and I don't like the idea to miss some defaults. We can decide to do it...but.
So what will happen is that on CI we will mutate the file before the build directly there for now. We do similar for the SDK the only difference is that the file is "excluded" in the .gitignore.
Another solution can be add a resource...but it's less performant. 
If version is not changed the task won't touch the file so in local we won't see any difference.
=> Automatic `MSTestExtension` versioning

azure-pipelines-nonofficial.yml
Copy of the pipeline, so we can reconfigure the PR builds to use this. Will cleanup the non-official stuff in later prs.
=> Add copy of pipeline for migration

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/DotnetTestCliTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceAssert.cs
The parent repo is using net9, and with preview2 installed this test is failing due to whitespace difference. 
I am also passing the location info to Assert.That, becuause it was showing all errors coming from the same line in the AcceptanceAssert.cs, which is unuseful for debugging.
=> Fix tests for sdk update to net9-p2 in parent

azure-pipelines-official.yml
Revert because using jobs.yml is not compatible with `outputs:`.
=> Revert outputs

azure-pipelines-official.yml
Remove temporary artifacts to avoid finding binskim issues for exes we don't own.
=> Clean artifacts/tmp

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs, src/Adapter/MSTest.TestAdapter/Extensions/ExceptionExtensions.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestAssemblyInfoTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Extensions/ExceptionExtensionsTests.cs
When my test fails with TargetInvocationException or TypeInitializationException, I get no useful info from the exception. Find the first inner exception that is not this common wrapper exception so user has more information about the fail.
Fix #2307
=> Get real exception in case of error in AssemblyInitialize

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets, src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/testsbaseline.txt, test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs
fixes https://github.com/microsoft/testfx/issues/2568
=> Support "Central Package Management" with the `MSTest.Sdk`

test/Utilities/Microsoft.Testing.TestInfrastructure/DebuggerUtility.cs
Useful to debug parent/children processes during development loop.
Took from VSTest https://github.com/microsoft/vstest/blob/main/src/AttachVS/AttachVs.cs
=> Add `DebuggerUtility` api

azure-pipelines-official.yml
Set the parent directory closer to packages to avoid scanning of all artifacts.
=> Fix parent package path

src/Platform/Microsoft.Testing.Platform/ServerMode/Json/Json.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/SerializerUtilities.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/ServerTests.cs
Currently, we are falling back to Jsonite in case of reference types, so we replaced System.Text.Json with Jsonite by adding serializers and deserializers.
=> Use System.Text.Json instead of Jsonite

azure-pipelines-official.yml
Use image that is owned by arcade and updated sooner than the other official image, so there is less chance that stuff will be temporarily broken after Arcade updates, e.g. SignTool missing dependencies.
=> Use pools from variables and recommended image

src/Platform/Microsoft.Testing.Platform/Builder/TestApplicationBuilder.cs
@Evangelink  this is not more needed right?
I don't see any usage in TA repo I think that now we use the bridge for console and the "default VSTest integration" for compat mode right?
=> Cleanup `TestApplicationBuilder`

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsProviderCache.cs
closes https://github.com/microsoft/testfx/issues/2412
Before
After
Tested only with 1 extension the trx one.
=> Cache `CommandLineOption` from the providers

src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/NoBannerTests.cs
=> Simplify Microsoft.Testing.Platform banner

src/Adapter/MSTestAdapter.PlatformServices/Services/ThreadOperations.cs
This exception occurs when the cancellation happens before the task is actually started.
=> Fix ThreadOperations to handle TaskCanceledException

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets, src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets
Updates PackageReference's so that they are marked as Implicitly Defined. This provides better compatibility with CentralPackageManagement, and with the added `Sdk` meta property it makes it easier to filter Packages added by the SDK.
Fixes #2726
=> Update PackageReferences to be properly defined

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets, src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets
Bring back the SDK flag, follow-up from #2732
=> Revert "remove SDK part of the PackageReference"

azure-pipelines-official.yml
built on internal pipeline is green: https://dev.azure.com/dnceng/internal/_build/results?buildId=2436531&view=results
=> Remove usage of pt images before decomissioning

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/MSTest.Acceptance.IntegrationTests.csproj
Make MSTest.Acceptance an Exe OutputType.
This is required for TestExplorer to be able to run such tests using protocol.
=> Make MSTest.Acceptance an Exe OutputType

src/Platform/Microsoft.Testing.Platform/Telemetry/TelemetryManager.cs
- simplify logic
- fix variable names
- use ArgumentGuard and not ApplicationStateGuard for arguments
=> Various internal refactoring in TelemetryManager

.github/workflows/backport-base.yml, .github/workflows/backport.yml
=> Copy backport GH logic locally and call it

test/Utilities/Microsoft.Testing.TestInfrastructure/TestAsset.cs
Add source mapping for the public sources we insert when we are restoring in testfx repo, and not in the parent repo. 
When this is not added, nuget.org or test-tools are not used for restore. 
Fix #2783
=> Fix test infra to handle package mapping from CPM

src/Platform/Microsoft.Testing.Platform/Extensions/CompositeExtensionsFactory.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs, src/Platform/Microsoft.Testing.Platform/TestHost/TestHostManager.cs, src/Platform/Microsoft.Testing.Platform/TestHostControllers/TestHostControllerConfiguration.cs, src/Platform/Microsoft.Testing.Platform/TestHostControllers/TestHostControllersManager.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/TestApplicationBuilderTests.cs
Make the `IDataConsumer` registration symmetric in both model. Historically we added a way to have data consumer inside the test host for "questionable" trx needs.
So we were foreaching the extension and in case of `IDataConsumer` implementation we were adding as listener to the `IMessageBus` to allow for instance the codecov old version to push the file that the trx could take to put inside the report self.
Nowadays where we run the trx and cc in-process this is mostly non needed but anyway we have a feature to collect artifacts inside the test host controller to "add attachments" if someone there is producing something.
This is an "hidden" and not documented behavior used only by our trx extension. So it's fine to update and make it coherent with the rest, but won't be exposed yet and …
=> Refactor `IDataConsumer` for the `TestHostController`

src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs, test/UnitTests/MSTestAdapter.UnitTests/Extensions/MethodInfoExtensionsTests.cs
This fixes regression, where we validate types of provided data (e.g. in `[DataRow]`) to the expected parameters of the test method exactly by their types. This is too strict and will fail for any types that can implicitly convert. 
This PR simply invokes the method, and relies on runtime to do the right checks, and we just handle and improve the exceptions that it throws. We only handle the two that are documented here: https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.invoke?view=net-8.0 as happening when parameters don't match the target method. 
As a result, user can provide int32 number to int64 parameter and it will work. As mentioned in the linked issue.
Fix #2828
=> Fix parameters/arguments check for data driven tests

eng/Version.Details.xml, eng/Versions.props
We do ship a dependency to CodeCoverage in our product through
MSTest.Sdk so we want to ensure we only reference released versions
at the time where we release MSTest
=> Revert code coverage to latest released

src/Package/MSTest.Sdk/README.md, src/Package/MSTest.Sdk/Sdk/Features/Aspire.targets, src/Package/MSTest.Sdk/Sdk/Features/Playwright.targets, src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets, src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
Do not use the `IsImplictlyDefined="true"` attribute in the `PackageReference` element in the `.targets` files. Instead,
rely on the `VersionOverride` attribute to define the package version. This is because for big projects, teams are usually
slowly migrating to MSTest.Sdk so they need to keep defining MSTest (and platform) packages in their CPM file.
If we use 'IsImplicitlyDefined' attribute, the package will be "defined twice" which will lead to `NU1009` warnings that
are most of the time updated as errors (warnAsError). We created a thread with MSBuild and NuGet teams and the only suggested
solution is for users to suppress the warning which is not ideal. Until a better solution is provided, we will use the
`VersionOverride` trick instead as it achieves a relatively close behavior …
=> MSTest.Sdk: do not use IsImplictlyDefined

src/Analyzers/MSTest.Analyzers.CodeFixes/FixtureMethodSignatureChanges.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/Helpers/FixtureMethodFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/TestCleanupShouldBeValidFixer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/TestCleanupShouldBeValidAnalyzerTests.cs
Add a single code fixer `Fix signature` that will ensures that:
- accessibility is `public`
- return type is `void`, `Task` or `ValueTask`
- method is not `static`
- method takes no parameter
- method isn't generic
- method isn't abstract
The following issues are not fixed:
- method is not a "normal method" (e.g. operator, finalizer...)
- class is generic
=> Code fix for TestCleanupShouldBeValidAnalyzer

src/Analyzers/MSTest.Analyzers.CodeFixes/AssemblyCleanupShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/AssemblyInitializeShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/ClassCleanupShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/ClassInitializeShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/Helpers/FixtureMethodFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/TestCleanupShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/ClassCleanupShouldBeValidAnalyzerTests.cs
Add a single code fixer `Fix signature` that will ensures that:
- accessibility is `public`
- return type is `void`, `Task` or `ValueTask`
- method is `static`
- method doesn't take any parameter
- method isn't generic
The following issues are not fixed:
- method is not a "normal method" (e.g. operator, finalizer...)
- class is generic
=> Add code fix for ClassCleanupShouldBeValidAnalyzer

.markdownlint.json, docs/Changelog.md, docs/testingplatform/idataconsumer.md
Add `<a>` with name to changelog, so we can link to it with `https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#340` no matter what the header says.
=> Add 3.4.0 href to changelog

docs/Changelog.md
Add explicit name to each version so we can link directly to it, with name that includes the dots and does not include the publish date. E.g.  `https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#3.4.0` rather than `https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#340---wip`
=> Add explicit hrefs for all versions

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj, src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj
since ides default to the first target framework when opening a cs file. so better to default to a target framework that everyone will have available (netstandard2.0)
=> move Uwp WinUi to end of target frameworks

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
and 
* remove null check, since the id is accessed above and a null ref would throw if it was null
* re-use the string value for the pid
=> re-use currentPID

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
* make more readable
* remove an array alloc
* remove some unnecessary linq
=> cleanup GetMethodInfoUsingRuntimeMethods

src/Adapter/MSTestAdapter.PlatformServices/Utilities/AssemblyUtility.cs
the resolutionPathsDictionary is only used for a key check. values are not used and there is only one key
=> simplify GetResolutionPaths

src/Platform/Microsoft.Testing.Platform/CommandLine/ParseResult.cs
since it looks like the intent is for it to be a readonly type
=> remove set for toolname on CommandLineParseResult

src/Platform/Microsoft.Testing.Platform/.editorconfig, src/Platform/Microsoft.Testing.Platform/Requests/NopFilter.cs
Fixes #2787 
cc @MarcoRossignoli
=> Make NopFilter public and experimental

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs
Use concurrent dictionary to store attribute cache.
Fix #3042
=> Use concurrent dictionary for attribute cache

samples/public/DemoMSTestSdk/DemoMSTestSdk.sln, samples/public/DemoMSTestSdk/ProjectUsingAspire/IntegrationTest1.cs, samples/public/DemoMSTestSdk/ProjectUsingAspire/ProjectUsingAspire.csproj, samples/public/DemoMSTestSdk/ProjectUsingMSTestRunner/Usings.cs, samples/public/DemoMSTestSdk/ProjectUsingPlaywright/ProjectUsingPlaywright.csproj, samples/public/DemoMSTestSdk/ProjectUsingPlaywright/UnitTest1.cs, samples/public/DemoMSTestSdk/ProjectUsingVSTest/ProjectUsingVSTest.csproj, samples/public/DemoMSTestSdk/ProjectUsingVSTest/Usings.cs, samples/public/DemoMSTestSdk/ProjectWithNativeAOT/ProjectWithNativeAOT.csproj, samples/public/DemoMSTestSdk/ProjectWithNativeAOT/Usings.cs, samples/public/Directory.Build.props
Add samples that were added only to 3.4 branch. 
Related to https://github.com/microsoft/testfx/pull/3073
=> Add SDK samples from rel/3.4

azure-pipelines.yml, test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj, test/Utilities/Microsoft.Testing.TestInfrastructure/TargetFrameworks.cs
Speedup PR feedback loop by testing only latest supported TFM for netcore. As of today, that means the PR CI will test only `net8.0` and no longer `net6.0` and `net7.0`. The main CI will still run all tests to ensure quality.
=> Skip testing intermediate netcore TFMs in PRs

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs, src/Platform/Microsoft.Testing.Platform/Builder/TestApplicationBuilder.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsValidator.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/ICommandLineHandler.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ITestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ToolsTestHost.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/ArgumentArityTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs
Refator `CommandLineHandler` to reduce responsibilities of the class. The new design is not yet optimal but allows to more easily do validation tests of command line providers without having to do a full end-to-end.
This is the first step of my plan to better validate our current providers as we keep discovering "stupid" mistakes around arity and missing validations.
This will also help to validate the test run parameter option by providing extensive test cases.
=> Refactor command line validation to ease testing

src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestRunParametersTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs
When using MSTest runner it wasn't possible to override or provide `TestRunParameters` entries while with VSTest we could override any entry from runsettings. We have decided to not allow to change any runsettings entry but to provide first-class level support for test run parameters.
The syntax is `--test-parameter Key=Value` and we can provide multiple pairs.
=> MSTest runner: allow overriding TestRunParameters

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs
Extracted from #2915. This part seems to be working on my machine so I will merge this part and then move on by taking on the rest of the changes.
cc @SimonCropp
=> Use GetTypes() instead of DefinedTypes

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs
Fixes #3096
I have been working on an integration test but I can't seem to understand why the regex doesn't match (regex101 seems to say it's matching). I have been fighting for 2h now so creating the PR without the test, might add it later.
=> Fix --info when tools are present

src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
Fixes some race condition issues:
```
at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported() in System\ThrowHelper.cs:line 374
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) in System.Collections.Generic\Dictionary.cs:line 1236
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value) in System.Collections.Generic\Dictionary.cs:line 711
at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunSingleTest(TestMethod testMethod, IDictionary`2 testContextProperties) in C:\src\testfx\src\Adapter\MSTest.TestAdapter\Execution\UnitTestRunner.cs:line 186
```
=> Use ConcurrentDictionary for fixtures

src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestFilterTests.cs
Fixes #3178
Some refactoring was done when introducing localization for the console service (cc @nohwnd) that broke the logic, I am fixing it back here.
@MarcoRossignoli I have also considered the cancellation requested as first failure to display.
=> Fix test run footer color to be red when not successful

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs
Fixes #3145 
`Assert.AreEqual<T>(IEquatable<T>, IEquatable<T>)` now handles the 2 arguments being null which fixes the case mentioned with `dynamic`.
=> Fix Assert.AreEqual using null dynamic

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpActivityIndicator.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpConfiguration.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpExtensions.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxEnvironmentVariableProvider.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportExtensions.cs, src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs
Based on https://github.com/microsoft/testanywhere/pull/1864, I am shortening the pipe names which should fix the issue reported on #3097.
It'd be ideal if we could add some integration test that would reproduce the issue.
I'll keep the PR open until it's reviewed by @MarcoRossignoli
=> Shorten pipe names

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
We have noticed the following exception being sometimes thrown:
```
Unhandled Exception: System.InvalidOperationException: No process is associated with this object.
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.get_Id()
at Microsoft.Testing.Platform.Hosts.TestHostControllersTestHost.<InternalRunAsync>b__21_0(Object sender, EventArgs e)
at System.Diagnostics.Process.OnExited()
at System.Diagnostics.Process.RaiseOnExited()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean …
```
=> Retrieve PID inside try/catch

docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs, src/Platform/Microsoft.Testing.Platform/Telemetry/TelemetryManager.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TelemetryTests.cs
Downgrade some log levels to debug so that they don't show up in VS output logs by default.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2112664
cc @MarcoRossignoli @drognanar
=> Downgrade some log levels from info to debug

src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
There seems to be a bug in UWP release mode when ".NET Native tool chain" is enabled causing the data to be wrapped in an `object[]`. While waiting for a proper fix, we are adding a logic to unwrap the data.
Manually tested.
Fixes #3071
=> Workaround the UWP release mode issue with DataRow data

src/Platform/Microsoft.Testing.Platform/Helpers/System/IProcess.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
Got some exception in our testing suite:
```
Unhandled Exception: System.InvalidOperationException: No process is associated with this object.
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.get_Id()
at Microsoft.Testing.Platform.Hosts.TestHostControllersTestHost.<InternalRunAsync>b__21_0(Object sender, EventArgs e)
at System.Diagnostics.Process.OnExited()
at System.Diagnostics.Process.RaiseOnExited()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at …
```
=> Handle InvalidOperationException when accessing process ID

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs
ResultFiles tag was incorrectly placed in the Output. Move it out under TestResults where it belongs.
Fix https://github.com/microsoft/testfx/issues/3260
=> Fix ResultFiles placement in TRX report

samples/Playground/Playground.csproj, samples/Playground/Tests.cs, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/NonNullableReferenceNotInitializedSuppressor.cs, src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt, test/UnitTests/MSTest.Analyzers.UnitTests/NonNullableReferenceNotInitializedSuppressorTests.cs
=> Feat: Add code suppressor for CS8618 on TestContext property

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.TestAdapter/Resources/Resource.resx, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
=> Feature: add support for injecting TestContext in ctor

src/Adapter/MSTest.TestAdapter/Execution/ClassCleanupManager.cs, src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.TestAdapter/Execution/TestRunCancellationToken.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/TestFramework/TestFramework/Attributes/TestMethod/STATestClassAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestClassTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestResultTest.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs
Replaces #3188 and fixes #2688
=> Feat: Add `[STATestClass]`

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/Utilities/ApplicationStateGuard.cs, src/TestFramework/TestFramework/Attributes/TestMethod/STATestMethodAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestMethodTests.cs
=> Feat: Add [STATestMethod]

src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs, test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs, test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DynamicDataTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DynamicDataTests.cs, test/IntegrationTests/TestAssets/DataRowTestProject/DataRowTests_Regular.cs, test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
=> Feat: add support for overloaded parameterized tests

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs, src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs, src/TestFramework/TestFramework/Internal/TestDataSourceUtilities.cs, test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DynamicDataTests.cs, test/IntegrationTests/MSTest.IntegrationTests/TestId.DefaultStrategy.cs, test/IntegrationTests/MSTest.IntegrationTests/TestId.FullyQualifiedStrategy.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataExtensibilityTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DynamicDataTests.cs, test/UnitTests/TestFramework.UnitTests/Attributes/DynamicDataAttributeTests.cs
Copies logic from @MichelZ for `DataRowAttribute` for `DynamicDataAttribute`. This is improving the display for `string`, `char`, `null` and collections.
Before:
After:
=> Improve display name for DynamicDataAttribute

src/Platform/Microsoft.Testing.Platform/Messages/PropertyBag.cs
* dont do linq if _property is null or _property is empty
* avoid multiple enumeration of matchingValues
=> improve perf of PropertyBag.SingleOrDefault

samples/Playground/Playground.csproj, samples/Playground/Program.cs, samples/Playground/ServerMode/TestingPlatformClientFactory.cs, samples/Playground/ServerMode/v1.0.0/TestingPlatformClient.cs, src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs
In server mode we cannot send back logging information to VS after the "exit". 
cc: @drognanar
=> Fix shutdown order for server mode

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs, src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs
* I don't recall why we went for a blocking wait. We have and hang on this line only for 6.0 so it could be a deadlock due to the blocking wait. Token is correctly signaled.
* Setup the pipe to be async
Fixes #3295
=> Fix possible deadlock inside MSBuild task

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs, src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
closes https://github.com/microsoft/testfx/issues/3268
New available syntax 
```bash
dotnet test -- --treenode-filter /*/*/*/TestMethod1 --results-directory "C:\\git\\testfx\\artifacts\\tmp\\Debug\\testsuite\\IDdwQ\\MSBuildTests\\45c8381577bc4a8f8fc63fc9575c3ae9" 
```
=> Handle `--` for msbuild dotnet test integration

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssemblyResolverTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ParameterizedTestTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestClassTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestMethodTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestDiscoveryTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestFilterTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestRunParametersTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadContextTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadingTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ValueTaskTests.cs
These patching are no longer required as we create the platform packages locally now.
=> Chore: remove unused patching in MSTest acceptance tests

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs
Getting the application path guarantees to never return null. Remove the unnecessary null checks that duplicate the code done in the method.
=> Chore: Modulename is never null or empty

test/UnitTests/MSTest.Analyzers.UnitTests/Verifiers/CSharpCodeFixVerifier`2.cs
Copied from https://github.com/dotnet/roslyn-analyzers/pull/7335
=> Highlight C# code in analyzer tests

src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TimeoutInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/Helpers/FixtureKind.cs, src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/TestFramework/TestFramework/Attributes/TestMethod/TimeoutAttribute.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/Properties/launchSettings.json, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestClassTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestMethodTests.cs
The current implementation of the timeout will create a "thread" that will observe the execution of the step (fixture or test method) for a given time (timeout value) and will stop observing after that. This means that we are producing dangling tasks where code continues to execute and possibly mutate state when we move to the next step which can have many unwanted consequences.
With this PR, we introduce a virtuous mode that ressemble what user has to do when implementing cooperative cancellation in their production code. 
/!\ It's important to note that when opting-in to this mode, if the method (fixture or test) is ignoring the token then the method will continue.
Fixes #2432
=> Feat: allow cooperative timeout

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
=> Fix: TestCleanup is always called in case of timeout

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Helpers/FixtureMethodRunner.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/CancellationTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs
Improve error message when step (fixture or test method) is being cancelled through the `TestContext`.
Before for `AssemblyInitialize`:
```text
Assembly Initialization method Playground.TestClass.AssemblyInitialize threw exception. System.OperationCanceledException: The operation was canceled.
```
After for `AssemblyInitialize`:
```text
Assembly initialize method 'UnitTest1.AssemblyInitialize' was canceled
```
=> Fix message when step is canceled through TestContext

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
=> Fix class initialization/cleanup calls

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs, src/Adapter/MSTest.TestAdapter/Extensions/TestCaseExtensions.cs, src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs, test/UnitTests/MSTestAdapter.UnitTests/ObjectModel/UnitTestElementTests.cs
Refactor `TestMethod.DisplayName` to be readonly has it never needs to be updated.
=> Refactor TestMethod DisplayName

src/Analyzers/MSTest.Analyzers/ClassCleanupShouldBeValidAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/ClassCleanupShouldBeValidAnalyzerTests.cs
fix: https://github.com/microsoft/testfx/issues/3349
=> MSTEST0011: report if InheritanceBehavior.BeforeEachDerivedClass is set on a sealed class

src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
fix: https://github.com/microsoft/testfx/issues/3323
=> Update description for (init/cleanup) analyzers

src/Adapter/MSTestAdapter.PlatformServices/Services/TestDataSource.cs
given i assume the result of GetExceptionMessage should be used
=> use GetExceptionMessage instead of ex.Message in TestDataSource

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs
the  diff is a little confusing. basically AddArtifactsAsync and AddResultSummaryAsync has the same 17 lines of code . so move that code to a method
=> refactor out common artifacts code into AddArtifactsToCollectionAsync

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineHandler.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOption.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
fix: https://github.com/microsoft/testfx/issues/3501
=> Add --? alias for --help

src/Platform/Microsoft.Testing.Platform/OutputDevice/Console/AnsiTerminal.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Console/AnsiTerminalTestProgressFrame.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Console/ConsoleLogger.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Console/HumanReadableDurationFormatter.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Console/NonAnsiTerminal.cs
Humanize the time in the progress to show minutes and hours, and reduce the precision to whole seconds. This change reduces the update frequency of the progress to 500ms to reduce flickering and improve performance.
Fix #3532
=> Humanize progress time, and reduce update to 500ms

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs
Assembly name was missing when writing progress using the non-ansi progress reporter.
=> Fix outputting assembly name in non-ansi progress reporter

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporterCommandLineOptionsProvider.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/HelpInfoTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
Add option to allow outputting normal, or detailed, so we can output without or with passed tests.
=> Add --output option

src/Platform/Microsoft.Testing.Platform/Messages/ListTestsMessageBus.cs
Originally we want to check that the producer and the test framework were the same but actually there's no need for it.
=> Remove useless check during `--list-tests`

src/Package/MSTest.Sdk/Sdk/Features/Aspire.targets, src/Package/MSTest.Sdk/Sdk/Features/Playwright.targets, src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Runner/Common.targets, src/Package/MSTest.Sdk/Sdk/Runner/NativeAOT.targets, src/Package/MSTest.Sdk/Sdk/VSTest/VSTest.targets, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
This pull request includes several changes to allow MSTest.Sdk to be used on infra/shared testing libraries. For these libraries, `Microsoft.NET.Test.Sdk`, `MSTest.TestAdapter` and all `Microsoft.Testing.Extensions.*` packages are not required.
Fixes #3567
=> MSTest.Sdk handles library mode

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
Allow any system.color to be written by formatted text message, instead of just supporting red and yellow for error and warning.
=> Fix writing colors to terminal

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs
Change to using just ascii to avoid breaking the progress in text, when saved in non-unicode encoding, or not having the right font: 
also easier to find: 
`[+0/x0/?0]`
=> Change non-ansi progress indicators to ascii

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminal.cs
Add extensions for report files used by xunit.
=> Add known report files

src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
Now that we have more than one supported protocol we give a name to the default one `jsonrpc` in case of `--server` with empty protocol name the `jsonrpc` will be the default
cc: @mariam-abdulla @drognanar
=> Give to json default protocol a name `--server jsonrpc`

src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs
Wrong index in the text pattern.
=> Fix `CommandLineHandler` duplication check message

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminalTestProgressFrame.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/CrashDumpTests.cs
Before: when the window gets smaller the progress is broken, and end up scrolling down on the screen. Same thing happens when assembly name is too long.
After: we hide the tfm and architecture first, then we start trimming the name from right prepending with ... to keep the output to correct width and keep the time on screen.
=> Reduce output when resizing to avoid breaking the progress

src/Platform/Microsoft.Testing.Platform/OutputDevice/TargetFrameworkParser.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
Fix #3669
Show the runtime version in header, and targeted framework in other places.
=> Banner uses runtime framework and live test output uses target framework

src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs, src/Adapter/MSTest.TestAdapter/Resources/Resource.resx, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/MessageLoggerAdapter.cs
Before this fix, info messages were only added to the log whereas warnings and errors were written both to log and output.
Fixing this allows to have MSTest parallelization message showing up:
=> Bridge message logger also forward info to output

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
Extensions don't know nothing about the concept of discovery and we want to keep them far from it.
contributes to https://github.com/microsoft/testfx/issues/3721
=> Disable out of process extensions in case of `--list-tests`

docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.Attributes.cs, docs/testingplatform/Source/TestingPlatformExplorer/TestingFramework/TestingFramework.cs, docs/testingplatform/Source/TestingPlatformExplorer/UnitTests.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs
Cherry pick https://github.com/microsoft/testfx/pull/3754
=> Fix missing skip reason (#3754)

src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/PreferAssertFailOverAlwaysFalseConditionsFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/PreferAssertFailOverAlwaysFalseConditionsAnalyzerTests.cs
fix: https://github.com/microsoft/testfx/issues/3667
=> Add codefix for MSTEST0025

src/Adapter/MSTest.TestAdapter/Execution/ClassCleanupManager.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/ClassCleanupManagerTests.cs
Fix running cleanup after all methods are done, even if some of them are run multiple times. 
Port of #3764 to main.
=> Fix running cleanup after first test method

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressState.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
Fix https://github.com/microsoft/testfx/issues/3762
=> [rel/3.6] Fix timedout test does not fail test run (in ui)

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxProcessLifetimeHandler.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs
fix: https://github.com/microsoft/testfx/issues/3769
=> Fix Timed Out Test isn't shown under timeout counter in Trx Report

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxProcessLifetimeHandler.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs
cherry-pick to 3.6: https://github.com/microsoft/testfx/pull/3773
=> Cherry-pick fix skipped Test isn't shown as skipped/not executed in Trx Report

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
Following some recent discovery that the ordering capability of MSTest is only available in Test Explorer and provided by Test Explorer (discovered through a breaking change on Test Explorer side), we are introducing a new runsettings option to allow running tests in alpabetical order.
=> Add option to order tests by name

src/Platform/Microsoft.Testing.Platform/IPC/Serializers/BaseSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/DotnetTestDataConsumer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/CommandLineOptionMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/DiscoveredTestMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/FileArtifactMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/TestResultMessagesSerializer.cs
Failing tests in the test project were preventing dotnet test to run normally.
=> Fix bug in TestResultMessagesSerializer

src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/DotnetTestConnection.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/IPushOnlyProtocol.cs
This pull request introduces several changes to improve the handling of test session cancellation and ensure proper disposal of resources in the `Microsoft.Testing.Platform` project. The most important changes include initializing the `exitCode` with a default failure value, handling the cancellation token in various parts of the `RunAsync` method, and adding a new method to the `IPushOnlyProtocol` interface.
* [`src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs`](diffhunk://#diff-d3fda3cb4312704ea9abea7557b28ebe5bad6aa45ddf54cbb231447dd552fca0L29-R45): Initialized `exitCode` with `ExitCodes.GenericFailure` and added checks for `testApplicationCancellationToken.IsCancellationRequested` to set `exitCode` to `ExitCodes.TestSessionAborted` when necessary. …
=> Ensure correct exit code in case of cancellation and add `OnExit` phase for for `IPushOnlyProtocol`

src/Adapter/MSTestAdapter.PlatformServices/Utilities/XmlUtilities.cs
Debug.Assert is redundant when we have a subsequent Guard.NotNull
=> use Guard.NotNull and remove redundant Debug.Assert

src/Platform/Microsoft.Testing.Platform/Telemetry/TelemetryManager.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TelemetryTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Telemetry/TelemetryManagerTests.cs
=> Fix: do not show telemetry banner if no telemetry provider is registered

src/Analyzers/MSTest.Analyzers/DynamicDataShouldBeValidAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/DynamicDataShouldBeValidAnalyzerTests.cs
=> MSTEST0018: fix false positive with data member visibility

src/Adapter/MSTest.TestAdapter/Resources/Resource.resx, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf, src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
Other options say to not localize workers and scope, but not the banner.
=> Fix localization info to avoid translating workers and scope

samples/Playground/Playground.csproj, samples/Playground/Program.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestFrameworkBuilderData.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/buildMultiTargeting/Microsoft.Testing.Platform.props
This pull request includes several changes to the `Playground` project and the `Microsoft.Testing.Platform` components, focusing on project configuration, code cleanup, and feature enhancements. The most important changes include updates to project references, import statements, and the addition of new capabilities to the testing platform.
* Consolidated `ProjectReference` tags in `samples/Playground/Playground.csproj` for better readability.
* Added an import statement for `Microsoft.Testing.Platform.props` in `samples/Playground/Playground.csproj` to include platform capabilities.
* Uncommented previously commented-out debugging and test host controller code in `samples/Playground/Program.cs` to enable these features.
* Added a new boolean parameter `isJsonRpcProtocol` to several …
=> Optimize the server mode discovery workflow

src/Analyzers/MSTest.Analyzers/DoNotUseShadowingAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/DoNotUseShadowingAnalyzerTests.cs
fix: https://github.com/microsoft/testfx/issues/3824
=> Fix MSTEST0036 is shown for cases where no shadowing happens

src/Adapter/MSTest.TestAdapter/build/common/MSTest.TestAdapter.props
Relates to #3883, it was missed on #3524.
Code Coverage was fixed, we are waiting for a release on their side.
=> Fix MSTest hook to be always generated

src/TestFramework/TestFramework/Assertions/CollectionAssert.cs, test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
fix: https://github.com/microsoft/testfx/issues/3822
=> Fix CollectionAssert.AreEqual fails for list of strings using IEqualityComparer following

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxEnvironmentVariableProvider.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxProcessLifetimeHandler.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportExtensions.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxTestApplicationLifecycleCallbacks.cs, src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, src/Platform/Microsoft.Testing.Platform/Services/ITestApplicationProcessExitCode.cs, src/Platform/Microsoft.Testing.Platform/Services/TestApplicationResult.cs, src/Platform/Microsoft.Testing.Platform/Services/TestApplicationResultProxy.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Services/TestApplicationResultTests.cs
This pull request introduces changes to the `TrxReportGenerator` and related classes to include the process exit code in the TRX report generation. The most important changes include adding a new dependency for `ITestApplicationProcessExitCode`, updating the `TrxReportEngine` to handle the exit code, and modifying the result summary to reflect the exit code.
* [`src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs`](diffhunk://#diff-60ba0552e9a8b5737b7826674f199f9d3058ccd3e5a3e420c657f52b6c4a6b34R41): Added `ITestApplicationProcessExitCode` as a dependency and updated the constructor and `OnTestSessionFinishingAsync` method to use it. [[1]](diffhunk://#diff-60ba0552e9a8b5737b7826674f199f9d3058ccd3e5a3e420c657f52b6c4a6b34R41) …
=> Fix trx in case of exit code != 0

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/TestingPlatformAutoRegisteredExtensions.cs
Fixes #3813
I'll work on adding some acceptance test as a follow-up but I have manually tested against the demo project in the linked issue.
=> Fix SelfRegisteredExtensions type to be internal

src/TestFramework/TestFramework/Assertions/CollectionAssert.cs, test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
fix: https://github.com/microsoft/testfx/issues/3879
=> Fix CollectionAssert.AreEqual for collection of collections ignores even-items

src/Platform/Microsoft.Testing.Platform/Logging/FileLogger.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.Designer.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/HelpInfoTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs
closes https://github.com/microsoft/testfx/issues/3751
=> Add yy/mm to the log filename for better ordering

src/Platform/Microsoft.Testing.Platform/IPC/Serializers/BaseSerializer.cs
This pull request includes changes to the `BaseSerializer` class in the `Microsoft.Testing.Platform` project to simplify the `WriteSize` method and its usage across multiple methods.
=> Fix WriteSize() in BaseSerializer.cs

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Configurations/RunSettingsConfigurationProvider.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Helpers/TestApplicationBuilderExtensions.cs, src/Platform/Microsoft.Testing.Platform/Configurations/ConfigurationManager.cs, src/Platform/Microsoft.Testing.Platform/Configurations/EnvironmentVariablesConfigurationSource.cs, src/Platform/Microsoft.Testing.Platform/Configurations/IConfigurationSource.cs, src/Platform/Microsoft.Testing.Platform/Configurations/JsonConfigurationSource.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/IFileSystem.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemFileSystem.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs
This pull request introduces several changes to the configuration management in the Microsoft Testing Platform. The key changes include the addition of asynchronous methods for building configuration providers, the introduction of an order property for configuration sources, and updates to unit tests to accommodate these changes.
* [`src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Configurations/RunSettingsConfigurationProvider.cs`](diffhunk://#diff-dcc99abc6e9742ffc0afc0e8b4ac601c665f6e46a9efe4ae674c2db55eb6c89dR6-R17): Added an asynchronous `BuildAsync` method and an `Order` property to the `RunSettingsConfigurationProvider` class. [[1]](diffhunk://#diff-dcc99abc6e9742ffc0afc0e8b4ac601c665f6e46a9efe4ae674c2db55eb6c89dR6-R17) …
=> Fix RunSettings/RunConfiguration/ResultsDirectory

src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/JsonRpcMethods.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs
This pull request includes a change to the `JsonRpcStrings` class in the `JsonRpcMethods.cs` file to standardize the casing of the `EventName` constant. 
Standardization of constant naming:
* [`src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/JsonRpcMethods.cs`](diffhunk://#diff-539514614a82756525e83e46acd035d448ce4be466bb603029d5be7009812f28L66-R66): Changed the constant `EventName` to `eventName` to maintain consistent casing.
cc: @drognanar
=> Fix casing for event key value

eng/cgmanifest.json
From Merlin BOT:
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a built-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
If you have any other questions contact us at OpenSourceEngSupport@microsoft.com.
---
For feedback or questions about this PR, please find the contact …
=> Add '$schema' to 'cgmanifest.json'

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InitializeAndCleanupTimeoutTests.cs
Tests are flaky on CI but don't reproduce locally. I am blocked for 4 days on this. Investigate it in this bug.
=> Ignore flaky tests

src/Adapter/MSTest.TestAdapter/build/net/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/netfx-netcore-netstandard/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/uwp/MSTest.TestAdapter.targets
Copy the resource dlls into the correct localization folders for localized runs.
Fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2221503?src=WorkItemMention&src-action=artifact_link 
Backport of https://github.com/microsoft/testfx/pull/3867
=> [rel/3.6] Fix localization of test adapter messages

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
=> Backport fix displaying inner exceptions

src/Platform/Microsoft.Testing.Platform/OutputDevice/IHotReloadPlatformOutputDevice.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminalTestProgressFrame.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporterOptions.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
Fix https://github.com/microsoft/testfx/issues/3831
=> Fix live output with HotReload

test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpTests.cs
Fix hangdump tests to complete tests after the set timeout, not before. So the test makes more sense.
=> Fix hangdump tests to complete the test after timeout

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpTests.cs
Workaround for https://github.com/dotnet/diagnostics/issues/5020
Workaround for https://github.com/microsoft/testfx/issues/3961
=> Fix hangdump space in dump path

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpActivityIndicator.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpOutputTests.cs
Fixes cases where method names are same in multiple classes (e.g. TestMethod1) and are not visible among the hanging tests.
The bug happens when Class1.TestMethod1 and Class2.TestMethod1 run in parallel, and one of them is not hanging. The first one to complete will remove the entry from tests in progress. 
Using UID reduces the chance of this happening significantly, and will also correctly show  that two tests with name TestMethod1 were running.
=> Fix hangdump not showing tests in progress

eng/verify-nupkgs.ps1, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
Fix https://github.com/microsoft/testfx/issues/4006
=> Only ship TestAdapter related resources

eng/verify-nupkgs.ps1, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
=> [rel/3.6] Only ship TestAdapter related resources

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs, src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/TestContext.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
Makes TestContext aware of the parameters that will be passed to the test method so user could have different behavior in the test init or cleanup,
Fixes #385
=> Add TestData property to the TestContext

Directory.Packages.props, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestDiscoverer.cs, src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs, src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj, src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/SettingsProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/Condition.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FastFilter.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FilterExpression.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FilterExpressionWrapper.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/TestCaseFilterExpression.cs, test/IntegrationTests/MSTest.IntegrationTests/MSTest.IntegrationTests.csproj, test/IntegrationTests/MSTest.IntegrationTests/Utilities/TestCaseFilterFactory.cs
Since PolyFill Guard is already enabled and leverages CallerArgumentExpression
=> Move off validate arg from VSTest ObjectModel

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs, src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework.Extensions/TestContext.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
=> Add TestException property to the TestContext

src/Analyzers/MSTest.Analyzers.CodeFixes/Helpers/FixtureMethodFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/PreferTestInitializeOverConstructorFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/RoslynAnalyzerHelpers/DocumentExtensions.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/TestClassShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/TestContextShouldBeValidFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/TestMethodShouldBeValidCodeFix.cs
=> Refactor GetSemanticModelAsync to GetRequiredSemanticModelAsync

src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidExpectedExceptionAttributeFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs
=> Implement codefix for MSTEST0006 (AvoidExpectedException)

src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs, src/Analyzers/MSTest.Analyzers/UseAttributeOnTestMethodAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseAttributeOnTestMethodAnalyzerTests.cs
=> Respect custom ExpectedExceptionBase attribute implementations

src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs
* use an exception `when` to only catch IOException when ignoreIOExceptions
* remove redundant `subDirectoryContents.Count` check
=> cleanup AddFilesFromDirectory

src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/ObjectFieldIds.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/TestResultMessagesSerializer.cs
Applying feedbacks from https://github.com/microsoft/testfx/pull/4054
=> Refactoring deserialization into methods

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/IOperationExtensions.cs, src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/UseProperAssertMethodsAnalyzerTests.cs
Implements the analyzer part of #3315. Codefix isn't yet implemented.
=> Implement 'Use proper Assert methods' analyzer

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
Hope to fix flakiness on acceptance test by removing the non-terminal logger display.
=> Use new output for VSTest acceptance test

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/DynamicDataOperations.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs, src/TestFramework/TestFramework/Interfaces/EmptyDataSourceExceptionInfoExtensions.cs, src/TestFramework/TestFramework/Interfaces/ITestDataSourceEmptyDataSourceExceptionInfo.cs, test/UnitTests/MSTestAdapter.UnitTests/DynamicDataAttributeTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTestAdapter.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
=> Refactor unnecessary try/catch

src/Platform/Microsoft.Testing.Platform/CommandLine/ParseResult.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/Parser.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/ResponseFileHelper.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs
=> Support rsp in MTP

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestExecutionManagerTests.cs
Fixes oversight in code where we grab the constructors from Reflection rather than getting them from the metadata provider.
Replace https://github.com/microsoft/testfx/pull/4033
=> Use reflection provider for class constructors

TestFx.sln
The latest .sln solution parser assumes that the folder names in the solution must comply with the file path restrictions of Windows. This makes msbuild fail the build of TestFx.sln as one of the folders contains the '&' sign.
Here's what the faulty exception looks like:
```
C:\code\testfx\TestFx.sln : error MSB4025: The project file could not be loaded. System.AggregateException: One or more
errors occurred. ---> Microsoft.VisualStudio.SolutionPersistence.Model.SolutionException: Names cannot:
C:\code\testfx\TestFx.sln : error MSB4025: - contain any of the following characters: / ? : \ * " < > | # & %
C:\code\testfx\TestFx.sln : error MSB4025: - contain control characters
C:\code\testfx\TestFx.sln : error MSB4025: - be system reserved names, including 'CON', 'AUX', 'PRN', 'COM1' or …
```
=> Remove the '&' from the sln file

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs
#4146 
I'm getting this on my pipelines on GitHub actions sometimes:
```
Error: Unhandled exception. System.InvalidOperationException: Console is already
in batching mode.
at 
Microsoft.Testing.Platform.OutputDevice.Terminal.NonAnsiTerminal.StartUpdate() 
in 
/_/src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal
.cs:line 125
at 
Microsoft.Testing.Platform.OutputDevice.Terminal.TestProgressStateAwareTerminal.
ThreadProc() in 
/_/src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressSta
teAwareTerminal.cs:line 45
at System.Threading.Thread.StartCallback()
```
Looking at the code, every call to `StartUpdate` is within a `lock` statement so that all looks correct, so the only thing I can think of is we're hitting some exception (although I can't …
=> StopUpdate in Finally Block

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
When we are using mstest sdk-style project, we have IsTestingPlatformApplication set to false, thus it's causing issues.
Because we are setting this property based on EnableMSTestRunner which is set to false because of the order of import (mstest testadapter props then ClassicEngine.targets), we need to set IsTestingPlatformApplication to true in ClassicEngine.targets to fix this issue.
The IsTestingPlatformApplication property is needed for the dotnet test driver to distinguish if we need to run the test project using the new testing platform.
=> Set IsTestingPlatformApplication to true in ClassicEngine.targets

src/TestFramework/TestFramework/Attributes/TestMethod/IgnoreAttribute.cs
It makes better sense to reflect the real semantics of the attribute.
@Evangelink Any backcompat concerns with this change?
=> Mark IgnoreAttribute as not inherited

src/TestFramework/TestFramework/Attributes/DataSource/DataSourceAttribute.cs, src/TestFramework/TestFramework/Attributes/DataSource/DataTestMethodAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/ExpectedExceptionAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/ExpectedExceptionBaseAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/IgnoreAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/TestClassAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs
=> Small XML doc refreshing

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
=> Improve Regex to Reduce Matching Time

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/NativeAotTests.cs
We are seeing increasing frequency of test flakiness for the acceptance test `NativeAotTests_WillRunWithExitCodeZero`. The error message is:
```text
System.TimeoutException: Timeout after 50s on command line: 'D:\a\_work\1\s/.dotnet/dotnet.exe publish -m:1 -nodeReuse:false D:\a\_work\1\s\artifacts\tmp\Release\testsuite\AKtK1\NativeAotTests -r win-x64 /warnaserror -p:SuppressNETCoreSdkPreviewMessage=true'
```
In a result, I am trying to bump to 90s (arbitrary value).
=> [test] bump dotnet publish timeout to 90s

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf
Reverts microsoft/testfx#4175
There is no timeout on the regex anymore.
=> Revert "Show the text that timed out in regex match"

samples/public/mstest-runner/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain.sln, samples/public/mstest-runner/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain.csproj, samples/public/mstest-runner/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain/MSTestSettings.cs, samples/public/mstest-runner/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain/Program.cs, samples/public/mstest-runner/MSTestProjectWithExplicitMain/MSTestProjectWithExplicitMain/Test1.cs
=> Add a MSTest sample with a program.cs

src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/UseProperAssertMethodsFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/ITypeSymbolExtensions.cs, src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseProperAssertMethodsAnalyzerTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/Verifiers/CSharpCodeFixVerifier`2.cs
=> Implement codefix for MSTEST0037: Use proper 'Assert' methods

src/Analyzers/MSTest.Analyzers/NonNullableReferenceNotInitializedSuppressor.cs
The warning being suppressed is a C# warning and is not relevant for VB as VB doesn't have nullable reference types.
=> Remove VB from `NonNullableReferenceNotInitializedSuppressor`

src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOption.cs
Noticed when profiling Playground.
For big test projects, this won't have that much of an effect though, but it's still a good improvement to take I think.
=> Avoid repetitive string.Format call for every character of command-line options

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/TypeValidator.cs, src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/SourceGeneration/SourceGeneratedReflectionOperations.cs, src/Adapter/MSTestAdapter.PlatformServices/Interfaces/IReflectionOperations2.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/ReflectionOperations2.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs
These changes seems to be more efficient, even if not super significant, but also will help when https://github.com/dotnet/runtime/issues/53217 is implemented (this analyzer is already approved). See also https://github.com/dotnet/runtime/pull/89317 which now hides GetTypeInfo for .NET 10
=> More efficient reflection

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/Execution/TestRunCancellationToken.cs, src/Adapter/MSTest.TestAdapter/PlatformServiceProvider.cs
=> [Performance] Avoid System.Action allocations for test context cancellation

src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestElement.cs
=> [Performance] Avoid TraitCollection.AddRange call with empty array

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumeratorWrapper.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs
It's easiest to review each commit on its own. The second commit is a pure refactoring to remove `RunSettingsXml` as it can be passed from GetTestsInIsolation to EnumerateAssembly and it makes the code easier and more simpler to follow.
This change was motivated by:
=> [Performance] Don't parse the same runsettings for each class in the assembly

src/Adapter/MSTestAdapter.PlatformServices/Deployment/TestRunDirectories.cs
Scenario being profiled:
Adjusted version of Playground with about 150 test method split across 10 test classes.
**Before**
**After**
No longer showing up:
=> [Performance] Avoid repetitive string allocations from TestRunDirectories

src/Adapter/MSTest.TestAdapter/SourceGeneration/SourceGeneratedFileOperations.cs
* remove redundant casts
* make ReflectionDataProvider `null!` and add comment as to why. better than the `warning disable CS8618` that gives no context
* fix nullability of return values
* remove null suppression for `ReflectionDataProvider` usage
=> cleanup SourceGeneratedFileOperations

src/Adapter/MSTestAdapter.PlatformServices/Services/ReflectionOperations.cs
=> [Performance] Ensure ReflectionOperations return `Attribute[]` when possible

src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs, src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeEnumeratorTests.MockedMethodInfoWithExtraAttributes.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeEnumeratorTests.cs
=> Refactor GetTestFromMethod

src/Analyzers/MSTest.Analyzers.CodeFixes/PreferAssertFailOverAlwaysFalseConditionsFixer.cs, src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs, src/Analyzers/MSTest.Analyzers/PreferAssertFailOverAlwaysFalseConditionsAnalyzer.cs, src/Analyzers/MSTest.Analyzers/ReviewAlwaysTrueAssertConditionAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/PreferAssertFailOverAlwaysFalseConditionsAnalyzerTests.cs
=> Preserve message and parameters in MSTEST0025 fixer

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs, src/TestFramework/TestFramework/Attributes/TestMethod/TestPropertyAttribute.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestPropertyAttributeTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
=> Support 'TestPropertyAttribute' on test classes

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumeratorWrapper.cs, src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/TypeValidator.cs, src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorWrapperTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeEnumeratorTests.cs
There shouldn't any noticable difference with this change. It's a minor cleanup.
`Collection<T>` ([Source](https://github.com/dotnet/runtime/blob/f0e1d7ba91f601064b90475541d5e7e91507f63e/src/libraries/System.Private.CoreLib/src/System/Collections/ObjectModel/Collection.cs)) is a mostly a thin wrapper around `List<T>` (except for cases where the constructor with `IList<T>` is used - but we don't use that constructor). I think it's a better idea to just use `List<T>` right away.
=> [Refactor] Use `List<T>` rather than `Collection<T>`

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
=> Introduce Assert.Throws(Async) and Assert.ThrowsExactly(Async) APIs

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs, test/UnitTests/MSTestAdapter.UnitTests/Helpers/ReflectHelperTests.cs
Fixes https://github.com/microsoft/testfx/issues/4331
=> Throw exception if ExpectedExceptionBaseAttribute is applied more than once

Directory.Packages.props, samples/Playground/DebuggerUtility.cs, samples/Playground/Playground.csproj, samples/Playground/Program.cs, samples/Playground/Tests.cs, src/Adapter/MSTest.TestAdapter/DynamicDataOperations.cs, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec, test/UnitTests/MSTestAdapter.UnitTests/DynamicDataAttributeTests.cs
Manually validated. Not adding a unit test because it's convoluted with our current infra.
=> Add support for ValueTuple for all target frameworks

src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs, src/TestFramework/TestFramework/Attributes/DataSource/TestDataSourceDiscoveryAttribute.cs, src/TestFramework/TestFramework/Attributes/DataSource/TestDataSourceDiscoveryOption.cs
Avoid warning/errors on users by removing added obsolete on `TestDataSourceDiscoveryOption`. Instead make it editor browsable hidden and update docs to recommend different usage.
In v4, based on remaining usages we would either deprecate and drop in v5 or drop directly in v4.
=> Don't make TestDataSourceDiscoveryOption obsolete

src/Adapter/MSTest.TestAdapter/Execution/ExceptionHelper.cs
* cache s_utaEndOfInnerExceptionTrace  statically to avoid the string concat on every iteration of the loop
* remove CurrentCulture usage. they are all strings
* avoid the concat with the popped value. yes this is redundant on newer runtimes, but not for older
=> Reduce alloc in GetStackTraceInformation

src/Analyzers/MSTest.Analyzers/DynamicDataShouldBeValidAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/DynamicDataShouldBeValidAnalyzerTests.cs
=> Report diagnostic if DynamicData is referencing a member that's not method/property (e.g, field) (and some cleanup)

Directory.Packages.props, eng/Version.Details.xml, eng/Versions.props, src/Package/MSTest.Sdk/MSTest.Sdk.csproj, src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets, src/Package/MSTest.Sdk/Sdk/Sdk.props.template, test/Directory.Build.targets, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests.csproj
Follow-up from #4354 to cleanup references (use project ref instead of package ref) and fix version included into MSTest.Sdk
=> Cleanup retry and hot reload versions and refs

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/Adapter/MSTest.TestAdapter/RunConfigurationSettings.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestGracefulStopTestExecutionCapability.cs, src/Adapter/MSTestAdapter.PlatformServices/Interfaces/IConfiguration.cs, src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj, src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/uap10.0.16299/PublicAPI.Unshipped.txt
Contributes to #4371
Thanks to the report, I have realized we were about to ship a version of MSTest broken for UWP. We are sadly having issues with having acceptance test for UWP because of arcade infra.
=> Don't reference MTP in UWP

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
the *Polyfill types are meant to be used as a replacement to remove the need for the ifdef
on newer frameworks they redirect to correct implementation
=> use EnumPolyfill.GetNames correctly

src/Analyzers/MSTest.Analyzers/TestContextShouldBeValidAnalyzer.cs
History:
- https://github.com/microsoft/testfx/pull/4439 added the using due to the use of ConcurrentBag. This alone was green.
- https://github.com/microsoft/testfx/pull/4424 added System.Collections.Concurrent as global using. This alone was green.
When both PRs got to main, it's now failing because the using in the analyzer is now redundant due to it being already a global using.
=> Fix main build

src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs
ImmutableDictionary.CreateBuilder is designed for creating an ImmutableDictionary without duplicating it on each .Add
=> Avoid Immutable.Add

src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseProperAssertMethodsAnalyzerTests.cs
=> MSTEST0037 (proper assert analyzer): Don't report for user defined equality operators

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
=> Refactor running of data driven tests

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
=> Small cleanup to Assert.AreEqual

src/Analyzers/MSTest.Analyzers/UseParallelizeAttributeAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseParallelizeAttributeAnalyzerTests.cs
=> Don't report MSTEST0001 when TestAdapter isn't referenced

src/Platform/Microsoft.Testing.Platform/Requests/TreeNodeFilter/TreeNodeFilter.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
=> Fix match all filter not working when property expression is present

src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidExpectedExceptionAttributeFixer.cs, src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs
=> Update ExpectedException codefix to use the new Assert.Throws[Exactly][Async] overloads

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/AvoidAssertAreSameWithValueTypesAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs
=> Add analyzer for value type usage with Assert.AreSame

src/Analyzers/MSTest.Analyzers/AvoidAssertAreSameWithValueTypesAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs
=> Report diagnostic when AreNotSame is passed value type

eng/verify-nupkgs.ps1, src/Adapter/MSTest.TestAdapter/BannedSymbols.txt, src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/Helpers/MSTestDiscovererHelpers.cs, src/Adapter/MSTest.TestAdapter/IPlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/Adapter/MSTest.TestAdapter/PlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/RunConfigurationSettings.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/BridgedConfiguration.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBannerCapability.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBridgedTestFramework.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestExtension.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestGracefulStopTestExecutionCapability.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestingPlatformBuilderHook.cs, src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestDiscoverer.cs, src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs, src/Adapter/MSTestAdapter.PlatformServices/Interfaces/IConfiguration.cs, src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj, src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/SettingsProvider.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/MSTestAdapterSettingsTests.cs, test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs, test/UnitTests/MSTestAdapter.UnitTests/RunConfigurationSettingsTests.cs, test/UnitTests/MSTestAdapter.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
During the investigation, I realized that VSTest custom assembly resolver, enabled only when AppDomains are enabled and only for netfx, includes only VS folders and MSTest.TestAdapter. On 3.7, we started to depend upon some types from MTP leading to the dll being required but not loaded in this mode (the deps is part of a different NuGet). 
As part of the analysis, I have also noticed that we are required to keep the framework under the adapter folder for the exact same reason.
I have restored the framework, only for netfx, that will be resolved only when under the customer resolver for netfx in VSTest. For MTP, I have decided not to copy the dll but instead to have wrapper types so we don't "pollute" the engine with types specific to a given platform.
Fixes #4426
=> Fix "Could not load file or assembly 'Microsoft.Testing.Platform'" exception

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs
Running the new tests on main, there are 14 failures. 7 are for `float` and 7 are for `double`. I'll list the test names for `float` failures only as the double ones are exact mirror.
```
DoubleAreEqual_ExpectedIsNaN_ActualIsNaN_DeltaIsNumeric_ShouldPass
DoubleAreNotEqual_ExpectedIsNaN_ActualIsNaN_DeltaIsNaN_ShouldFail
DoubleAreNotEqual_ExpectedIsNaN_ActualIsNaN_DeltaIsNumeric_ShouldFail
DoubleAreNotEqual_ExpectedIsNaN_ActualIsNumeric_DeltaIsNaN_ShouldFail
DoubleAreNotEqual_ExpectedIsNumeric_ActualIsNaN_DeltaIsNaN_ShouldFail
DoubleAreNotEqual_ExpectedIsNumeric_ActualIsNumeric_ExpectedAndActualEquals_DeltaIsNaN_ShouldFail
DoubleAreNotEqual_ExpectedIsNumeric_ActualIsNumeric_ExpectedAndActualNotEquals_DeltaIsNaN_ShouldFail
```
Fixes #4530
=> Fix NaN behavior for Assert.AreEqual/AreNotEqual

test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs
the `SuppressFinalize` and `protected virtual void Dispose(bool disposing)` is only required when cleaning up unmanaged resources
=> remove destructor pattern from TempDirectory

src/Platform/Microsoft.Testing.Platform/.editorconfig
Maybe this is already the default, I don't know. But it's better to be explicit IMO.
=> Set MTP editorconfig as non-root explicitly

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ParameterizedTestTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadContextTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TimeoutTests.cs, test/IntegrationTests/MSTest.IntegrationTests/OutputTests.cs, test/IntegrationTests/MSTest.IntegrationTests/Utilities/CLITestBase.discovery.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/FixturesTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/DiagnosticTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TelemetryTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/TrxTests.cs, test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/ReflectionUtilityTests.cs, test/Performance/MSTest.Performance.Runner/Steps/PerfviewRunner.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseAsyncSuffixTestFixtureMethodSuppressorTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseAsyncSuffixTestMethodSuppressorTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Discovery/UnitTestDiscovererTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationExtensionsTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs, test/Utilities/Automation.CLI/CLITestBase.e2e.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetMuxer.cs
=> make some methods static

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentItemUtility.cs, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/ArrayBuilder.cs, src/Platform/Microsoft.Testing.Extensions.Telemetry/AppInsightsProvider.cs, src/Platform/Microsoft.Testing.Platform/Messages/AsynchronousMessageBus.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/HandshakeMessageSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs, test/Performance/MSTest.Performance.Runner/PipelinesRunner.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetMuxer.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/ProcessFactory.cs
=> deconstruct some KeyValuePair

src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidAssertAreSameWithValueTypesFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, src/Analyzers/MSTest.Analyzers/AvoidAssertAreSameWithValueTypesAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs
=> Implement codefix for 'Are[Not]Same' usage with value types

.github/workflows/backport-base.yml
=> Adjustments for Backport GH Action

.github/workflows/backport-base.yml
=> Progress with backport action

src/TestFramework/TestFramework/Internal/DebugEx.cs
=> Use FailFast instead of throwing in DebugEx.Assert under .NET Framework

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs
TrxTests works by creating a MemoryStream, and mocking NewFileStream to return that instance. Then later, the tests tries to use that stream. For that reason, tests are passing a flag to prevent production code form disposing the stream.
This PR cleans up product code, but makes tests more verbose. Now, product code will **always** dispose, without any flag that's used by tests. However, the "fake" stream created by tests will create the `XDocument` that the test needs when Dispose is called. That way, we don't need the stream anymore and we use the XDocument.
@Evangelink How do you feel about this change? I generally don't like when there is a code path in product code that's test only and prefer more ugly tests but cleaner product code. That's a personal taste though.
=> Avoid keeping trx stream open in unit tests

Directory.Packages.props, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj, test/UnitTests/MSTestAdapter.UnitTests/MSTestAdapter.UnitTests.csproj
=> Drop package ref to System.Memory

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/AvoidUsingAssertsInAsyncVoidContextAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/AvoidUsingAssertsInAsyncVoidContextAnalyzerTests.cs
=> Implement analyzer to warn for use of Assert methods in async void

src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataOperations.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TupleDynamicDataTests.cs
=> Fix Tuple/ValueTuple handling of TRest

src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/ExtensionResources.resx, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.cs.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.de.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.es.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.fr.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.it.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.ja.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.ko.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.pl.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.ru.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.tr.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/Resources/xlf/ExtensionResources.zh-Hant.xlf, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxDataConsumer.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxProcessLifetimeHandler.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportEngine.cs, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxReportExtensions.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs
=> Overwrite trx when file name is explicitly provided

Directory.Packages.props
Reverts microsoft/testfx#4673
This is breaking main and we need to wait for a package that contains https://github.com/microsoft/testfx/pull/4678
=> Revert "[main] Bump MSTest from 3.8.0-preview.25063.12 to 3.8.0-preview.25065.17"

src/TestFramework/TestFramework/Constants.cs, src/TestFramework/TestFramework/Exceptions/InternalTestFailureException.cs, src/TestFramework/TestFramework/GenericParameterHelper.cs
=> Obsolete InternalTestFailureException and GenericParameterHelper

src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
=> Re-word async void analyzer description

src/Adapter/MSTest.TestAdapter/Constants.cs, src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs, src/Adapter/MSTest.TestAdapter/Extensions/TestCaseExtensions.cs, src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs, src/Adapter/MSTest.TestAdapter/ObjectModel/UnitTestElement.cs, test/UnitTests/MSTestAdapter.UnitTests/Extensions/TestCaseExtensionsTests.cs, test/UnitTests/MSTestAdapter.UnitTests/ObjectModel/UnitTestElementTests.cs
I can't see any meaningful usage of it.
@Evangelink Do you know if it's used by a component outside of testfx repo?
=> Remove AsyncTestProperty

TestFx.sln, eng/verify-nupkgs.ps1, src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj, src/Analyzers/MSTest.Analyzers.Package/buildTransitive/MSTest.Analyzers.props, src/Analyzers/MSTest.Analyzers.Package/buildTransitive/MSTest.Analyzers.targets, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticDescriptorHelper.cs, src/Analyzers/MSTest.Analyzers/Helpers/WellKnownCustomTags.cs, src/Analyzers/MSTest.Analyzers/PreferConstructorOverTestInitializeAnalyzer.cs, src/Analyzers/MSTest.Analyzers/PreferDisposeOverTestCleanupAnalyzer.cs, src/Analyzers/MSTest.Analyzers/PreferTestCleanupOverDisposeAnalyzer.cs, src/Analyzers/MSTest.Analyzers/PreferTestInitializeOverConstructorAnalyzer.cs, src/Analyzers/MSTest.Analyzers/TestMethodShouldBeValidAnalyzer.cs, src/Analyzers/MSTest.GlobalConfigsGenerator/AnalyzerAssemblyLoader.cs, src/Analyzers/MSTest.GlobalConfigsGenerator/AnalyzerSeverityDecider.cs, src/Analyzers/MSTest.GlobalConfigsGenerator/GlobalConfigBuilder.cs, src/Analyzers/MSTest.GlobalConfigsGenerator/MSTest.GlobalConfigsGenerator.csproj, src/Analyzers/MSTest.GlobalConfigsGenerator/MSTestAnalysisMode.cs, src/Analyzers/MSTest.GlobalConfigsGenerator/Program.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AnalyzersTests.cs
=> Implement MSTestAnalysisMode

src/Package/MSTest.Sdk/Sdk/Sdk.props.template
The `Microsoft.NET.Sdk` sets a `UsingMicrosoftNETSdk` property which allows other imported files to rely on it, for example in Directory.Build.{props, targets}. This PR adds a similar `UsingMSTestSdk` for the MSTest SDK.
=> Add UsingMSTestSdk property

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
=> Fix MTP MSBuild targets to run before BeforeCompile and XamlPreCompile

src/Analyzers/MSTest.Analyzers.CodeFixes/AddTestClassFixer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs, src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/PublicTypeShouldBeTestClassAnalyzerTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/TypeContainingTestMethodShouldBeATestClassAnalyzer.cs
=> MSTEST0030: add codefix

src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs, src/Adapter/MSTest.TestAdapter/Extensions/TestResultExtensions.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Extensions/TestResultExtensionsTests.cs
`UnitTestResult` is no longer used in production code and is kept ONLY for backcompat because it's public. The tests are now using `ToTestResult` which converts from TestFramework model to VSTest model, which better reflects what happens in production.
=> Avoid using ToUnitTestResults in unit tests

test/Utilities/Microsoft.Testing.TestInfrastructure/TestAssetFixtureBase.cs
=> Drop `-m:1 -nodeReuse:false` from acceptance tests infra

src/Analyzers/MSTest.Analyzers/PublicMethodShouldBeTestMethodAnalyzer.cs, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/IMethodSymbolExtensions.cs, test/UnitTests/MSTest.Analyzers.UnitTests/PublicMethodShouldBeTestMethodAnalyzerTests.cs
Fixes #4660.
I am not sure what's the best way to really cover/document that we exclude all interfaces.
=> MSTEST0029 do not report on implementation of interface

.editorconfig, src/TestFramework/TestFramework/Attributes/TestMethod/RetryBaseAttribute.cs, src/TestFramework/TestFramework/Attributes/TestMethod/RetryContext.cs, src/TestFramework/TestFramework/Attributes/TestMethod/RetryResult.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
Following internal discussions, there are some unclear parts as to how we want to really allow extension of the retry capabilities so marking it as experimental so we can allow some extensibility while reserving right to modify the public API.
=> Retry: mark as experimental extension points

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/AssertionArgsShouldAvoidConditionalAccessAnalyzer.cs
Although it was only `Info` by default, it seems to be causing polarization amongst users so disabling by default now.
Fixes #4706
=> Disable MSTEST0026 by default

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs, src/Platform/Microsoft.Testing.Platform/Helpers/EnvironmentVariableConstants.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/IProcess.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs
=> Add ability to wait for debugger attach

src/Adapter/MSTest.TestAdapter/IPlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/PlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/BridgedTraceLogger.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/MSTestBridgedTestFramework.cs, test/UnitTests/MSTestAdapter.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
=> Add MSTest trace logs when using MTP

Directory.Build.props, src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, src/Adapter/MSTest.TestAdapter/IPlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, src/Adapter/MSTest.TestAdapter/PlatformServiceProvider.cs, src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs, src/Adapter/MSTestAdapter.PlatformServices/Deployment/AssemblyLoadWorker.cs, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/CompilationExtensions.cs, src/Platform/Microsoft.Testing.Platform/Helpers/TestApplicationBuilderExtensions.cs, src/TestFramework/TestFramework/Assertions/CollectionAssert.cs, src/TestFramework/TestFramework/Attributes/TestMethod/OSConditionAttribute.cs, test/Utilities/Automation.CLI/CLITestBase.e2e.cs
=> Fix some missing xml docs

src/TestFramework/TestFramework/Assertions/Assert.Contains.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs, src/TestFramework/TestFramework/Resources/FrameworkMessages.resx, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf, src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
=> Add string Contains/DoesNotContain assertions

src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
=> avoid 2x string allocs in TerminalOutputDevice

src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs
=> Remove `TestRequestExecutionTimeInfo` from `TerminalOutputDevice.DataTypesConsumed`

src/Platform/Microsoft.Testing.Platform.MSBuild/Microsoft.Testing.Platform.MSBuild.csproj, src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/DotnetMuxerLocator.cs, src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceTestBase.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/CommandLine.cs
Fixes https://github.com/microsoft/testfx/issues/4070
=> Fix InvokeTestingPlatformTask to handle running with msbuild.exe and 'Test' target

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ContextAdapterBase.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/DiscoveryContextAdapter.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunContextAdapter.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsAdapter.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Requests/VSTestDiscoverTestExecutionRequestFactory.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/RunsettingsTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestFilterTests.cs
=> VSTestBridge: support filter at discovery + runsettings TestCaseFilter

src/Adapter/MSTestAdapter.PlatformServices/Utilities/AppDomainUtilities.cs
=> Preserve TestIdGenerationStrategy in the execution AppDomain

src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs, src/Directory.Build.props, src/Platform/Microsoft.Testing.Platform/Capabilities/TestFramework/IGracefulStopTestExecutionCapability.cs, src/Platform/Microsoft.Testing.Platform/Messages/TestNodeUid.cs, src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs, src/TestFramework/TestFramework/Assertions/Assert.AreSame.cs, src/TestFramework/TestFramework/Assertions/Assert.Contains.cs, src/TestFramework/TestFramework/Assertions/Assert.Count.cs, src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs, src/TestFramework/TestFramework/Assertions/Assert.IsNull.cs, src/TestFramework/TestFramework/Assertions/Assert.IsTrue.cs, src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs, src/TestFramework/TestFramework/Interfaces/ITestDataSourceUnfoldingCapability.cs
I noticed there is no doc comment for
https://github.com/microsoft/testfx/blob/4210f00ff9cca0eb2a7004663cbffa5ec00e55f7/src/TestFramework/TestFramework/Interfaces/ITestDataSourceUnfoldingCapability.cs#L13
So maybe StyleCop doesn't catch all cases. Let's see if the compiler is able to capture this, then we should fix the build errors.
cc @Evangelink
=> Set SkipArcadeNoWarnCS1591 to true

src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTest.TestAdapter/Discovery/DiscoveryTestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
Building "fake" options type doesn't seem like a good idea. It's simply caller responsibility to be aware that these info are not correct and cannot be relied on. When reading the code, you have to go to references few levels up to understand and be sure that the "fake" options are indeed not used.
Instead, a new internal `DiscoveryTestMethodInfo` is introduced which holds only information relevant for discovery. It also doesn't calculate things that will end up not being used for discovery.
As the new type is very lightweight, I chose to make it a struct.
=> Refactor discovery to build specific info for discovery

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj
It seems unnecessarily complex currently.
=> Simplify inclusion of MSTestVersion.cs and PlatformVersion.cs

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
If a user updates from 3.7 to 3.8 (not yet released at time of writing), the compilation may fail without this change. This is because the user may have TestingPlatformEntryPoint.cs already generated, and it will be seen as up-to-date because RootNamespace isn't included in the hash (the generation in 3.7 didn't use RootNamespace at all, while we do use it in 3.8). This change makes sure that the entry point file will be re-generated.
This is also relevant even if the user starts a clean build on 3.8, then changes `RootNamespace` in csproj after that.
=> Include RootNamespace in hash calculation for MTP MSBuild generated files

Directory.Packages.props, test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj
The security concerns mentioned in comments were addressed by https://github.com/dotnet/roslyn-sdk/pull/1148 and https://github.com/microsoft/vs-streamjsonrpc/pull/1095
=> Remove redundant explicit override of NuGet.Packaging and MessagePack

docs/Changelog-Platform.md, docs/Changelog.md
Follow-up to #4989 (had the changes locally but forgot to push them)
=> Follow-up to Changelog

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
For C#:
https://github.com/dotnet/msbuild/blob/aff54559404d31214c71aa2ea6d2caa6003b0334/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L37
For VB:
https://github.com/dotnet/msbuild/blob/aff54559404d31214c71aa2ea6d2caa6003b0334/src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets#L37
For F#:
https://github.com/dotnet/fsharp/blob/898c6c7a5b39f6bc0cfb42c21e3fcc167b192ab4/src/FSharp.Build/Microsoft.FSharp.Targets#L42
=> Simplify generated file name by using `DefaultLanguageSourceExtension`

src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs, src/Adapter/MSTest.TestAdapter/Helpers/TestDataSourceHelpers.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TupleDynamicDataTests.cs
=> Avoid handling tuples for test methods with only `object[]` parameter

src/Adapter/MSTest.TestAdapter/buildTransitive/common/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/buildTransitive/common/MSTest.TestAdapter.targets, src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.props, src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.ConfigurationFile.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs
Fixes #5016 
The general idea here is:
1. MSBuild extension props file is imported first. We do nothing
2. Then TestAdapter props. We do nothing.
3. csproj is imported, and the user can set `IsTestingPlatformApplication` and/or `EnableMSTestRunner`.
4. MSBuild extension targets are imported. At this point, we default `IsTestingPlatformApplication` to true if it wasn't set from csproj or from MSTest.Sdk. But we don't yet decide whether or not we can generate anything.
5. TestAdapter targets is imported, now we default `EnableMSTestRunner` to false if not already set. And we overwrite `IsTestingPlatformApplication` to use the same value as EnableMSTestRunner
6. In MSBuild extension `Target`s (referring to really "Target", not `.targets` file), this is only when we can reliable use the value …
=> Try out props/targets refactoring

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
Backports https://github.com/microsoft/testfx/pull/5044
Backport is manually created as there is a refactoring done on main so an automated backport PR will likely have conflicts. The change is small enough for the backport PR to be manually done ;)
=> [rel/3.8] Revert _IncludeGenerateAutoRegisteredExtensionsIntoCompilation target rename

src/Platform/Microsoft.Testing.Extensions.HotReload/HotReloadHandler.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs, src/Platform/Microsoft.Testing.Platform/Helpers/CountDownEventExtensions.cs, src/Platform/Microsoft.Testing.Platform/Helpers/NonCooperativeParentProcessListener.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/IConsole.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemConsole.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemMainModule.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcessHandler.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemTask.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs, src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeClient.cs, src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs, src/Platform/Microsoft.Testing.Platform/Logging/FileLogger.cs, src/Platform/Microsoft.Testing.Platform/Microsoft.Testing.Platform.csproj, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/AnsiTerminal.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs, src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/MessageHandlerFactory.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/TcpMessageHandler.cs, src/Platform/Microsoft.Testing.Platform/Services/CTRLPlusCCancellationTokenSource.cs, src/Platform/Microsoft.Testing.Platform/Services/StopPoliciesService.cs
=> Enable platform compatibility warnings for android, ios, tvos, and browser

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/IgnoreTests.cs
When the first test of a class is ignored (and the first test ever in the assembly), we will not call AssemblyInitialize, so `IsAssemblyInitializeExecuted` will be false.
However, in that case, we still want to call `RunClassCleanup` so that the test is marked as completed (see `MarkTestComplete`). Not marking the ignored test as completed is problematic, because later on when all tests in the class are executed, we will still be viewing remaining tests in the class, hence we will not call class cleanup.
Note that even with this change, we respect the case where all tests in class are ignored, and we will not call ClassCleanup. The logic in `ExecuteClassCleanup` handles the case when class init wasn't called.
Fixes #5062
=> Fix ClassCleanup not called when the first test in class is ignored

test/UnitTests/TestFramework.UnitTests/Exceptions/BinaryFormatterExceptionSerializationTests.cs
Fix https://devdiv.visualstudio.com/DevDiv/_queries/edit/?_a=query&wiql=%20SELECT%20ID%2CSeverity%2CState%2C%5BAssigned%20To%5D%2CTitle%20FROM%20WorkItem%20WHERE%20Tags%20Contains%27TSA-testfx-CodeQL-Official%27AND%20State%20IN%28%27Active%27%29%20&id=2395119
=> Add SerializationBinder to formatter we use in tests

.editorconfig
https://spec.editorconfig.org/#no-inline-comments
> *Changed in version 0.15.0.*
>
> A `;` or `#` anywhere other than at the beginning of a line does not start a comment, but is part of the text of that line.
=> Respect EditorConfig spec about comments

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
@Evangelink Worth backporting? Not sure if it can affect some arm64 scenarios
=> Fix typo in determining `_TestArchitecture`

test/UnitTests/TestFramework.UnitTests/Exceptions/BinaryFormatterExceptionSerializationTests.cs
Resolve type in binder based on the exception. Null binders are not allowed.
=> Resolve types in test binary formatter binder

src/Adapter/MSTest.TestAdapter/MSTestSettings.cs, test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs
@Evangelink Worth backporting?
=> Fix `parallelism:enabled` incorrectly setting `OrderTestsByNameInClass`

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
I think it's a better idea to avoid having dependencies between the self-registered generation and the entry point generation. We let the target run on whatever order, and we still respect the compile order by using `CompileAfter` for the entry point.
=> Refactor F# compile order

test/Utilities/Microsoft.Testing.TestInfrastructure/TestAssetFixtureBase.cs
=> Fix binlog base name for .NET Framework tests

test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/TempDirectory.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/TestAsset.cs
=> Cleanup TempDirectory implementation

test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/DeploymentTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs, test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/TimeoutTests.cs, test/Utilities/Automation.CLI/CLITestBase.e2e.cs
Return path to .dotnet when setting DOTNET_ROOT to properly propagate the where locally installed dotnet is.
Fix #5110
=> Fix dotnet_root passing, and unignore tests

src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs, src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/CommandLine.cs
Manually verified this works as expected. For https://github.com/microsoft/PowerToys/pull/37001, tests run successfully when running the Exe directly but not when using `dotnet exec dll`. I wasn't able to set up projects in a similar way as PowerToys to repro the issue and have a test. But I think it makes sense to run directly, and potentially even faster. We probably have enough tests to know if this change is problematic for a main stream scenario.
=> Update InvokeTestingPlatformTask to prefer running Exe over `dotnet exec dll`

src/Platform/Microsoft.Testing.Platform/Configurations/AggregatedConfiguration.cs, src/Platform/Microsoft.Testing.Platform/Configurations/ConfigurationExtensions.cs, src/Platform/Microsoft.Testing.Platform/Configurations/ConfigurationManager.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs, src/Platform/Microsoft.Testing.Platform/TestHostControllers/TestHostControllersManager.cs, test/UnitTests/MSTest.Engine.UnitTests/Adapter_ExecuteRequestAsyncTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/AggregatedConfigurationTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationExtensionsTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/TestApplicationBuilderTests.cs
=> Consider `--results-directory` before configuration

eng/verify-nupkgs.ps1, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.NonWindows.nuspec, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec, src/Adapter/MSTest.TestAdapter/build/net462/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/net462/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/net6.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/net6.0/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/net7.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/net7.0/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/net8.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/net8.0/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/net9.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/net9.0/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/netcoreapp3.1/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/netcoreapp3.1/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/netstandard2.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/netstandard2.0/MSTest.TestAdapter.targets, src/Adapter/MSTest.TestAdapter/build/uap10.0/MSTest.TestAdapter.props, src/Adapter/MSTest.TestAdapter/build/uap10.0/MSTest.TestAdapter.targets, src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.NonWindows.nuspec, src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.nuspec, src/TestFramework/TestFramework.Extensions/build/net6.0/MSTest.TestFramework.targets, src/TestFramework/TestFramework.Extensions/build/net7.0/MSTest.TestFramework.targets, src/TestFramework/TestFramework.Extensions/build/net8.0/MSTest.TestFramework.targets, src/TestFramework/TestFramework.Extensions/build/net9.0/MSTest.TestFramework.targets
=> Ship props/targets of MSTest.TestFramework and MSTest.TestAdapter in both build and buildTransitive

test/Directory.Build.targets
Hopefully fixes main official build this time :)
=> Consume MTP.MSBuild from source when using internal test framework

src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs, test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs
Fixes #5226
Looks like it could be a regression from #4686
=> Fix TestFailedException outcome not propagating to TestResult outcome

docs/Changelog-Platform.md, docs/Changelog.md
=> Add Changelog for 3.8.3

src/TestFramework/TestFramework/Assertions/StringAssert.cs
=> Fix typo in docs for `StringAssert.That`

azure-pipelines.yml, global.json
We previously made changes in the protocol used by dotnet test to add `InstanceId` which was breaking. So, we temporarily switched back to Arcade's way of testing. Now that we have an updated version of SDK that knows the new protocol, I'm switching back to `dotnet test`.
=> Use new version of .NET SDK and re-enable new dotnet test experience

src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs
Just noticed a small typo in the documentation
=> Fix typo in TestMethodAttribute documentation

src/TestFramework/TestFramework.Extensions/Attributes/WinUI_UITestMethodAttribute.cs
We should pass `null` so that we fallback to `Arguments` which has the right thing for parameterized tests:
https://github.com/microsoft/testfx/blob/d991da75ccb71e4181424ae6435d3136f9d43062/src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs#L149
Fixes #740
It looks like we don't have the test infra that allows to test this, as we need vstest.console.exe that comes with VS. It should be possible to test it, but requires a bit of test infra work.
=> Fix parameterized UI tests for WinUI

src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/MSTest.Analyzers/DuplicateDataRowAnalyzer.cs, src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs, src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.Analyzers/Resources.Designer.cs, src/Analyzers/MSTest.Analyzers/Resources.resx, src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/DiagnosticExtensions.cs, src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf, test/UnitTests/MSTest.Analyzers.UnitTests/DuplicateDataRowAnalyzerTests.cs
=> Add analyzer for duplicate data row

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs, src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs, test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodePropertiesTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs, test/Utilities/Microsoft.Testing.TestInfrastructure/Microsoft.Testing.TestInfrastructure.csproj
Partially addressing #5265
From the original issue:
> Ideally, in order to reduce memory consumption, these properties should not always be emitted by the test framework and we should have a capability like we have for TRX that would allow clients or extensions to declare they are interested about such properties so that test framework can conditionally emit them.
This is something I'm not doing yet in this PR. So will keep the issue open to address it.
=> VSTestBridge: Add traits as TestMetadataProperty

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.NonWindows.nuspec, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec, src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.NonWindows.nuspec, src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.nuspec, src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj
Scenario:
A test project uses MSTest 3.8.3, and upgrades `System.Threading.Tasks.Extensions` to 4.6.0 or later.
MSTest.TestAdapter already depends on 4.5.4.
Because the user is using a newer version, the requested assembly version by MSTest.TestAdapter won't be found.
**Normally**, binding redirects should be generated and are considered by VSTest. However, the tooling only consider assemblies in `Reference` item for binding redirect generation. As MSTest.TestAdapter NuGet package is kinda special and the adapter dll isn't added to `Reference` item, binding redirect is not generated.
=> Move System.Threading.Tasks.Extensions to TestFramework

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
Screenshot from dotnet test, but it is the same issue and code, empty line was doubled when we wrote artifacts, because we wrote it before writing artifacts and not after.
=> Fix double empty line

src/Adapter/MSTest.Engine/Engine/TestExecutionContext.cs, src/Adapter/MSTest.Engine/Engine/ThreadPoolTestNodeRunner.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/FrameworkHandlerAdapter.cs, src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs, src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs, src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/DotnetTestDataConsumer.cs, test/UnitTests/Microsoft.Testing.Extensions.UnitTests/TrxTests.cs, test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
The API isn't yet shipped so another break is okay :)
I feel like it's redundant to requires the property having SessionUid. It's already available on the `TestNodeUpdateMessage`.
=> Remove SessionUid from FileArtifactProperty

CONTRIBUTING.md
Add link to developer guide to contributing.md to make it more discoverable.
Fix #5350
=> Add developer guide to Contributing.md

test/UnitTests/MSTestAdapter.UnitTests/MSTestSettingsTests.cs
removes some compiler warnings. and given this test is only to test an obsolete class, the warnings add little value
=> add disable CS0618  to MSTestSettingsTests

samples/Playground/DebuggerUtility.cs
since `ppbc` can be null https://learn.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-createbindctx#parameters
=> fix nullability of CreateBindCtx

test/UnitTests/Microsoft.Testing.Platform.UnitTests/Services/TestApplicationResultTests.cs
since one of the DataRows pass in a null, and we do null checks in the test on that parameter
=> fix nullability of argument in GetProcessExitCodeAsync_IgnoreExitCodes

src/Platform/Microsoft.Testing.Platform/Logging/FileLoggerProvider.cs
since `FileLogger` is never assigned to null
=> fix nullability in FileLoggerProvider

test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/MSTestAdapterSettingsTests.cs
since based on the code paths both can be null. so the null suppression `null!` is both not required and incorrect
=> fix nullability in TestableMSTestAdapterSettings

src/Analyzers/MSTest.SourceGeneration/MSTest.SourceGeneration.csproj
the settings make no sense for a source generator.
and never apply since the project doesnt even target a compatible TFM
=> remove Trimming, AOT, and SingleFile config from MSTest.SourceGeneration

src/Platform/Microsoft.Testing.Extensions.CrashDump/CrashDumpEnvironmentVariableProvider.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CrashDumpTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/CrashPlusHangDumpTests.cs
=> Use `GetFileNameWithoutExtension` for crashdump file name to be consistent with hangdump

src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxCompareTool.CommandLine.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/TreeNodeFilterCommandLineOptionsProvider.cs
Partially addresses #4294.
In future, we will probably want everything to be aligned by the platform and remove the `IExtension` parameter, and obsolete the relevant public APIs that accepts `IExtension`.
I'm going for the easier approach for now.
=> Consistent command-line options provider properties

src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/PassiveNode.cs
This makes much more sense to me instead of hard-coding 1.0.0 or having to manually bump it later on.
=> Use `PlatformVersion.Version` as the server version

src/Analyzers/MSTest.Analyzers/TestContextShouldBeValidAnalyzer.cs, test/UnitTests/MSTest.Analyzers.UnitTests/TestContextShouldBeValidAnalyzerTests.cs
=> Skip analyzing TestContext fields that are generated via primary constructor parameters

src/Platform/Microsoft.Testing.Extensions.AzureDevOps/AzureDevOpsCommandLineProvider.cs, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/AzureDevOpsReporter.cs, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/AzureDevOpsResources.resx, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.cs.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.de.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.es.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.fr.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.it.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.ja.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.ko.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.pl.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.ru.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.tr.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Extensions.AzureDevOps/Resources/xlf/AzureDevOpsResources.zh-Hant.xlf
@nohwnd Can you please validate that this still works as expected?
We may also need at least few basic unit tests.
=> Few improvements to AzDO extension

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs, src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/SerializerUtilities.cs, test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodePropertiesTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/ServerMode/FormatterUtilitiesTests.cs
- Instead of looping over the test properties, just read the relevant ones directly
- No need to copy anything from TestResult, as it doesn't have any property of interest. All properties of interest are on TestCase.
=> Cleanup and simplify ObjectModelConverters

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs
Hide whitespaces in diff for easier review.
This change basically still kills the test host even if writing the dump file fails, so that the process isn't stuck
=> Kill testhost if writing hang dump fails

src/Platform/Microsoft.Testing.Extensions.AzureDevOpsReport/Microsoft.Testing.Extensions.AzureDevOpsReport.csproj
RTM produced 1.0.0 not 1.0.0-alphaxxx.
=> Fix alpha branding on devops extension in rtm build

azure-pipelines-official.yml
Don't disable publish on the build, disable publish on the template. This way we should get the artifacts uploaded to azdo, but not pushed to nuget feeds.
We already disable pushing to test-tools nuget feed separately.
=> Disable publish step on rtm build

src/Analyzers/MSTest.Analyzers.CodeFixes/MSTest.Analyzers.CodeFixes.csproj, src/Analyzers/MSTest.Analyzers.CodeFixes/PublicAPI.Shipped.txt, src/Analyzers/MSTest.Analyzers.CodeFixes/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj, src/Analyzers/MSTest.Analyzers.Package/PublicAPI.Shipped.txt, src/Analyzers/MSTest.Analyzers.Package/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.GlobalConfigsGenerator/MSTest.GlobalConfigsGenerator.csproj, src/Analyzers/MSTest.GlobalConfigsGenerator/PublicAPI.Shipped.txt, src/Analyzers/MSTest.GlobalConfigsGenerator/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.Internal.Analyzers/MSTest.Internal.Analyzers.csproj, src/Analyzers/MSTest.Internal.Analyzers/PublicAPI.Shipped.txt, src/Analyzers/MSTest.Internal.Analyzers/PublicAPI.Unshipped.txt, src/Analyzers/MSTest.SourceGeneration/MSTest.SourceGeneration.csproj, src/Analyzers/MSTest.SourceGeneration/PublicAPI.Shipped.txt, src/Analyzers/MSTest.SourceGeneration/PublicAPI.Unshipped.txt, src/Platform/Microsoft.Testing.Extensions.MSBuild/Microsoft.Testing.Extensions.MSBuild.csproj, src/Platform/Microsoft.Testing.Extensions.MSBuild/PublicAPI.Shipped.txt, src/Platform/Microsoft.Testing.Extensions.MSBuild/PublicAPI.Unshipped.txt, src/Platform/Microsoft.Testing.Platform.MSBuild/Microsoft.Testing.Platform.MSBuild.csproj, src/Platform/Microsoft.Testing.Platform.MSBuild/PublicAPI.Shipped.txt, src/Platform/Microsoft.Testing.Platform.MSBuild/PublicAPI.Unshipped.txt
Add public api files to projects that were missing the. We are trying to keep the public apis minimal, to avoid users accidentally depending on api that we don't want to keep backwards compatible.
=> Add public api files

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
=> Run the whole ExecuteInternal logic under the right execution context

test/Utilities/Microsoft.Testing.TestInfrastructure/DotnetCli.cs
Tests often timeout in `DotnetCli.RunAsync`. Let's see if increasing the timeout can improve stability.
=> Increase DotnetCli.RunAsync timeout from 50s to 60s

src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs, src/Platform/Microsoft.Testing.Platform/Requests/TreeNodeFilter/TreeNodeFilter.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodePropertiesTests.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
=> Enable filtering with `TestMetadataProperty` in the treenode filter

src/Platform/Microsoft.Testing.Platform.MSBuild/buildMultiTargeting/Microsoft.Testing.Platform.MSBuild.targets
@rainersigwald We didn't see any issue, but that's how all comparisons we see look like. Is there known behavior difference? Or is it the same? It depends?
=> Add quotes around MSBuild property when performing comparison

src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
I never seen a case where `InvalidManagedNameException` is thrown in MSTest, but let's have the fallback path consistent with the main logic.
Fixes #4508
=> Fix fallback path for getting method info if InvalidManagedNameException is thrown

MSTest.slnf, TestFx.sln, src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs, src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs, test/UnitTests/MSTest.SelfRealExamples.UnitTests/MSTest.SelfRealExamples.UnitTests.csproj, test/UnitTests/MSTest.SelfRealExamples.UnitTests/Program.cs, test/UnitTests/MSTest.SelfRealExamples.UnitTests/TestExecutionContextPropagationFromTestMethodAttributeToTestMethod.cs
One more execution context bug :)
Also adding a new test project that's kinda in-between unit tests and integration tests. It's similar to Playground but intended to contain real tests. It can only test "positive" cases.
Fixes #5687
=> Ensure TestMethodAttribute.Execute is run on the correct execution context

src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs, src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
This works-around cases where binding redirects are not properly generated in consumer projects, either due to missing Microsoft.NET.Test.Sdk dependency, or due to reasons not yet known.
=> Avoid loading System.Threading.Tasks.Extensions when not needed

src/Adapter/MSTestAdapter.PlatformServices/Execution/ClassCleanupManager.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/ConsoleErrorCapturer.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/ConsoleOutCapturer.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestAssemblyInfo.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestClassInfo.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodInfo.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TraceTextWriter.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/IPlatformServiceProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/PlatformServiceProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/PlatformServiceProviderTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestContextImplementationTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
Fixes #2616
Instead of repeatedly setting Console.Out/Console.Error and resetting to original in a thread-unsafe way, we now set Conosle.Out/Console.Error once in the UnitTestRunner constructor.
Additionally, the logic of capturing is way simplified now.
Each step of the test lifecycle (asm init, asm cleanup, class init, test, class cleanup, and asm cleanup) will set its current TestContext. The current TestContext is async local, so it's isolated properly when running in parallel. Then when each step creates its test result, it just needs to get the data from the current test context.
The redirected out/error will simply write to the current test context if there is one, or write to the original if there isn't one. This simplifies the logic a lot and makes it much easier to follow.
Note …
=> Fix TraceListenerManager thread safety issue

src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTestAdapter.PlatformServices/Discovery/UnitTestDiscoverer.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs, src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ParameterizedTestTests.cs, test/UnitTests/MSTest.SelfRealExamples.UnitTests/ParameterizedTestSerializationIssue2390.cs
When we get a run request with a given filter, we do:
1. Discovery
- We call `UnitTestDiscoverer.DiscoverTestsInSource` which creates `UnitTestElement`s
- It then converts `UnitTestElement`s to `TestCase`s (VSTest object model), and sends the test cases to discovery sink.
2. Execution
- We call `ExecuteTestsAsync` with the `TestCase`s.
- We then convert back `TestCase`s to `UnitTestElement`s that we pass to `UnitTestRunner`.
During discovery, we already have the "real data". We are only starting to lose them when moving from `UnitTestElement`s to `TestCase`s.
This PR makes the following changes:
1. Updates `AssemblyEnumerator` to store the real/original data along with the serialized data.
2. `UnitTestDiscoverer.SendTestCases` can read the data set in the previous step, and store that in …
=> Store the actual data to instead of deserializing

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunSettingsPatcher.cs
`DisableAppDomain` is already `false` by default. In MSTest v4, if we decided to change the default, we want to make sure the bridge is following.
=> Cleanup RunSettingsPatcher

src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTestAdapter.PlatformServices/EngineConstants.cs, src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs, src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs, src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/ObjectModel/UnitTestElementTests.cs
=> Adjust TestCase.Id to account for randomized tests (include test case index instead of serialized data)

src/Adapter/MSTestAdapter.PlatformServices/Execution/ClassCleanupManager.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs, src/Adapter/MSTestAdapter.PlatformServices/IPlatformServiceProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/PlatformServiceProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, src/TestFramework/TestFramework.Extensions/TestContext.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadContextTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestAssemblyInfoTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestClassInfoTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodInfoTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodRunnerTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestPropertyAttributeTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TypeCacheTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/PlatformServiceProviderTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestContextImplementationTests.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
Code cleanup, and also ensures that class name is available when running class init/cleanup.
Related to #1285
=> TestContext cleanup

samples/FxExtensibility/FxExtensibility.csproj, src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj, src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj, src/Platform/Microsoft.Testing.Platform.MSBuild/Microsoft.Testing.Platform.MSBuild.csproj, src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj, src/TestFramework/TestFramework/TestFramework.csproj, test/IntegrationTests/TestAssets/TestProject/TestProjectForDiscovery.csproj
this was one of the blockers when i was working on https://github.com/microsoft/testfx/pull/4368
since those csproj ignored solution level constants
=> projects should inherit defined constants

src/Platform/Microsoft.Testing.Platform/Hosts/TestHostBuilder.cs
=> remove redundant environment instance in TestHostBuilder

azure-pipelines.yml
Shows whole stack trace for unhandled and other exceptions so we can investigate that "handle not initialized" error.
https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Parser.cs#L262-L265
=> Show whole error with stack trace

src/Adapter/MSTestAdapter.PlatformServices/Execution/TestExecutionManager.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadingTests.cs
This is one possible fix for #5920, and it's the "easy" fix.
We could go with adding our own synchronization context, which actually will ensure that async sta test methods will also continue on STA, which isn't (and was never) the case.
Maybe we can fix it better in v4 and add our custom synchronization context for both STATestMethodAttribute and the global setting as well?
=> Fix STA regression when async method completes asynchronously between sync methods

Directory.Packages.props, src/Platform/Microsoft.Testing.Extensions.TrxReport/TrxCompareTool.cs
=> use XElement.LoadAsync in TrxCompareTool

src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs, src/Platform/Microsoft.Testing.Platform/Requests/ConsoleTestExecutionFilterFactory.cs, src/Platform/Microsoft.Testing.Platform/Requests/ITestExecutionFilterFactory.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/HelpInfoTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/ExecutionTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
=> Support `--filter-uid` on console

src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
=> MSTest.TestAdapter depends upon MSTest.TestFramework

src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/SettingsProvider.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/MSTestSettingsProviderTests.cs
- IsRunSettingsFileHasMSTestSettings was unnecessarily parsing the XML twice.
- `MSTestAdapterSettings.Load(IConfiguration)` didn't have any side effect previously. We now correctly reflect that in the current settings.
Note that for MSTest-specific settings, we have a guard in place that prevents having settings both in runsettings and testconfig.json.
https://github.com/microsoft/testfx/blob/62ff112616e444cb5cf735724e1f030c2db3b428/src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs#L299-L304
So, `MSTestSettingsProvider.Load(XmlReader)` and `MSTestSettingsProvider.Load(IConfiguration)` are never both called. It's one of them at max will be called.
Fixes #6077
=> MSTest configuration improvement

azure-pipelines-official.yml, azure-pipelines.yml
It's still useful to have the test results in successful pipelines, to use them for comparison with failed ones for example.
=> Always publish TestResults folder

test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/ThreadSafeStringWriterTests.cs
Fixes #6094
Anyways, we no longer care about `ThreadSafeStringWriter`. The type is deprecated and we don't use it internally. We are removing it in v4.
=> Disable flaky test

src/Analyzers/MSTest.Analyzers/NonNullableReferenceNotInitializedSuppressor.cs, test/UnitTests/MSTest.Analyzers.UnitTests/NonNullableReferenceNotInitializedSuppressorTests.cs
Fixes https://github.com/microsoft/testfx/issues/6136
=> Fix nullability suppressor for TestContext when explicit constructor is declared

samples/Playground/Program.cs
This is so annoying when working with testfx locally.
=> Comment out AttachCurrentProcessToParentVSProcess

test/UnitTests/MSTest.Analyzers.UnitTests/UnusedParameterSuppressorTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseAsyncSuffixTestFixtureMethodSuppressorTests.cs, test/UnitTests/MSTest.Analyzers.UnitTests/UseAsyncSuffixTestMethodSuppressorTests.cs
=> Fix suppressors tests

src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
Fixes https://github.com/microsoft/testfx/issues/6152
=> Add missing `Func<object?>` overload to ThrowsExactly

eng/Version.Details.xml, eng/Versions.props
Reverts microsoft/testfx#6211
The PR was incorrectly merged to main instead of rel/3.10.
So reverting in main and opened https://github.com/microsoft/testfx/pull/6216 for 3.10
=> Revert "[rel/3.10] Use stable CC"

src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj, src/Analyzers/MSTest.SourceGeneration/MSTest.SourceGeneration.csproj
Brings consistency with the rest of the repo. Building is building only. It's unnecessary to produce packages when only build is requested.
=> Avoid generate package on build

src/Package/MSTest.Sdk/Sdk/Runner/ClassicEngine.targets
When a repo is fully onboarded to MTP and dotnet test, we should give the opportunity for developers to stop relying on VSTEst package. This should not be done by default, but as an opt-in, as some extra tools might be broken.
=> Allow to opt-out of Microsoft.NET.Test.Sdk

test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssemblyResolutionTests.cs, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/Helpers/AcceptanceAssert.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.GenerateEntryPoint.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/RetryFailedTestsTests.cs
From time to time I see failures in CI that look like the following:
```
failed Invalid_TestingProfile_Name_Should_Fail ("net9.0;net8.0;net7.0;net6.0;net462",Debug) (6s 220ms)
Assert.AreEqual failed. Expected:<1>. Actual:<-532462766>. 
at MSTest.Acceptance.IntegrationTests.SdkTests.Invalid_TestingProfile_Name_Should_Fail(String multiTfm, BuildConfiguration buildConfiguration) in /_/test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs:280
```
The change in this PR should provide better message, including standard output and standard error.
=> Improve assertions for DotnetMuxerResult.ExitCode

src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestContextImplementationTests.cs
Hopefully fixes #6246
Ideally, we should also set a flag in TestContext before we call `GetOut` or `GetError`, and have the `Console[Out|Error]Router` check it before writing. If the flag is true already, write to original console out/err.
=> Fix race in TestContextImplementation

test/Directory.Build.targets
This property is no longer used. No projects are setting it, so it's always true.
Follow-up to https://github.com/microsoft/testfx/pull/6234
=> Cleanup test/Directory.Build.targets

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
=> Fix terminal reporter when architecture is null

src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
`ApplicationStateGuard.Unreachable` only creates an instance of UnreachableException, but it doesn't throw.
=> Fix missing "throw" for unreachable code path in FormatStringComparisonMessage

src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs, src/Adapter/MSTestAdapter.PlatformServices/Discovery/TypeEnumerator.cs, src/Adapter/MSTestAdapter.PlatformServices/Discovery/UnitTestDiscoverer.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TypeCache.cs, src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs, src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs, src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs, src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
Part of #6317
We still cannot remove it entirely because of appdomains...
Adding 10k empty test methods in Playground, using MTP, and parallelization not enabled. Executing the "exe" directly from `artifacts/bin/Playground/Debug/net9.0/Playground.exe`
```
Test run summary: Passed! - C:\Users\ygerges\Desktop\testfx\artifacts\bin\Playground\Debug\net9.0\Playground.dll (net9.0|x64)
total: 10000
failed: 0
succeeded: 10000
skipped: 0
duration: 11s 881ms
```
- Process wall-time: 15s
- Process CPU time: 13s
CPU stacks sorted by exclusive time:
(NOTE: ManagedNameHelper.GetMethod inclusive CPU time is 6.5s, around 50% of total CPU time)
Memory:
```
Test run summary: Passed! - C:\Users\ygerges\Desktop\testfx\artifacts\bin\Playground\Debug\net9.0\Playground.dll (net9.0|x64)
total: 10000
failed: 0 …
```
=> Avoid ManagedNameHelper when possible

src/TestFramework/TestFramework/Assertions/Assert.cs, src/TestFramework/TestFramework/Assertions/CollectionAssert.cs, src/TestFramework/TestFramework/Assertions/StringAssert.cs, src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt, test/IntegrationTests/TestAssets/FxExtensibilityTestProject/AssertExTest.cs, test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.cs, test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs, test/UnitTests/TestFramework.UnitTests/Assertions/StringAssertTests.cs
Reverts https://github.com/microsoft/testfx/pull/5811 per user feedback.
=> Revert Assert.That obsoletion

src/Adapter/MSTestAdapter.PlatformServices/Discovery/UnitTestDiscoverer.cs
In a scenario with too many tests:
Accessing `Traits` property on `TestCase` causes VSTest to force materializing a TraitCollection, even if we don't have any traits. Accessing the traits from MSTest model is cheaper.
=> Avoid accessing TestCase.Traits when possible

src/Adapter/MSTestAdapter.PlatformServices/Execution/TypeCache.cs, src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs
About 4.5% of allocations are iterator allocations when running 10k tests in a test class.
=> Avoid iterator allocations

src/Adapter/MSTestAdapter.PlatformServices/Execution/TcmTestPropertiesProvider.cs, src/Adapter/MSTestAdapter.PlatformServices/Execution/TestExecutionManager.cs, test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TcmTestPropertiesProviderTests.cs
Unnecessary empty dictionary allocation is 3.1% of allocations when running 10k tests in a test class:
`null` can be used instead of the empty dictionary, and null-check is done on the callsite.
=> Optimize tcm properties

src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs
Scenario: 100 test class, each containing 2000 test method.
=> Avoid unnecessary `List<string>` allocations in ObjectModelConverters

.editorconfig
Currently it applies to everything which is annoying. For example, when hand-editing resx files
=> Don't set insert_final_newline for xlf/resx files

src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs, src/Platform/Microsoft.Testing.Platform/Helpers/PasteArguments.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
Fixes https://github.com/microsoft/testfx/issues/6277
=> Fix command-line arguments escaping when retry and test host controllers start child processes

src/Platform/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs, src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs
Follow-up per https://github.com/microsoft/testfx/pull/6462#pullrequestreview-3168081208
=> Add clarifying comments for command-line arg escaping

src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs, src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs, src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf, test/IntegrationTests/MSTest.Acceptance.IntegrationTests/HelpInfoTests.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpInfoTests.cs
Fixes #5531
I went with `--debug-attach` as it seems more natural and closer to reality than `--debug` to me. This is also aligned with naming on sdk [--debug: attach](https://github.com/dotnet/templating/blob/main/docs/Reserved-Aliases.md)
Another option would be to use `--debug attach` so we could add more debug modes in the future.
=> Add --debug-attach option to MTP

src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
Possibly fixes https://github.com/microsoft/testfx/issues/6492 which likely regressed in https://github.com/microsoft/testfx/pull/6037
=> Clean TestProgressState on TestExecutionCompleted

src/Platform/Microsoft.Testing.Platform/IPC/Serializers/BaseSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/CommandLineOptionMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/DiscoveredTestMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/FileArtifactMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/HandshakeMessageSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/TestResultMessagesSerializer.cs, src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/TestSessionEventSerializer.cs
This rename reflects the actual semantics of the method.
A similar change is needed on dotnet/sdk too.
=> Rename ReadShort and WriteShort to ReadUShort and WriteUShort

src/Platform/Microsoft.Testing.Platform/ServerMode/DotnetTest/IPC/Serializers/HandshakeMessageSerializer.cs, test/UnitTests/Microsoft.Testing.Platform.UnitTests/IPC/ProtocolTests.cs
Today, the dictionary is never null or empty, so we can never encounter the bug.
However, let's keep the implementation correct in all cases.
=> Fix handshake serialization if properties dictionary is null or empty

src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs, src/Platform/Microsoft.Testing.Platform/IPC/PipeNameDescription.cs
=> Avoid long path issues for pipes

src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpExtensions.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/Helpers/Class1.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/Helpers/IProcessExtensions.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/Helpers/ProcessTreeNode.cs, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/ExtensionResources.resx, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.cs.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.de.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.es.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.fr.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.it.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ja.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ko.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.pl.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.pt-BR.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.ru.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.tr.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.zh-Hans.xlf, src/Platform/Microsoft.Testing.Extensions.HangDump/Resources/xlf/ExtensionResources.zh-Hant.xlf, src/Platform/Microsoft.Testing.Platform/Helpers/System/IProcess.cs, src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemProcess.cs, test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HangDumpProcessTreeTests.cs
Collect tree of processes and dump them from the bottom up, skipping werFault (dump reporter on windows) and conhost (console host on windows). 
Report all dumps that were collected, together with the tree of processes that we will dump.
Reduce verbosity of the dumper, to not show thousands of lines per dump, seeing memory addresses etc. is not usually useful, and makes it really hard to see what actually happened when stuff goes wrong, e.g. when the process completes after the hang timeout, and so we cannot dump it anymore. (We cannot suspend the processes while dumping them - on .net core dumper it prevents the dumper from working, on .net framework, we don't have documented api to do this, and so we get flagged by compliance).
The way dumps are created depends on the testhost process, …
=> Dump child process on hang

eng/mark-shipped.ps1
Utf8 encoding means utf8 with BOM in the old windows powershell, modern powershell makes that mean utf8 without BOM.
Require powershell 7 to run the script.
=> Add requires to script to make it work constistently
